//! A-19: every refusal driven red on a planted defect, each for its own reason, and the
//! registry on this tree green.

use std::path::{Path, PathBuf};

use super::*;

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// The fixture crate. Its harness attribute is spelled `HARNESS` and filled in by [`lib`]: the
/// proof-count census greps for the attribute at line start, and a fixture is not a harness.
/// For the same reason `mod proofs` carries no `cfg` attribute: the divergence census counts
/// those.
const LIB: &str = r#"
pub fn admit(x: u8) -> bool {
    x < 10
}

pub struct Gate;

impl Gate {
    pub fn open(&self, x: u8) -> bool {
        admit(x)
    }
}

mod proofs {
    use super::*;

    #[HARNESS]
    fn proof_admit() {
        let x: u8 = kani::any();
        let v = admit(x);
        assert_eq!(v, x < 10);
        kani::cover!(v, "an admitted value exists");
    }

    // The issue's trivial harness: names the function, proves nothing.
    #[HARNESS]
    fn proof_trivial() {
        let _ = admit(kani::any());
    }

    // Ends in a cover, but never calls what it would be registered as proving.
    #[HARNESS]
    fn proof_unrelated() {
        let x: u8 = kani::any();
        kani::cover!(x > 1);
    }

    #[HARNESS]
    fn proof_never() {
        let x: u8 = kani::any();
        assert!(admit(x) == (x < 10));
        kani::cover!(false);
    }

    #[HARNESS]
    fn proof_unscheduled() {
        let x: u8 = kani::any();
        assert!(admit(x) == (x < 10));
        kani::cover!();
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn parity_admit() {
        assert!(super::admit(1));
    }

    #[test]
    fn parity_open() {
        assert!(super::Gate.open(1));
    }

    pub fn helper() {}
}
"#;

fn lib() -> String {
    LIB.replace("#[HARNESS]", concat!("#[kani", "::proof]"))
}

const FUNS: &str = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [demo]: function definitions
import Aeneas
open Aeneas Aeneas.Std Result

namespace demo

/-- [demo::admit]:
    Source: 'crates/demo/src/lib.rs', lines 2:0-4:1
    Visibility: public -/
def admit (x : U8) : Result Bool := do
  ok (x < 10#u8)

/-- [demo::{demo::Gate}::open]:
    Source: 'crates/demo/src/lib.rs', lines 9:4-11:5
    Visibility: public -/
def Gate.open (self : Gate) (x : U8) : Result Bool := do
  admit x

end demo
"#;

const PROOFS: &str = r#"import Demo.Funs
open Aeneas.Std Result

/-- `admit` accepts nine. -/
theorem admit_nine : demo.admit 9#u8 = ok true := by rfl

/-- The planted vacuous theorem: about nothing. -/
theorem admit_planted : True := trivial

def mirrorAdmit (x : Nat) : Bool := x < 10

theorem mirror_admit_nine : mirrorAdmit 9 = true := rfl
"#;

const KANI_WORKFLOW: &str = "jobs:\n  kani:\n    steps:\n      - uses: model-checking/kani-github-action@pin\n        with:\n          args: >-\n            -p demo\n            --harness proof_admit\n            --harness proof_trivial\n            --harness proof_unrelated\n            --harness proof_never\n";

const LEAN_WORKFLOW: &str = "jobs:\n  lean:\n    steps:\n      - uses: leanprover/lean-action@pin\n        with:\n          build: 'true'\n          lake-package-directory: crates/demo/lean\n          build-args: Proofs\n";

const LAKEFILE: &str = "package «demo» where\n\nlean_lib «Gen» where\n  roots := #[`Demo.Funs]\n  srcDir := \"generated\"\n\nlean_lib «Proofs» where\n  roots := #[`Proofs]\n";

fn write(root: &Path, path: &str, text: &str) {
    let p = root.join(path);
    std::fs::create_dir_all(p.parent().unwrap()).unwrap();
    std::fs::write(p, text).unwrap();
}

fn fixture() -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        "Cargo.toml",
        "[workspace]\nmembers = [\"crates/demo\"]\n",
    );
    write(
        root,
        "crates/demo/Cargo.toml",
        "[package]\nname = \"demo\"\n",
    );
    write(root, "crates/demo/src/lib.rs", &lib());
    write(root, ".github/workflows/kani.yml", KANI_WORKFLOW);
    write(root, ".github/workflows/lean.yml", LEAN_WORKFLOW);
    write(root, "crates/demo/lean/lakefile.lean", LAKEFILE);
    write(
        root,
        "crates/demo/lean/lake-manifest.json",
        "{\"packages\":[]}",
    );
    write(root, "crates/demo/lean/generated/Demo/Funs.lean", FUNS);
    write(root, "crates/demo/lean/Proofs.lean", PROOFS);
    write(
        root,
        "crates/demo/lean/Orphan.lean",
        "theorem orphan : demo.admit 1#u8 = ok true := by rfl\n",
    );
    dir
}

const PASSING: &str = r##"
[[obligation]]
function = "demo::admit"
kind = "kani"
artifact = "crates/demo/src/lib.rs::proof_admit"
status = "proved"

[[obligation]]
function = "demo::admit"
kind = "lean-extracted"
artifact = "crates/demo/lean/Proofs.lean::admit_nine"
status = "proved"

[[obligation]]
function = "demo::admit"
kind = "lean-mirror"
artifact = "crates/demo/lean/Proofs.lean::mirror_admit_nine"
constant = "mirrorAdmit"
status = "proved"

[[obligation]]
function = "demo::admit"
kind = "parity"
artifact = "crates/demo/src/lib.rs::parity_admit"
status = "proved"

[[obligation]]
function = "demo::Gate::open"
kind = "missing"
status = "allowlisted"
tracking = "#1"
"##;

/// The one row, checked against the fixture: its violations.
fn violations_of(row: &str) -> Vec<String> {
    let dir = fixture();
    let (_, _, errors) = violations(dir.path(), row).unwrap();
    errors
}

/// Red, exactly once, and for the reason named — not for some other refusal.
fn red_for(row: &str, reason: &str) {
    let errors = violations_of(row);
    assert_eq!(
        errors.len(),
        1,
        "expected exactly one violation, got {errors:#?}"
    );
    assert!(
        errors[0].contains(reason),
        "red for the wrong reason: {errors:#?}"
    );
}

#[test]
fn every_kind_passes_on_a_real_artifact() {
    assert_eq!(violations_of(PASSING), Vec::<String>::new());
}

#[test]
fn a_planted_trivial_harness_fails_for_lacking_a_terminal_cover() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"kani\"\nartifact = \"crates/demo/src/lib.rs::proof_trivial\"\nstatus = \"proved\"\n",
        "does not end with `kani::cover!`",
    );
}

#[test]
fn a_harness_that_never_calls_the_function_fails() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"kani\"\nartifact = \"crates/demo/src/lib.rs::proof_unrelated\"\nstatus = \"proved\"\n",
        "does not reference `admit`",
    );
}

#[test]
fn a_cover_of_false_fails() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"kani\"\nartifact = \"crates/demo/src/lib.rs::proof_never\"\nstatus = \"proved\"\n",
        "kani::cover!(false",
    );
}

#[test]
fn a_harness_no_workflow_runs_fails() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"kani\"\nartifact = \"crates/demo/src/lib.rs::proof_unscheduled\"\nstatus = \"proved\"\n",
        "run by no workflow",
    );
}

#[test]
fn a_planted_true_theorem_fails_for_not_mentioning_the_constant() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"lean-extracted\"\nartifact = \"crates/demo/lean/Proofs.lean::admit_planted\"\nstatus = \"proved\"\n",
        "does not mention demo.admit",
    );
}

#[test]
fn a_theorem_no_workflow_builds_is_unreachable() {
    red_for(
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"lean-extracted\"\nartifact = \"crates/demo/lean/Orphan.lean::orphan\"\nstatus = \"proved\"\n",
        "unreachable",
    );
}

#[test]
fn a_renamed_function_fails() {
    // The real artifact, the function renamed in the source: only the existence check fires.
    let dir = fixture();
    write(
        dir.path(),
        "crates/demo/src/lib.rs",
        &lib().replace("pub fn admit(x: u8)", "pub fn admit_renamed(x: u8)"),
    );
    let (_, _, errors) = violations(
        dir.path(),
        "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"parity\"\nartifact = \"crates/demo/src/lib.rs::parity_admit\"\nstatus = \"proved\"\n",
    )
    .unwrap();
    assert_eq!(errors.len(), 1, "{errors:#?}");
    assert!(errors[0].contains("no longer exists"), "{errors:#?}");
}

#[test]
fn a_missing_row_must_be_allowlisted_and_not_stale() {
    red_for(
        "[[obligation]]\nfunction = \"demo::Gate::open\"\nkind = \"missing\"\nstatus = \"proved\"\n",
        "not allowlisted",
    );
    red_for(
        "[[obligation]]\nfunction = \"demo::Gate::open\"\nkind = \"missing\"\nstatus = \"allowlisted\"\n",
        "needs a `tracking` issue",
    );
    let stale = format!(
        "{PASSING}\n[[obligation]]\nfunction = \"demo::admit\"\nkind = \"missing\"\nstatus = \"allowlisted\"\ntracking = \"#2\"\n"
    );
    let errors = violations_of(&stale);
    assert_eq!(errors.len(), 1, "{errors:#?}");
    assert!(errors[0].contains("stale"), "{errors:#?}");
}

#[test]
fn test_only_code_cannot_carry_an_obligation() {
    red_for(
        "[[obligation]]\nfunction = \"demo::tests::helper\"\nkind = \"missing\"\nstatus = \"allowlisted\"\ntracking = \"#1\"\n",
        "test-only",
    );
}

#[test]
fn a_source_hash_pin_moves_with_the_code() {
    let dir = fixture();
    let row = |hash: &str| {
        format!(
            "[[obligation]]\nfunction = \"demo::admit\"\nkind = \"parity\"\nartifact = \"crates/demo/src/lib.rs::parity_admit\"\nstatus = \"proved\"\nsource_hash = \"{hash}\"\n"
        )
    };
    let (_, _, errors) = violations(dir.path(), &row("0")).unwrap();
    let now = errors[0]
        .rsplit("now ")
        .next()
        .unwrap()
        .trim_end_matches(')')
        .to_string();
    assert_eq!(
        violations(dir.path(), &row(&now)).unwrap().2,
        Vec::<String>::new()
    );
    // A comment is not code: the pin holds.
    write(
        dir.path(),
        "crates/demo/src/lib.rs",
        &lib().replace("    x < 10\n}", "    // bound\n    x < 10\n}"),
    );
    assert_eq!(
        violations(dir.path(), &row(&now)).unwrap().2,
        Vec::<String>::new()
    );
    // A code edit moves it.
    write(
        dir.path(),
        "crates/demo/src/lib.rs",
        &lib().replace("    x < 10\n}", "    x < 11\n}"),
    );
    let errors = violations(dir.path(), &row(&now)).unwrap().2;
    assert_eq!(errors.len(), 1, "{errors:#?}");
    assert!(
        errors[0].contains("changed since its source_hash"),
        "{errors:#?}"
    );
}

#[test]
fn the_registry_refuses_duplicates_unknown_fields_and_emptiness() {
    let row = "[[obligation]]\nfunction = \"a::b\"\nkind = \"kani\"\nartifact = \"x::y\"\nstatus = \"proved\"\n";
    assert!(parse(&format!("{row}{row}")).is_err());
    assert!(parse(&row.replace("status", "statsu")).is_err());
    assert!(parse(&row.replace("\"kani\"", "\"kanni\"")).is_err());
    assert!(parse("obligation = []").is_err());
}

#[test]
fn lean_statements_end_at_the_proof_and_mentions_need_two_segments() {
    let ts = lean::theorems(
        "@[simp] private theorem a (x : Nat) :\n    demo.admit x = ok true := by\n  simp\n-- theorem commented : demo.admit\ntheorem b : True := trivial\nlemma c {s : S := 1} : Gate.open s = 1 := rfl\n",
    );
    let names: Vec<_> = ts.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(names, ["a", "b", "c"]);
    assert!(lean::mentions(&ts[0].statement, "demo.admit", &[]));
    assert!(!ts[0].statement.contains("simp"));
    assert!(!lean::mentions(&ts[1].statement, "demo.admit", &[]));
    assert!(lean::mentions(&ts[2].statement, "demo.Gate.open", &[]));
    // A bare last segment is a coincidence, not a mention ...
    assert!(!lean::mentions(
        "(h : admit x = ok true)",
        "demo.admit",
        &[]
    ));
    assert!(!lean::mentions("demo.admitted x", "demo.admit", &[]));
    // ... unless the file opens the namespace that makes it the constant.
    let scopes =
        lean::scopes("open Aeneas demo (Gate)\n-- open nope\nnamespace Proofs\nopen other in\n");
    assert_eq!(scopes, ["Aeneas", "demo", "Proofs", "other"]);
    assert!(lean::mentions(
        "(h : admit x = ok true)",
        "demo.admit",
        &scopes
    ));
    assert!(!lean::mentions(
        "(h : admit x = ok true)",
        "elsewhere.admit",
        &scopes
    ));
}

#[test]
fn aeneas_paths_normalize_to_symbol_keys() {
    assert_eq!(
        lean::normalize_aeneas_path(
            "nucleus_ifc_kernel::exposure::{nucleus_ifc_kernel::exposure::ExposureSet}::set"
        )
        .as_deref(),
        Some("nucleus_ifc_kernel::exposure::ExposureSet::set")
    );
    assert_eq!(
        lean::normalize_aeneas_path("k::m::{k::m::Ledger<T>}::spend").as_deref(),
        Some("k::m::Ledger::spend")
    );
    assert_eq!(
        lean::normalize_aeneas_path("k::{impl core::cmp::PartialEq<k::A> for k::A}::eq"),
        None
    );
    let e = lean::extracted(FUNS).unwrap();
    assert_eq!(
        e,
        [
            lean::Extracted {
                function: "demo::admit".into(),
                constant: "demo.admit".into()
            },
            lean::Extracted {
                function: "demo::Gate::open".into(),
                constant: "demo.Gate.open".into()
            },
        ]
    );
    assert!(lean::extracted(PROOFS).is_none());
}

#[test]
fn a_function_a_binary_defines_resolves() {
    let dir = fixture();
    write(
        dir.path(),
        "crates/demo/src/main.rs",
        "fn main() {}\n\nfn remount() -> bool {\n    true\n}\n",
    );
    let (_, _, errors) = violations(
        dir.path(),
        "[[obligation]]\nfunction = \"demo::remount\"\nkind = \"missing\"\nstatus = \"allowlisted\"\ntracking = \"#1\"\n",
    )
    .unwrap();
    assert_eq!(errors, Vec::<String>::new());
    // The library and the binary both defining one path is ambiguous, not first-walked-wins.
    write(
        dir.path(),
        "crates/demo/src/main.rs",
        "fn main() {}\n\npub fn admit(x: u8) -> bool {\n    x < 11\n}\n",
    );
    let err = violations(dir.path(), PASSING).unwrap_err();
    assert!(
        format!("{err:#}").contains("more than one of the crate's targets"),
        "{err:#}"
    );
}

/// The registry the ratchet tests start from: one gap still missing (`Gate::open`).
const RATCHETED: &str = PASSING;

fn discharged() -> String {
    // `Gate::open`'s gap closed: its `missing` row became the proof's row, `tracking` kept.
    PASSING.replace(
        "function = \"demo::Gate::open\"\nkind = \"missing\"\nstatus = \"allowlisted\"",
        "function = \"demo::Gate::open\"\nkind = \"parity\"\nartifact = \"crates/demo/src/lib.rs::parity_open\"\nstatus = \"proved\"",
    )
}

#[test]
fn the_ratchet_holds_at_its_ceiling() {
    let (gaps, errors) = ratchet(RATCHETED, 1).unwrap();
    assert_eq!(
        gaps,
        Gaps {
            missing: 1,
            discharged: 0
        }
    );
    assert_eq!(errors, Vec::<String>::new());
}

#[test]
fn a_new_missing_row_is_over_the_ceiling() {
    let grown = format!(
        "{RATCHETED}\n[[obligation]]\nfunction = \"demo::tests::helper\"\nkind = \"missing\"\nstatus = \"allowlisted\"\ntracking = \"#3\"\n"
    );
    let (_, errors) = ratchet(&grown, 1).unwrap();
    assert_eq!(errors.len(), 1, "{errors:#?}");
    assert!(errors[0].contains("a new `missing` row"), "{errors:#?}");
}

#[test]
fn a_missing_row_deleted_without_a_proof_is_under_the_ceiling() {
    let start = RATCHETED
        .find("[[obligation]]\nfunction = \"demo::Gate::open\"")
        .unwrap();
    let deleted = &RATCHETED[..start];
    let (gaps, errors) = ratchet(deleted, 1).unwrap();
    assert_eq!(gaps.missing, 0);
    assert_eq!(errors.len(), 1, "{errors:#?}");
    assert!(errors[0].contains("without a proof"), "{errors:#?}");
}

#[test]
fn a_discharged_gap_lowers_missing_without_touching_the_ceiling() {
    let text = discharged();
    assert_eq!(violations_of(&text), Vec::<String>::new());
    let (gaps, errors) = ratchet(&text, 1).unwrap();
    assert_eq!(
        gaps,
        Gaps {
            missing: 0,
            discharged: 1
        }
    );
    assert_eq!(errors, Vec::<String>::new());
}

#[test]
fn the_ceiling_must_be_read_not_assumed() {
    assert_eq!(parse_ceiling("# c\nMISSING_CEILING=7\n").unwrap(), 7);
    assert!(parse_ceiling("# no line\n").is_err());
    assert!(parse_ceiling("MISSING_CEILING=\n").is_err());
    assert!(parse_ceiling("MISSING_CEILING=1\nMISSING_CEILING=2\n").is_err());
    assert!(missing_ceiling(fixture().path()).is_err());
}

/// The committed registry holds on this tree: every seeded row passes, and the missing ratchet
/// sits exactly at its ceiling.
#[test]
fn the_committed_registry_holds() {
    let (total, _, gaps, errors) = check(&repo()).unwrap();
    assert!(total > 0);
    assert!(
        gaps.missing > 0,
        "the ratchet counted no missing row: {gaps:?}"
    );
    assert_eq!(errors, Vec::<String>::new());
}
