-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreEgress.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::egress::netmask]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 88:0-125:1
    Visibility: public -/
def extracted.egress.netmask (prefix1 : Std.U8) : Result Std.U32 := do
  match prefix1 with
  | 0#uscalar => ok 0#u32
  | 1#uscalar => ok 2147483648#u32
  | 2#uscalar => ok 3221225472#u32
  | 3#uscalar => ok 3758096384#u32
  | 4#uscalar => ok 4026531840#u32
  | 5#uscalar => ok 4160749568#u32
  | 6#uscalar => ok 4227858432#u32
  | 7#uscalar => ok 4261412864#u32
  | 8#uscalar => ok 4278190080#u32
  | 9#uscalar => ok 4286578688#u32
  | 10#uscalar => ok 4290772992#u32
  | 11#uscalar => ok 4292870144#u32
  | 12#uscalar => ok 4293918720#u32
  | 13#uscalar => ok 4294443008#u32
  | 14#uscalar => ok 4294705152#u32
  | 15#uscalar => ok 4294836224#u32
  | 16#uscalar => ok 4294901760#u32
  | 17#uscalar => ok 4294934528#u32
  | 18#uscalar => ok 4294950912#u32
  | 19#uscalar => ok 4294959104#u32
  | 20#uscalar => ok 4294963200#u32
  | 21#uscalar => ok 4294965248#u32
  | 22#uscalar => ok 4294966272#u32
  | 23#uscalar => ok 4294966784#u32
  | 24#uscalar => ok 4294967040#u32
  | 25#uscalar => ok 4294967168#u32
  | 26#uscalar => ok 4294967232#u32
  | 27#uscalar => ok 4294967264#u32
  | 28#uscalar => ok 4294967280#u32
  | 29#uscalar => ok 4294967288#u32
  | 30#uscalar => ok 4294967292#u32
  | 31#uscalar => ok 4294967294#u32
  | 32#uscalar => ok 4294967295#u32
  | _ => ok 4294967295#u32

/-- [nucleus_ifc_kernel::extracted::egress::in_cidr]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 133:0-136:1
    Visibility: public -/
def extracted.egress.in_cidr
  (net : Std.U32) (prefix1 : Std.U8) (addr : Std.U32) : Result Bool := do
  let m ← extracted.egress.netmask prefix1
  let i ← lift (net &&& m)
  let i1 ← lift (addr &&& m)
  ok (i = i1)

/-- [nucleus_ifc_kernel::extracted::egress::rule_matches]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 139:0-147:1
    Visibility: public -/
def extracted.egress.rule_matches
  (rule : extracted.egress.Rule) (dest : extracted.egress.Dest) :
  Result Bool
  := do
  let b ← extracted.egress.in_cidr rule.net rule.«prefix» dest.addr
  if b
  then if rule.port_specific
       then ok (rule.port = dest.port)
       else ok true
  else ok false

/-- [nucleus_ifc_kernel::extracted::egress::rule_admits]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 154:0-156:1
    Visibility: public -/
def extracted.egress.rule_admits
  (rule : extracted.egress.Rule) (dest : extracted.egress.Dest) :
  Result Bool
  := do
  let b ← extracted.egress.rule_matches rule dest
  if b
  then ok rule.allow
  else ok false

end nucleus_ifc_kernel
