-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::egress::Dest]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 49:0-54:1
    Visibility: public -/
structure extracted.egress.Dest where
  addr : Std.U32
  port : Std.U16

/-- [nucleus_ifc_kernel::extracted::egress::Rule]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 58:0-69:1
    Visibility: public -/
structure extracted.egress.Rule where
  net : Std.U32
  «prefix» : Std.U8
  port_specific : Bool
  port : Std.U16
  allow : Bool

end nucleus_ifc_kernel
