// Node smoke test for @coproduct/verify — the wedge's core claim.
//
// 1. A REAL fixture bundle (generated by
//    `cargo run -p nucleus-envelope --example emit_demo_bundle`, self-verified
//    by that example incl. a tamper-rejection assertion) VERIFIES.
// 2. A TAMPERED copy (one byte of an Ed25519 signature flipped) is REJECTED.
//
// No fake data: both inputs are the same fixtures the in-browser demo uses.
// Requires ./pkg to exist — run `npm run build:wasm` first (CI builds it).

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { verify, VerifyError } from "../index.js";

const fixtureDir = new URL("../demo-fixtures/", import.meta.url);

async function readJson(name) {
  const text = await readFile(fileURLToPath(new URL(name, fixtureDir)), "utf8");
  return JSON.parse(text);
}

test("accepts a real, untampered fixture bundle", async () => {
  const bundle = await readJson("bundle.json");
  const anchor = await readJson("trust-anchor.json");

  const r = await verify(bundle, anchor);

  assert.equal(r.ok, true, `expected ok, got error: ${r.ok ? "" : r.error.message}`);
  assert.equal(r.report.ok, true);
  assert.ok(r.report.edge_count > 0, "expected at least one edge");
  assert.equal(r.report.trust_mode, "out_of_band");
  assert.equal(r.report.merkle_verified, true);
  assert.equal(r.report.head_edge_hash_hex.length, 64);
});

test("rejects a tampered bundle (one flipped signature byte)", async () => {
  const bundle = await readJson("bundle.json");
  const anchor = await readJson("trust-anchor.json");

  // Flip the first base64 char of the first edge's Ed25519 signature — the
  // smallest possible tamper. The local verifier must refuse it.
  const sig = bundle.envelope.edges[0].proof.sig;
  const c0 = sig[0];
  bundle.envelope.edges[0].proof.sig = (c0 === "A" ? "B" : "A") + sig.slice(1);

  const r = await verify(bundle, anchor);

  assert.equal(r.ok, false, "tampered bundle must NOT verify");
  assert.ok(r.error instanceof VerifyError);
  assert.equal(r.error.code, "VERIFICATION");
  assert.ok(r.error.message.length > 0, "rejection should carry a reason");
});

test("string inputs work identically to object inputs", async () => {
  const bundleStr = await readFile(
    fileURLToPath(new URL("bundle.json", fixtureDir)),
    "utf8",
  );
  const anchorStr = await readFile(
    fileURLToPath(new URL("trust-anchor.json", fixtureDir)),
    "utf8",
  );

  const r = await verify(bundleStr, anchorStr);
  assert.equal(r.ok, true);
});

test("malformed receipt surfaces a typed VERIFICATION error, not a throw", async () => {
  const anchor = await readJson("trust-anchor.json");
  // Valid JSON, invalid Bundle shape — WASM should reject at parse, the facade
  // turns the throw into a typed result.
  const r = await verify({ not: "a bundle" }, anchor);
  assert.equal(r.ok, false);
  assert.ok(r.error instanceof VerifyError);
  assert.equal(r.error.code, "VERIFICATION");
});
