-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: function definitions
import Aeneas
import PortcullisCoreCertChain.Types
import PortcullisCoreCertChain.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace portcullis_core

/-- [portcullis_core::certchain::chain_attenuates::{impl core::ops::function::FnMut<((bool, L), &'_ L), (bool, L)> for portcullis_core::certchain::chain_attenuates::closure<L>}::call_mut]:
    Source: 'crates/portcullis-core/src/certchain.rs', lines 52:36-55:9 -/
def
  certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnMutPairPairBoolLSharedLPairBoolL.call_mut
  {L : Type} (categoryLatticeInst : category.Lattice L)
  (c : certchain.chain_attenuates.closure L) (tupled_args : ((Bool × L) × L))
  :
  Result ((Bool × L) × (certchain.chain_attenuates.closure L))
  := do
  let ((ok1, prev), next) := tupled_args
  let step ← if ok1
               then categoryLatticeInst.leq next prev
               else ok false
  let t ← categoryLatticeInst.corecloneCloneInst.clone next
  ok ((step, t), c)

/-- [portcullis_core::certchain::chain_attenuates::{impl core::ops::function::FnOnce<((bool, L), &'_ L), (bool, L)> for portcullis_core::certchain::chain_attenuates::closure<L>}::call_once]:
    Source: 'crates/portcullis-core/src/certchain.rs', lines 52:36-55:9 -/
def
  certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnOncePairPairBoolLSharedLPairBoolL.call_once
  {L : Type} (categoryLatticeInst : category.Lattice L)
  (c : certchain.chain_attenuates.closure L) (p : ((Bool × L) × L)) :
  Result (Bool × L)
  := do
  let (p1, _) ←
    certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnMutPairPairBoolLSharedLPairBoolL.call_mut
      categoryLatticeInst c p
  ok p1

/-- Trait implementation: [portcullis_core::certchain::chain_attenuates::{impl core::ops::function::FnOnce<((bool, L), &'_ L), (bool, L)> for portcullis_core::certchain::chain_attenuates::closure<L>}]
    Source: 'crates/portcullis-core/src/certchain.rs', lines 52:36-55:9 -/
@[reducible]
def
  certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnOncePairPairBoolLSharedLPairBoolL
  {L : Type} (categoryLatticeInst : category.Lattice L) :
  core.ops.function.FnOnce (certchain.chain_attenuates.closure L) ((Bool × L)
  × L) (Bool × L) := {
  call_once :=
    certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnOncePairPairBoolLSharedLPairBoolL.call_once
    categoryLatticeInst
}

/-- Trait implementation: [portcullis_core::certchain::chain_attenuates::{impl core::ops::function::FnMut<((bool, L), &'_ L), (bool, L)> for portcullis_core::certchain::chain_attenuates::closure<L>}]
    Source: 'crates/portcullis-core/src/certchain.rs', lines 52:36-55:9 -/
@[reducible]
def
  certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnMutPairPairBoolLSharedLPairBoolL
  {L : Type} (categoryLatticeInst : category.Lattice L) :
  core.ops.function.FnMut (certchain.chain_attenuates.closure L) ((Bool × L)
  × L) (Bool × L) := {
  FnOnceInst :=
    certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnOncePairPairBoolLSharedLPairBoolL
    categoryLatticeInst
  call_mut :=
    certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnMutPairPairBoolLSharedLPairBoolL.call_mut
    categoryLatticeInst
}

/-- [portcullis_core::certchain::chain_attenuates]:
    Source: 'crates/portcullis-core/src/certchain.rs', lines 49:0-57:1
    Visibility: public -/
def certchain.chain_attenuates
  {L : Type} (categoryLatticeInst : category.Lattice L) (root : L)
  (effective : Slice L) :
  Result Bool
  := do
  let i ← core.slice.Slice.iter effective
  let t ← categoryLatticeInst.corecloneCloneInst.clone root
  let (b, _) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.fold
      (certchain.chain_attenuates.closure.Insts.CoreOpsFunctionFnMutPairPairBoolLSharedLPairBoolL
      categoryLatticeInst) i (true, t) ()
  ok b

end portcullis_core
