/-!
# CapabilityLevel as a Heyting Algebra

This file proves that `CapabilityLevel` — the 3-element total order
`Never < LowRisk < Always` mirroring the Rust enum in `portcullis` — is a
`HeytingAlgebra` in the sense of Mathlib's `Order.Heyting.Basic`.

## Model source

This is a **hand-written Lean 4 model**, not a file generated by the
Aeneas/Charon pipeline (Rust MIR → LLBC → Lean).  The type and its
`toNat` mapping were authored manually to match the Rust source.

Correspondence with the Rust enum is enforced by the unit test
`lean_tonat_matches_rust_discriminants` in
`portcullis/src/capability.rs`, which reads this file at compile time
via `include_str!` and asserts that the `toNat` values exactly match
the Rust `#[repr]` discriminants (`Never = 0`, `LowRisk = 1`,
`Always = 2`).  The CI build fails if they diverge.

An Aeneas-pipeline translation (Rust MIR → Lean) is planned for a
later phase but has not been started.

## Verification approach

Every proof in this file is **kernel-checked** by the Lean 4 type-checker.
No SMT oracle is involved; no Z3 queries are made. Propositions over the
3-element type are decided by the `decide` tactic, which the kernel evaluates
by finite enumeration of all cases (3, 9, or 27 cases depending on arity).

This contrasts with the Verus layer (`src/lib.rs`), which uses Z3 to discharge
verification conditions over an integer encoding of the same type.

## Correspondence with Kani R1/R2/R3 harnesses

The three named Kani harnesses in `portcullis/src/kani.rs` mirror the key
HeytingAlgebra axioms proven here:

- **R1** (`proof_r1_heyting_adjunction`): `a ≤ b ⇨ c ↔ a ⊓ b ≤ c`
  — the defining adjunction (`le_himp_iff`).
- **R2** (`proof_r2_pseudo_complement`): `a ⊓ ¬a = ⊥`
  — pseudo-complement (`inf_compl_le_bot`, derived from `himp_bot`).
- **R3** (`proof_r3_entailment`): `a ≤ b ↔ (a ⇨ b) = ⊤`
  — entailment equivalence (corollary of `le_himp_iff`).

## Build

```bash
cd crates/portcullis-verified/lean
lake build PortcullisVerified
```
-/

import Mathlib.Order.Heyting.Basic
import Mathlib.Data.Fintype.Basic

/-- The three permission levels, mirroring the Rust `CapabilityLevel` enum.

    Discriminants match the Rust repr: `Never = 0`, `LowRisk = 1`, `Always = 2`. -/
inductive CapabilityLevel : Type
  | never   : CapabilityLevel
  | lowRisk : CapabilityLevel
  | always  : CapabilityLevel
  deriving DecidableEq, Repr, Inhabited

namespace CapabilityLevel

/-- Encode as a natural number, matching the Rust discriminants. -/
def toNat : CapabilityLevel → Nat
  | .never   => 0
  | .lowRisk => 1
  | .always  => 2

/-- `toNat` is injective — distinct constructors have distinct codes. -/
theorem toNat_injective : Function.Injective toNat := by decide

/-- Decidable ≤ derived from the natural-number encoding. -/
instance instDecidableLE : DecidableRel (α := CapabilityLevel) (· ≤ ·) :=
  fun a b => inferInstanceAs (Decidable (a.toNat ≤ b.toNat))

/-- The canonical total order: `Never < LowRisk < Always`. -/
instance instLinearOrder : LinearOrder CapabilityLevel where
  le a b             := a.toNat ≤ b.toNat
  lt a b             := a.toNat < b.toNat
  le_refl a          := Nat.le_refl _
  le_trans _ _ _ hab hbc := Nat.le_trans hab hbc
  lt_iff_le_not_le a b   := Nat.lt_iff_le_not_le
  le_antisymm a b h1 h2  := toNat_injective (Nat.le_antisymm h1 h2)
  le_total a b       := Nat.le_total _ _
  decidableLE        := instDecidableLE
  decidableLT _ _    := inferInstance
  decidableEq        := inferInstance

/-- All elements are ≤ `Always`. -/
theorem le_always (a : CapabilityLevel) : a ≤ .always := by cases a <;> decide

/-- `Never` is ≤ every element. -/
theorem never_le (a : CapabilityLevel) : .never ≤ a := by cases a <;> decide

/-- Bottom element: `Never`. -/
instance instBot : Bot CapabilityLevel := ⟨.never⟩

/-- Top element: `Always`. -/
instance instTop : Top CapabilityLevel := ⟨.always⟩

instance instBoundedOrder : BoundedOrder CapabilityLevel where
  bot_le := never_le
  le_top := le_always

/-- The lattice structure is inherited from the linear order. -/
instance instLattice : Lattice CapabilityLevel := LinearOrder.toLattice

/-- Heyting implication: the right adjoint to meet in the chain.

    For a total order, `a ⇨ b = if a ≤ b then ⊤ else b`. -/
instance instHImp : HImp CapabilityLevel where
  himp a b := if a ≤ b then .always else b

/-- Pseudo-complement: `aᶜ = a ⇨ ⊥`. -/
instance instHasCompl : HasCompl CapabilityLevel where
  compl a := if a ≤ (⊥ : CapabilityLevel) then .always else .never

-- ---------------------------------------------------------------------------
-- Core HeytingAlgebra axiom: le_himp_iff
-- The defining adjunction: a ≤ b ⇨ c ↔ a ⊓ b ≤ c
-- ---------------------------------------------------------------------------

/-- **Adjunction** (R1): `a ≤ b ⇨ c ↔ a ⊓ b ≤ c`.

    This is the defining property of the Heyting implication and is verified
    by the Lean kernel via exhaustive case analysis over all 27 triples. -/
theorem le_himp_iff (a b c : CapabilityLevel) :
    a ≤ b ⇨ c ↔ a ⊓ b ≤ c := by
  cases a <;> cases b <;> cases c <;>
    simp only [HImp.himp, Inf.inf, instHImp, instLattice,
               LinearOrder.toLattice, instLinearOrder] <;>
    decide

-- ---------------------------------------------------------------------------
-- Pseudo-complement axiom: himp_bot
-- ---------------------------------------------------------------------------

/-- **himp_bot** (R2 foundation): `a ⇨ ⊥ = aᶜ`.

    For a 3-element chain:
    - `Never ⇨ Never = Always` (Never ≤ Never, so ⊤) and `¬Never = Always` ✓
    - `LowRisk ⇨ Never = Never` (LowRisk > Never) and `¬LowRisk = Never`  ✓
    - `Always ⇨ Never = Never` (Always > Never) and `¬Always = Never`    ✓ -/
theorem himp_bot (a : CapabilityLevel) :
    a ⇨ (⊥ : CapabilityLevel) = aᶜ := by
  cases a <;> decide

-- ---------------------------------------------------------------------------
-- Derived: pseudo-complement is a∧¬a = ⊥  (R2)
-- ---------------------------------------------------------------------------

/-- **Pseudo-complement** (R2): `a ⊓ aᶜ = ⊥`.

    Kernel-checked over all 3 values. -/
theorem inf_compl_eq_bot (a : CapabilityLevel) :
    a ⊓ aᶜ = ⊥ := by cases a <;> decide

-- ---------------------------------------------------------------------------
-- Derived: entailment equivalence  (R3)
-- ---------------------------------------------------------------------------

/-- **Entailment** (R3): `a ≤ b ↔ (a ⇨ b) = ⊤`.

    Kernel-checked over all 9 pairs. -/
theorem le_iff_himp_eq_top (a b : CapabilityLevel) :
    a ≤ b ↔ a ⇨ b = ⊤ := by cases a <;> cases b <;> decide

-- ---------------------------------------------------------------------------
-- HeytingAlgebra instance
-- ---------------------------------------------------------------------------

/-- `CapabilityLevel` is a `HeytingAlgebra`.

    All fields discharge via `decide` because the type is a 3-element
    `Fintype` with `DecidableEq` — the Lean 4 kernel enumerates all cases
    with no SMT oracle and no opaque Z3 discharge. -/
instance instGeneralizedHeytingAlgebra : GeneralizedHeytingAlgebra CapabilityLevel where
  le_top  := le_always
  le_himp_iff a b c := le_himp_iff a b c

instance instHeytingAlgebra : HeytingAlgebra CapabilityLevel where
  bot_le  := never_le
  himp_bot := himp_bot

-- ---------------------------------------------------------------------------
-- Sanity checks: spot-verify the implication table
-- ---------------------------------------------------------------------------

#check @instHeytingAlgebra  -- verifies the instance type-checks

example : (CapabilityLevel.lowRisk ⇨ CapabilityLevel.never : CapabilityLevel) =
          .never := by decide

example : (CapabilityLevel.never ⇨ CapabilityLevel.always : CapabilityLevel) =
          .always := by decide

example : (CapabilityLevel.always ⇨ CapabilityLevel.lowRisk : CapabilityLevel) =
          .lowRisk := by decide

end CapabilityLevel
