-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreCredential.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::credential::sinkrank]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 50:0-55:1
    Visibility: public -/
def extracted.credential.sinkrank
  (s : extracted.credential.CredSink) : Result Std.U8 := do
  match s with
  | extracted.credential.CredSink.Guest => ok 0#u8
  | extracted.credential.CredSink.ExternalService => ok 1#u8

/-- [nucleus_ifc_kernel::extracted::credential::sink_ceiling]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 63:0-68:1
    Visibility: public -/
def extracted.credential.sink_ceiling
  (s : extracted.credential.CredSink) :
  Result extracted.ifc_confidentiality.ConfLevel
  := do
  match s with
  | extracted.credential.CredSink.Guest =>
    ok extracted.ifc_confidentiality.ConfLevel.Public
  | extracted.credential.CredSink.ExternalService =>
    ok extracted.ifc_confidentiality.ConfLevel.Secret

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::crank]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 33:0-39:1
    Visibility: public -/
def extracted.ifc_confidentiality.crank
  (l : extracted.ifc_confidentiality.ConfLevel) : Result Std.U8 := do
  match l with
  | extracted.ifc_confidentiality.ConfLevel.Public => ok 0#u8
  | extracted.ifc_confidentiality.ConfLevel.Internal => ok 1#u8
  | extracted.ifc_confidentiality.ConfLevel.Secret => ok 2#u8

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::cflows_to]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 58:0-60:1
    Visibility: public -/
def extracted.ifc_confidentiality.cflows_to
  (a : extracted.ifc_confidentiality.ConfLevel)
  (ceiling : extracted.ifc_confidentiality.ConfLevel) :
  Result Bool
  := do
  let i ← extracted.ifc_confidentiality.crank a
  let i1 ← extracted.ifc_confidentiality.crank ceiling
  ok (i <= i1)

/-- [nucleus_ifc_kernel::extracted::credential::cred_may_deliver]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 77:0-79:1
    Visibility: public -/
def extracted.credential.cred_may_deliver
  (label : extracted.ifc_confidentiality.ConfLevel)
  (sink : extracted.credential.CredSink) :
  Result Bool
  := do
  let cl ← extracted.credential.sink_ceiling sink
  extracted.ifc_confidentiality.cflows_to label cl

/-- [nucleus_ifc_kernel::extracted::credential::credential_may_reach]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 86:0-88:1
    Visibility: public -/
def extracted.credential.credential_may_reach
  (sink : extracted.credential.CredSink) : Result Bool := do
  extracted.credential.cred_may_deliver
    extracted.ifc_confidentiality.ConfLevel.Secret sink

end nucleus_ifc_kernel
