-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::credential::CredSink]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 41:0-47:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.credential.CredSink where
| Guest : extracted.credential.CredSink
| ExternalService : extracted.credential.CredSink

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::ConfLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 21:0-28:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_confidentiality.ConfLevel where
| Public : extracted.ifc_confidentiality.ConfLevel
| Internal : extracted.ifc_confidentiality.ConfLevel
| Secret : extracted.ifc_confidentiality.ConfLevel

end nucleus_ifc_kernel
