//! Declarative provenance schema manifest (DPI spec section 12).
//!
//! A provenance schema declares how each output field should be derived:
//! deterministic fields MUST go through the WASM parser pipeline, while
//! AI-derived fields are honestly labeled. The schema itself is content-hashed
//! and included in the receipt chain, proving the methodology wasn't altered.
//!
//! ## Format
//!
//! Schemas are YAML files (`.provenance.yaml`) with this structure:
//!
//! ```yaml
//! schema_version: 1
//! description: "SEC 10-K financial extraction"
//! sources:
//!   sec_10k:
//!     url_template: "https://efts.sec.gov/...?q={ticker}"
//!     content_type: "application/json"
//! fields:
//!   revenue:
//!     source: sec_10k
//!     parser: jq
//!     expression: ".hits[0].revenue"
//!     derivation: deterministic
//!   business_summary:
//!     source: sec_10k
//!     derivation: ai_derived
//! ```

use std::collections::BTreeMap;

// ═══════════════════════════════════════════════════════════════════════════
// DerivationKind — how a field must be derived
// ═══════════════════════════════════════════════════════════════════════════

/// How a schema field must be derived.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
pub enum DerivationKind {
    /// Field MUST come from a registered deterministic parser — the model
    /// never touches the data. Enforced by the kernel.
    Deterministic,
    /// Field is generated by the model. Honestly labeled in output.
    AiDerived,
    /// Field is provided directly by the user (e.g., the ticker symbol).
    UserProvided,
}

// ═══════════════════════════════════════════════════════════════════════════
// SourceDeclaration — a named data source
// ═══════════════════════════════════════════════════════════════════════════

/// A named data source referenced by schema fields.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SourceDeclaration {
    /// URL template with `{param}` placeholders (e.g., `https://api.example.com/data?q={ticker}`).
    pub url_template: String,
    /// Expected MIME content type (e.g., `application/json`, `text/html`).
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub content_type: Option<String>,
}

// ═══════════════════════════════════════════════════════════════════════════
// FieldDeclaration — a single output field
// ═══════════════════════════════════════════════════════════════════════════

/// Declaration of a single output field in the provenance schema.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FieldDeclaration {
    /// Which named source this field draws from.
    pub source: String,
    /// How this field must be derived.
    pub derivation: DerivationKind,
    /// Parser ID from the ParserRegistry (required when `derivation == Deterministic`).
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub parser: Option<String>,
    /// Parser expression (e.g., jq filter, JSONPath, XPath).
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub expression: Option<String>,
}

// ═══════════════════════════════════════════════════════════════════════════
// ProvenanceSchema — the top-level manifest
// ═══════════════════════════════════════════════════════════════════════════

/// A declarative provenance schema that maps output fields to data sources
/// and derivation methods.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ProvenanceSchema {
    /// Schema format version (currently 1).
    pub schema_version: u32,
    /// Human-readable description of what this schema extracts.
    pub description: String,
    /// Named data sources.
    pub sources: BTreeMap<String, SourceDeclaration>,
    /// Output fields with their derivation declarations.
    pub fields: BTreeMap<String, FieldDeclaration>,
}

// ═══════════════════════════════════════════════════════════════════════════
// Validation
// ═══════════════════════════════════════════════════════════════════════════

/// Validation error for a provenance schema.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SchemaValidationError {
    /// A field references a source that doesn't exist.
    UnknownSource { field: String, source: String },
    /// A deterministic field is missing its parser declaration.
    MissingParser { field: String },
    /// A deterministic field is missing its expression.
    MissingExpression { field: String },
    /// Schema version is unsupported.
    UnsupportedVersion { version: u32 },
}

impl std::fmt::Display for SchemaValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownSource { field, source } => {
                write!(f, "field '{field}' references unknown source '{source}'")
            }
            Self::MissingParser { field } => {
                write!(
                    f,
                    "deterministic field '{field}' requires a parser declaration"
                )
            }
            Self::MissingExpression { field } => {
                write!(f, "deterministic field '{field}' requires an expression")
            }
            Self::UnsupportedVersion { version } => {
                write!(f, "unsupported schema version {version} (expected 1)")
            }
        }
    }
}

impl std::error::Error for SchemaValidationError {}

impl ProvenanceSchema {
    /// Validate the schema for internal consistency.
    ///
    /// Checks:
    /// 1. Schema version is supported (currently only 1)
    /// 2. Every field references a declared source
    /// 3. Deterministic fields have a parser and expression
    pub fn validate(&self) -> Result<(), Vec<SchemaValidationError>> {
        let mut errors = Vec::new();

        if self.schema_version != 1 {
            errors.push(SchemaValidationError::UnsupportedVersion {
                version: self.schema_version,
            });
        }

        for (name, field) in &self.fields {
            if !self.sources.contains_key(&field.source) {
                errors.push(SchemaValidationError::UnknownSource {
                    field: name.clone(),
                    source: field.source.clone(),
                });
            }

            if field.derivation == DerivationKind::Deterministic {
                if field.parser.is_none() {
                    errors.push(SchemaValidationError::MissingParser {
                        field: name.clone(),
                    });
                }
                if field.expression.is_none() {
                    errors.push(SchemaValidationError::MissingExpression {
                        field: name.clone(),
                    });
                }
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Compute the SHA-256 content hash of the schema in canonical form.
    ///
    /// The hash covers description, sources, and fields in sorted order,
    /// ensuring that the same logical schema always produces the same hash
    /// regardless of serialization format or key ordering.
    #[cfg(feature = "artifact")]
    pub fn content_hash(&self) -> [u8; 32] {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(self.schema_version.to_le_bytes());
        hasher.update(self.description.as_bytes());

        // Sources in sorted order (BTreeMap guarantees this).
        for (name, src) in &self.sources {
            hasher.update(name.as_bytes());
            hasher.update(src.url_template.as_bytes());
            if let Some(ref ct) = src.content_type {
                hasher.update(ct.as_bytes());
            }
        }

        // Fields in sorted order.
        for (name, field) in &self.fields {
            hasher.update(name.as_bytes());
            hasher.update(field.source.as_bytes());
            hasher.update([field.derivation as u8]);
            if let Some(ref p) = field.parser {
                hasher.update(p.as_bytes());
            }
            if let Some(ref e) = field.expression {
                hasher.update(e.as_bytes());
            }
        }

        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        hash
    }

    /// Count of deterministic fields in the schema.
    pub fn deterministic_field_count(&self) -> usize {
        self.fields
            .values()
            .filter(|f| f.derivation == DerivationKind::Deterministic)
            .count()
    }

    /// Count of AI-derived fields in the schema.
    pub fn ai_derived_field_count(&self) -> usize {
        self.fields
            .values()
            .filter(|f| f.derivation == DerivationKind::AiDerived)
            .count()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_schema() -> ProvenanceSchema {
        let mut sources = BTreeMap::new();
        sources.insert(
            "sec_10k".into(),
            SourceDeclaration {
                url_template: "https://efts.sec.gov/search?q={ticker}".into(),
                content_type: Some("application/json".into()),
            },
        );

        let mut fields = BTreeMap::new();
        fields.insert(
            "revenue".into(),
            FieldDeclaration {
                source: "sec_10k".into(),
                derivation: DerivationKind::Deterministic,
                parser: Some("jq".into()),
                expression: Some(".hits[0].revenue".into()),
            },
        );
        fields.insert(
            "business_summary".into(),
            FieldDeclaration {
                source: "sec_10k".into(),
                derivation: DerivationKind::AiDerived,
                parser: None,
                expression: None,
            },
        );

        ProvenanceSchema {
            schema_version: 1,
            description: "SEC 10-K financial extraction".into(),
            sources,
            fields,
        }
    }

    #[test]
    fn valid_schema_passes_validation() {
        let schema = sample_schema();
        assert!(schema.validate().is_ok());
    }

    #[test]
    fn unknown_source_rejected() {
        let mut schema = sample_schema();
        schema.fields.insert(
            "orphan".into(),
            FieldDeclaration {
                source: "nonexistent".into(),
                derivation: DerivationKind::Deterministic,
                parser: Some("jq".into()),
                expression: Some(".foo".into()),
            },
        );
        let errs = schema.validate().unwrap_err();
        assert!(
            errs.iter()
                .any(|e| matches!(e, SchemaValidationError::UnknownSource { .. }))
        );
    }

    #[test]
    fn deterministic_without_parser_rejected() {
        let mut schema = sample_schema();
        schema.fields.insert(
            "bad".into(),
            FieldDeclaration {
                source: "sec_10k".into(),
                derivation: DerivationKind::Deterministic,
                parser: None,
                expression: Some(".foo".into()),
            },
        );
        let errs = schema.validate().unwrap_err();
        assert!(
            errs.iter()
                .any(|e| matches!(e, SchemaValidationError::MissingParser { .. }))
        );
    }

    #[test]
    fn deterministic_without_expression_rejected() {
        let mut schema = sample_schema();
        schema.fields.insert(
            "bad".into(),
            FieldDeclaration {
                source: "sec_10k".into(),
                derivation: DerivationKind::Deterministic,
                parser: Some("jq".into()),
                expression: None,
            },
        );
        let errs = schema.validate().unwrap_err();
        assert!(
            errs.iter()
                .any(|e| matches!(e, SchemaValidationError::MissingExpression { .. }))
        );
    }

    #[test]
    fn ai_derived_without_parser_is_fine() {
        let schema = sample_schema();
        // business_summary is AiDerived with no parser — valid
        assert!(schema.validate().is_ok());
    }

    #[test]
    fn unsupported_version_rejected() {
        let mut schema = sample_schema();
        schema.schema_version = 99;
        let errs = schema.validate().unwrap_err();
        assert!(
            errs.iter()
                .any(|e| matches!(e, SchemaValidationError::UnsupportedVersion { version: 99 }))
        );
    }

    #[cfg(feature = "artifact")]
    #[test]
    fn content_hash_is_deterministic() {
        let s1 = sample_schema();
        let s2 = sample_schema();
        assert_eq!(s1.content_hash(), s2.content_hash());
    }

    #[cfg(feature = "artifact")]
    #[test]
    fn content_hash_changes_on_modification() {
        let original = sample_schema();
        let original_hash = original.content_hash();

        let mut modified = sample_schema();
        modified.description = "tampered".into();
        assert_ne!(modified.content_hash(), original_hash);
    }

    #[test]
    fn field_counts() {
        let schema = sample_schema();
        assert_eq!(schema.deterministic_field_count(), 1);
        assert_eq!(schema.ai_derived_field_count(), 1);
    }
}
