//! Content-addressed provenance nodes (#1000).
//!
//! A Merkle DAG for provenance: each node is identified by the SHA-256
//! of its (kind, payload, parent_ids). This makes the DAG self-verifying —
//! an auditor can recompute any node's hash and detect tampering.
//!
//! ## jj-like semantics
//!
//! Like jj's content-addressed changes, provenance nodes are globally unique.
//! Cross-session references work without ID collision. Partial DAG transfer
//! is possible: send just the nodes the auditor needs.

use crate::flow::NodeKind;

/// A content-addressed provenance node in the Merkle DAG.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvenanceNode {
    /// SHA-256 of (kind, payload, parent_ids) — the content address.
    pub id: [u8; 32],
    /// Parent node content addresses (causal ancestors).
    pub parents: Vec<[u8; 32]>,
    /// What kind of provenance step this represents.
    pub kind: ProvenanceNodeKind,
    /// Kind-specific payload (e.g., URL, parser ID, field name).
    pub payload: String,
    /// Unix timestamp.
    pub timestamp: u64,
}

/// The kind of provenance step.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProvenanceNodeKind {
    /// Session started, optionally linked to prior session.
    SessionStart,
    /// Schema loaded for provenance mode.
    SchemaLoad,
    /// Source data fetched from a URL.
    SourceFetch,
    /// Deterministic parser executed on source data.
    ParserExec,
    /// Parser output bound to a schema field (model excluded).
    DeterministicBind,
    /// AI-derived content generated by the model.
    AiDerivedOutput,
    /// Clearance granted — WitnessBundle assembled.
    Clearance,
    /// Flow graph observation (maps from NodeKind).
    FlowObservation(NodeKind),
}

impl ProvenanceNode {
    /// Compute the content-address hash from the node's data.
    ///
    /// The hash covers kind, payload, parents, and timestamp —
    /// changing any field changes the hash.
    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    pub fn compute_id(
        kind: &ProvenanceNodeKind,
        payload: &str,
        parents: &[[u8; 32]],
        timestamp: u64,
    ) -> [u8; 32] {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(format!("{kind:?}").as_bytes());
        hasher.update(payload.as_bytes());
        for parent in parents {
            hasher.update(parent);
        }
        hasher.update(timestamp.to_le_bytes());
        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        hash
    }

    /// Create a new content-addressed node.
    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    pub fn new(
        kind: ProvenanceNodeKind,
        payload: String,
        parents: Vec<[u8; 32]>,
        timestamp: u64,
    ) -> Self {
        let id = Self::compute_id(&kind, &payload, &parents, timestamp);
        Self {
            id,
            parents,
            kind,
            payload,
            timestamp,
        }
    }

    /// Verify that the node's ID matches its content.
    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    pub fn verify_integrity(&self) -> bool {
        let expected = Self::compute_id(&self.kind, &self.payload, &self.parents, self.timestamp);
        self.id == expected
    }
}

/// A collection of content-addressed provenance nodes forming a Merkle DAG.
#[derive(Debug, Clone, Default)]
pub struct ProvenanceDAG {
    nodes: Vec<ProvenanceNode>,
}

impl ProvenanceDAG {
    /// Create an empty DAG.
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert a node. Returns the content-address hash.
    pub fn insert(&mut self, node: ProvenanceNode) -> [u8; 32] {
        let id = node.id;
        // Dedup: if a node with this ID already exists, skip.
        if !self.nodes.iter().any(|n| n.id == id) {
            self.nodes.push(node);
        }
        id
    }

    /// Look up a node by its content address.
    pub fn get(&self, id: &[u8; 32]) -> Option<&ProvenanceNode> {
        self.nodes.iter().find(|n| &n.id == id)
    }

    /// Number of nodes in the DAG.
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether the DAG is empty.
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// All nodes in insertion order.
    pub fn nodes(&self) -> &[ProvenanceNode] {
        &self.nodes
    }

    /// Verify integrity of all nodes in the DAG.
    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    pub fn verify_all(&self) -> bool {
        self.nodes.iter().all(|n| n.verify_integrity())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    #[test]
    fn content_addressed_node() {
        let node = ProvenanceNode::new(
            ProvenanceNodeKind::SourceFetch,
            "https://example.com".into(),
            vec![],
            1000,
        );
        assert!(node.verify_integrity());
        assert_ne!(node.id, [0u8; 32]);
    }

    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    #[test]
    fn different_payload_different_id() {
        let a = ProvenanceNode::new(
            ProvenanceNodeKind::SourceFetch,
            "url_a".into(),
            vec![],
            1000,
        );
        let b = ProvenanceNode::new(
            ProvenanceNodeKind::SourceFetch,
            "url_b".into(),
            vec![],
            1000,
        );
        assert_ne!(a.id, b.id);
    }

    #[cfg(any(feature = "artifact", feature = "wasm-sandbox"))]
    #[test]
    fn parent_changes_id() {
        let parent = [0xAA; 32];
        let with_parent = ProvenanceNode::new(
            ProvenanceNodeKind::ParserExec,
            "jq".into(),
            vec![parent],
            1000,
        );
        let without_parent =
            ProvenanceNode::new(ProvenanceNodeKind::ParserExec, "jq".into(), vec![], 1000);
        assert_ne!(with_parent.id, without_parent.id);
    }

    #[test]
    fn dag_dedup() {
        let mut dag = ProvenanceDAG::new();
        let node = ProvenanceNode {
            id: [0xAA; 32],
            parents: vec![],
            kind: ProvenanceNodeKind::SessionStart,
            payload: String::new(),
            timestamp: 1000,
        };
        dag.insert(node.clone());
        dag.insert(node); // duplicate
        assert_eq!(dag.len(), 1);
    }

    #[test]
    fn dag_lookup() {
        let mut dag = ProvenanceDAG::new();
        let id = [0xBB; 32];
        dag.insert(ProvenanceNode {
            id,
            parents: vec![],
            kind: ProvenanceNodeKind::Clearance,
            payload: "wtn_123".into(),
            timestamp: 2000,
        });
        assert!(dag.get(&id).is_some());
        assert!(dag.get(&[0xCC; 32]).is_none());
    }
}
