//! zkVM receipt types for verifiable parser execution (#1115).
//!
//! A [`ZkvmReceipt`] proves that a specific WASM parser produced a specific
//! output from a specific input — cryptographically, not just via hash chain.
//! The receipt is generated by RISC Zero's zkVM and can be verified by any
//! party without re-executing the parser.
//!
//! ## Relationship to existing types
//!
//! - [`crate::witness::WitnessBundle`] records hash-chain provenance (trust-based)
//! - `ZkvmReceipt` provides cryptographic proof of execution (trustless)
//! - A `WitnessBundle` can optionally carry a `ZkvmReceipt` for stronger guarantees

use sha2::{Digest, Sha256};

/// Hex-encode a byte slice (avoids hex crate dependency).
fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// A cryptographic receipt proving parser execution in the zkVM.
///
/// The receipt attests: "parser with hash `parser_hash` was executed on
/// input with hash `input_hash` and produced output with hash `output_hash`."
/// This is verifiable by any party without access to the input data or parser.
#[derive(Debug, Clone)]
pub struct ZkvmReceipt {
    /// SHA-256 hash of the WASM parser binary.
    pub parser_hash: [u8; 32],
    /// SHA-256 hash of the input data fed to the parser.
    pub input_hash: [u8; 32],
    /// SHA-256 hash of the parser's output.
    pub output_hash: [u8; 32],
    /// The RISC Zero receipt bytes (serialized `risc0_zkvm::Receipt`).
    /// This is the cryptographic proof — verifiers check this.
    pub receipt_bytes: Vec<u8>,
    /// The image ID of the zkVM guest program that produced this receipt.
    /// Used to verify the receipt was generated by the correct guest.
    pub image_id: [u32; 8],
}

/// Error from zkVM receipt operations.
#[derive(Debug)]
pub enum ZkvmReceiptError {
    /// Receipt verification failed.
    VerificationFailed(String),
    /// Hash mismatch between receipt journal and expected values.
    HashMismatch {
        field: &'static str,
        expected: [u8; 32],
        actual: [u8; 32],
    },
    /// Deserialization error.
    Deserialize(String),
}

impl core::fmt::Display for ZkvmReceiptError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::VerificationFailed(msg) => write!(f, "zkVM verification failed: {msg}"),
            Self::HashMismatch {
                field,
                expected,
                actual,
            } => write!(
                f,
                "hash mismatch on {field}: expected {}, got {}",
                hex_encode(expected),
                hex_encode(actual)
            ),
            Self::Deserialize(msg) => write!(f, "zkVM deserialize error: {msg}"),
        }
    }
}

impl std::error::Error for ZkvmReceiptError {}

impl ZkvmReceipt {
    /// Create a new receipt from its components.
    pub fn new(
        parser_hash: [u8; 32],
        input_hash: [u8; 32],
        output_hash: [u8; 32],
        receipt_bytes: Vec<u8>,
        image_id: [u32; 8],
    ) -> Self {
        Self {
            parser_hash,
            input_hash,
            output_hash,
            receipt_bytes,
            image_id,
        }
    }

    /// Compute a content hash over all receipt fields (for inclusion in witness bundles).
    pub fn content_hash(&self) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(self.parser_hash);
        hasher.update(self.input_hash);
        hasher.update(self.output_hash);
        hasher.update(&self.receipt_bytes);
        for word in &self.image_id {
            hasher.update(word.to_le_bytes());
        }
        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        hash
    }

    /// Check if this receipt's hashes match expected values.
    pub fn verify_hashes(
        &self,
        expected_parser: &[u8; 32],
        expected_input: &[u8; 32],
        expected_output: &[u8; 32],
    ) -> Result<(), ZkvmReceiptError> {
        if self.parser_hash != *expected_parser {
            return Err(ZkvmReceiptError::HashMismatch {
                field: "parser_hash",
                expected: *expected_parser,
                actual: self.parser_hash,
            });
        }
        if self.input_hash != *expected_input {
            return Err(ZkvmReceiptError::HashMismatch {
                field: "input_hash",
                expected: *expected_input,
                actual: self.input_hash,
            });
        }
        if self.output_hash != *expected_output {
            return Err(ZkvmReceiptError::HashMismatch {
                field: "output_hash",
                expected: *expected_output,
                actual: self.output_hash,
            });
        }
        Ok(())
    }

    /// Returns true if the receipt has non-empty proof bytes.
    pub fn has_proof(&self) -> bool {
        !self.receipt_bytes.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sha256(data: &[u8]) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(data);
        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        hash
    }

    #[test]
    fn receipt_creation() {
        let r = ZkvmReceipt::new(
            sha256(b"parser.wasm"),
            sha256(b"input data"),
            sha256(b"output data"),
            vec![0xDE, 0xAD],
            [1, 2, 3, 4, 5, 6, 7, 8],
        );
        assert!(r.has_proof());
        assert_eq!(r.image_id[0], 1);
    }

    #[test]
    fn content_hash_deterministic() {
        let r1 = ZkvmReceipt::new([1u8; 32], [2u8; 32], [3u8; 32], vec![4], [0; 8]);
        let r2 = ZkvmReceipt::new([1u8; 32], [2u8; 32], [3u8; 32], vec![4], [0; 8]);
        assert_eq!(r1.content_hash(), r2.content_hash());
    }

    #[test]
    fn content_hash_changes_with_input() {
        let r1 = ZkvmReceipt::new([1u8; 32], [2u8; 32], [3u8; 32], vec![4], [0; 8]);
        let r2 = ZkvmReceipt::new([1u8; 32], [9u8; 32], [3u8; 32], vec![4], [0; 8]);
        assert_ne!(r1.content_hash(), r2.content_hash());
    }

    #[test]
    fn verify_hashes_pass() {
        let ph = sha256(b"parser");
        let ih = sha256(b"input");
        let oh = sha256(b"output");
        let r = ZkvmReceipt::new(ph, ih, oh, vec![], [0; 8]);
        assert!(r.verify_hashes(&ph, &ih, &oh).is_ok());
    }

    #[test]
    fn verify_hashes_mismatch() {
        let ph = sha256(b"parser");
        let ih = sha256(b"input");
        let oh = sha256(b"output");
        let r = ZkvmReceipt::new(ph, ih, oh, vec![], [0; 8]);
        let wrong = sha256(b"wrong");
        let err = r.verify_hashes(&wrong, &ih, &oh).unwrap_err();
        assert!(err.to_string().contains("parser_hash"));
    }

    #[test]
    fn empty_receipt_has_no_proof() {
        let r = ZkvmReceipt::new([0; 32], [0; 32], [0; 32], vec![], [0; 8]);
        assert!(!r.has_proof());
    }
}
