-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreCapQuantale.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::capability_quantale::caprank]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 34:0-40:1
    Visibility: public -/
def extracted.capability_quantale.caprank
  (l : extracted.capability_quantale.CapLevel) : Result Std.U8 := do
  match l with
  | extracted.capability_quantale.CapLevel.Never => ok 0#u8
  | extracted.capability_quantale.CapLevel.LowRisk => ok 1#u8
  | extracted.capability_quantale.CapLevel.Always => ok 2#u8

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capunit]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 43:0-45:1
    Visibility: public -/
def extracted.capability_quantale.capunit
  : Result extracted.capability_quantale.CapLevel := do
  ok extracted.capability_quantale.CapLevel.Always

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capbot]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 48:0-50:1
    Visibility: public -/
def extracted.capability_quantale.capbot
  : Result extracted.capability_quantale.CapLevel := do
  ok extracted.capability_quantale.CapLevel.Never

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capmeet]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 54:0-60:1
    Visibility: public -/
def extracted.capability_quantale.capmeet
  (a : extracted.capability_quantale.CapLevel)
  (b : extracted.capability_quantale.CapLevel) :
  Result extracted.capability_quantale.CapLevel
  := do
  let i ← extracted.capability_quantale.caprank a
  let i1 ← extracted.capability_quantale.caprank b
  if i <= i1
  then ok a
  else ok b

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capjoin]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 63:0-69:1
    Visibility: public -/
def extracted.capability_quantale.capjoin
  (a : extracted.capability_quantale.CapLevel)
  (b : extracted.capability_quantale.CapLevel) :
  Result extracted.capability_quantale.CapLevel
  := do
  let i ← extracted.capability_quantale.caprank a
  let i1 ← extracted.capability_quantale.caprank b
  if i >= i1
  then ok a
  else ok b

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capleq]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 73:0-75:1
    Visibility: public -/
def extracted.capability_quantale.capleq
  (a : extracted.capability_quantale.CapLevel)
  (b : extracted.capability_quantale.CapLevel) :
  Result Bool
  := do
  let i ← extracted.capability_quantale.caprank a
  let i1 ← extracted.capability_quantale.caprank b
  ok (i <= i1)

/-- [nucleus_ifc_kernel::extracted::capability_quantale::capresidual]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 80:0-86:1
    Visibility: public -/
def extracted.capability_quantale.capresidual
  (a : extracted.capability_quantale.CapLevel)
  (c : extracted.capability_quantale.CapLevel) :
  Result extracted.capability_quantale.CapLevel
  := do
  let b ← extracted.capability_quantale.capleq a c
  if b
  then ok extracted.capability_quantale.CapLevel.Always
  else ok c

end nucleus_ifc_kernel
