-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::capability_quantale::CapLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 23:0-30:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.capability_quantale.CapLevel where
| Never : extracted.capability_quantale.CapLevel
| LowRisk : extracted.capability_quantale.CapLevel
| Always : extracted.capability_quantale.CapLevel

end nucleus_ifc_kernel
