//! [SLSA Provenance v1.1][slsa] predicate adapter.
//!
//! Maps a nucleus [`Bundle`] to a SLSA Provenance predicate, then
//! wraps it in the [in-toto Statement](super::in_toto::Statement)
//! shape and signs via DSSE. The result drops into `slsa-verifier`,
//! `cosign verify-attestation`, and any other SLSA-aware pipeline
//! without further translation.
//!
//! [slsa]: https://slsa.dev/spec/v1.1/provenance
//!
//! # SLSA build level claim
//!
//! Nucleus claims **SLSA Build L2** by default for sessions executed
//! inside the standard control-plane pipeline:
//!
//! - Provenance is generated by a trusted build platform (the nucleus
//!   control plane, signed under its SPIFFE identity) — satisfies L2
//!   `Provenance generated`.
//! - Provenance is signed by the build platform — satisfies L2
//!   `Hosted`.
//!
//! **L3 (`Hardened builds`)** requires hermetic + isolated execution.
//! Firecracker-microVM-backed sessions satisfy these structurally
//! (see [`NORTH_STAR.md`](../../../NORTH_STAR.md)), but claiming L3
//! requires an audited mapping from the nucleus runtime config to
//! the SLSA hardening checklist — flagged as roadmap work, not
//! claimed in this adapter.

use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use nucleus_lineage::{EdgeKind, EdgeSigner};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::Digest;

use crate::bundle::Bundle;
use crate::interop::in_toto::{
    DsseEnvelope, InTotoError, ResourceDescriptor, Statement, IN_TOTO_STATEMENT_TYPE,
    NUCLEUS_SUBJECT_NAME,
};

/// SLSA Provenance v1 predicate type URI.
pub const SLSA_PROVENANCE_V1_PREDICATE_TYPE: &str = "https://slsa.dev/provenance/v1";

/// Nucleus build type. Identifies the schema of `externalParameters`
/// and `resolvedDependencies` so SLSA verifiers can dispatch
/// nucleus-specific checks.
pub const NUCLEUS_BUILD_TYPE: &str = "https://nucleus.coproduct.io/agent-build/v1";

/// SLSA Provenance v1.1 predicate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Provenance {
    /// Description of how the build was invoked.
    #[serde(rename = "buildDefinition")]
    pub build_definition: BuildDefinition,
    /// Description of the build execution.
    #[serde(rename = "runDetails")]
    pub run_details: RunDetails,
}

/// SLSA Provenance buildDefinition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildDefinition {
    /// TypeURI identifying the schema of externalParameters and
    /// resolvedDependencies.
    #[serde(rename = "buildType")]
    pub build_type: String,
    /// Inputs that were specified by the build invocation.
    #[serde(rename = "externalParameters")]
    pub external_parameters: Value,
    /// Inputs known only to the build platform (omitted by default —
    /// no provenance-irrelevant internals to leak).
    #[serde(
        rename = "internalParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub internal_parameters: Option<Value>,
    /// Set of dependencies the build platform resolved on the
    /// builder's behalf. For nucleus this is the set of inputs the
    /// agent read during the session.
    #[serde(
        rename = "resolvedDependencies",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub resolved_dependencies: Vec<ResourceDescriptor>,
}

/// SLSA Provenance runDetails.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunDetails {
    pub builder: Builder,
    pub metadata: Metadata,
    /// Optional byproducts of the build (logs, debug artifacts).
    /// Empty in v1 of this adapter; reserved for future use.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub byproducts: Vec<ResourceDescriptor>,
}

/// SLSA Provenance builder reference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Builder {
    /// URI identifying the build platform that ran this session.
    pub id: String,
    /// Optional version info (commit hash, semver, …).
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub version: Value,
    /// Other tooling involved in the build (not the build platform
    /// itself). Empty in v1.
    #[serde(
        rename = "builderDependencies",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub builder_dependencies: Vec<ResourceDescriptor>,
}

/// SLSA Provenance run metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Metadata {
    /// Identifier for this particular build invocation. Nucleus uses
    /// the session root SPIFFE URI.
    #[serde(rename = "invocationId")]
    pub invocation_id: String,
    /// When the build started — first edge's timestamp.
    #[serde(rename = "startedOn", default, skip_serializing_if = "Option::is_none")]
    pub started_on: Option<DateTime<Utc>>,
    /// When the build finished — last edge's timestamp.
    #[serde(
        rename = "finishedOn",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub finished_on: Option<DateTime<Utc>>,
}

impl Bundle {
    /// Compute the [`Builder::id`] URI from the session root's trust
    /// domain. Convention: the control plane's SPIFFE identity in the
    /// same trust domain. Verifiers can pin to this exact value or
    /// allow any URI under the trust domain.
    fn slsa_builder_id(&self) -> String {
        // session_root is e.g. spiffe://<td>/ns/<ns>/sa/<sa>
        let s = self.envelope.session_root.as_str();
        if let Some(rest) = s.strip_prefix("spiffe://") {
            let td = rest.split('/').next().unwrap_or("unknown.local");
            format!("spiffe://{td}/nucleus-control-plane")
        } else {
            "spiffe://unknown.local/nucleus-control-plane".to_string()
        }
    }

    /// Build a SLSA Provenance v1.1 predicate from this bundle.
    pub fn to_slsa_provenance(&self) -> Provenance {
        let session_root_str = self.envelope.session_root.to_string();

        // `resolvedDependencies` ← `EdgeKind::ToolCall` edges whose
        // tool name describes a read (Read, HttpGet, …). The edge
        // child URI carries `sha256:<hex>` of the input content per
        // the lineage spec; we surface that as the digest.
        let resolved_dependencies = self
            .envelope
            .edges
            .iter()
            .filter_map(|edge| match &edge.kind {
                EdgeKind::ToolCall { tool } => {
                    let uri = edge.child.as_str().to_string();
                    let digest = sha256_digest_from_spiffe_uri(&uri);
                    let mut map = BTreeMap::new();
                    if let Some(d) = digest {
                        map.insert("sha256".to_string(), d);
                    }
                    Some(ResourceDescriptor {
                        name: tool.clone(),
                        digest: map,
                    })
                }
                _ => None,
            })
            .collect();

        let started_on = self.envelope.edges.first().map(|e| e.ts);
        let finished_on = self.envelope.edges.last().map(|e| e.ts);

        Provenance {
            build_definition: BuildDefinition {
                build_type: NUCLEUS_BUILD_TYPE.to_string(),
                external_parameters: serde_json::json!({
                    "sessionRoot": session_root_str.clone(),
                }),
                internal_parameters: None,
                resolved_dependencies,
            },
            run_details: RunDetails {
                builder: Builder {
                    id: self.slsa_builder_id(),
                    version: Value::Null,
                    builder_dependencies: Vec::new(),
                },
                metadata: Metadata {
                    invocation_id: session_root_str,
                    started_on,
                    finished_on,
                },
                byproducts: Vec::new(),
            },
        }
    }

    /// Build an in-toto Statement carrying the SLSA Provenance as
    /// its predicate.
    pub fn to_slsa_statement(&self) -> Result<Statement, InTotoError> {
        let payload_bytes = serde_json::to_vec(&self.payload)?;
        let payload_hash = sha2::Sha256::digest(&payload_bytes);
        let mut digest = BTreeMap::new();
        digest.insert("sha256".to_string(), hex::encode(payload_hash));
        let subject = ResourceDescriptor {
            name: NUCLEUS_SUBJECT_NAME.to_string(),
            digest,
        };
        let provenance = self.to_slsa_provenance();
        Ok(Statement {
            statement_type: IN_TOTO_STATEMENT_TYPE.to_string(),
            subject: vec![subject],
            predicate_type: SLSA_PROVENANCE_V1_PREDICATE_TYPE.to_string(),
            predicate: serde_json::to_value(&provenance)?,
        })
    }

    /// Build a DSSE-signed SLSA Provenance attestation. Reuses the
    /// PAE + DSSE machinery from [`super::in_toto`]; verifiable by
    /// any in-toto-aware tool.
    pub fn to_slsa_dsse(&self, signer: &dyn EdgeSigner) -> Result<DsseEnvelope, InTotoError> {
        let statement = self.to_slsa_statement()?;
        let statement_bytes = serde_json::to_vec(&statement)?;
        let pae = crate::binding::pae_bytes(
            super::in_toto::DSSE_INTOTO_PAYLOAD_TYPE,
            &[&statement_bytes],
        );
        let signature = signer.sign(&pae)?;
        use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
        Ok(DsseEnvelope {
            payload_type: super::in_toto::DSSE_INTOTO_PAYLOAD_TYPE.to_string(),
            payload: B64.encode(&statement_bytes),
            signatures: vec![super::in_toto::DsseSignature {
                keyid: signer.kid().to_string(),
                sig: B64.encode(&signature),
            }],
        })
    }
}

/// Extract a `sha256:<hex>` suffix from a SPIFFE URI of the shape
/// `spiffe://<td>/.../<tool>/sha256:<hex>`. Returns just the hex.
fn sha256_digest_from_spiffe_uri(uri: &str) -> Option<String> {
    uri.rsplit('/')
        .next()
        .and_then(|tail| tail.strip_prefix("sha256:").map(|hex| hex.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bundle::BundleBuilder;
    use ed25519_dalek::{Signer as Ed25519Signer, SigningKey, SECRET_KEY_LENGTH};
    use nucleus_lineage::{
        CallSpiffeId, EdgeKind, InMemorySink, IssuerError, Jwks, LineageEdge, LineageSink,
    };

    struct TestSigner {
        key: SigningKey,
        kid: String,
    }

    impl TestSigner {
        fn new() -> Self {
            Self {
                key: SigningKey::from_bytes(&[9u8; SECRET_KEY_LENGTH]),
                kid: "slsa-test-key".to_string(),
            }
        }
    }

    impl EdgeSigner for TestSigner {
        fn sign(&self, message: &[u8]) -> Result<Vec<u8>, IssuerError> {
            Ok(self.key.sign(message).to_bytes().to_vec())
        }
        fn kid(&self) -> &str {
            &self.kid
        }
        fn alg(&self) -> &str {
            "EdDSA"
        }
    }

    fn fixture_bundle() -> Bundle {
        let sink = InMemorySink::new();
        let pod = CallSpiffeId::pod("prod.example.com", "agents", "summarizer").unwrap();
        sink.emit(LineageEdge::pod_admit(pod.clone())).unwrap();
        sink.emit(LineageEdge::from_parent(
            pod.derive_tool("Read", Some(b"input-A")).unwrap(),
            pod.clone(),
            EdgeKind::ToolCall {
                tool: "Read".to_string(),
            },
        ))
        .unwrap();
        sink.emit(LineageEdge::from_parent(
            pod.derive_tool("Read", Some(b"input-B")).unwrap(),
            pod.clone(),
            EdgeKind::ToolCall {
                tool: "Read".to_string(),
            },
        ))
        .unwrap();
        BundleBuilder::new(pod)
            .payload(serde_json::json!({"summary": "hi"}))
            .sink(&sink)
            .jwks(Jwks { keys: vec![] })
            .build()
            .unwrap()
    }

    #[test]
    fn provenance_carries_nucleus_build_type() {
        let prov = fixture_bundle().to_slsa_provenance();
        assert_eq!(
            prov.build_definition.build_type,
            "https://nucleus.coproduct.io/agent-build/v1"
        );
    }

    #[test]
    fn provenance_external_parameters_have_session_root() {
        let bundle = fixture_bundle();
        let prov = bundle.to_slsa_provenance();
        let session_root = prov.build_definition.external_parameters["sessionRoot"]
            .as_str()
            .unwrap()
            .to_string();
        assert_eq!(session_root, bundle.envelope.session_root.to_string());
    }

    #[test]
    fn provenance_resolves_dependencies_from_tool_call_edges() {
        let prov = fixture_bundle().to_slsa_provenance();
        // Two `Read` edges → two resolved dependencies.
        assert_eq!(prov.build_definition.resolved_dependencies.len(), 2);
        for dep in &prov.build_definition.resolved_dependencies {
            assert_eq!(dep.name, "Read");
            // Each carries a SHA-256 digest extracted from the SPIFFE URI.
            assert!(dep.digest.contains_key("sha256"));
            let hex = dep.digest.get("sha256").unwrap();
            assert_eq!(hex.len(), 64, "SHA-256 hex must be 64 chars");
        }
        // Distinct inputs → distinct digests.
        let d0 = &prov.build_definition.resolved_dependencies[0].digest["sha256"];
        let d1 = &prov.build_definition.resolved_dependencies[1].digest["sha256"];
        assert_ne!(d0, d1);
    }

    #[test]
    fn provenance_builder_id_is_derived_from_trust_domain() {
        let prov = fixture_bundle().to_slsa_provenance();
        // Session is in `prod.example.com` → builder is the control
        // plane in the same trust domain.
        assert_eq!(
            prov.run_details.builder.id,
            "spiffe://prod.example.com/nucleus-control-plane"
        );
    }

    #[test]
    fn provenance_metadata_has_invocation_id() {
        let bundle = fixture_bundle();
        let prov = bundle.to_slsa_provenance();
        assert_eq!(
            prov.run_details.metadata.invocation_id,
            bundle.envelope.session_root.to_string()
        );
    }

    #[test]
    fn provenance_metadata_started_and_finished_match_edges() {
        let bundle = fixture_bundle();
        let prov = bundle.to_slsa_provenance();
        assert_eq!(
            prov.run_details.metadata.started_on,
            Some(bundle.envelope.edges.first().unwrap().ts)
        );
        assert_eq!(
            prov.run_details.metadata.finished_on,
            Some(bundle.envelope.edges.last().unwrap().ts)
        );
    }

    #[test]
    fn slsa_statement_has_correct_predicate_type() {
        let stmt = fixture_bundle().to_slsa_statement().unwrap();
        assert_eq!(stmt.predicate_type, "https://slsa.dev/provenance/v1");
        assert_eq!(stmt.statement_type, "https://in-toto.io/Statement/v1");
    }

    #[test]
    fn slsa_dsse_signature_verifies() {
        use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
        let signer = TestSigner::new();
        let env = fixture_bundle().to_slsa_dsse(&signer).unwrap();
        let payload_bytes = B64.decode(&env.payload).unwrap();
        let pae = crate::binding::pae_bytes(
            super::super::in_toto::DSSE_INTOTO_PAYLOAD_TYPE,
            &[&payload_bytes],
        );
        let sig_bytes = B64.decode(&env.signatures[0].sig).unwrap();
        let sig_array: [u8; 64] = sig_bytes.as_slice().try_into().unwrap();
        let signature = ed25519_dalek::Signature::from_bytes(&sig_array);
        let vk = signer.key.verifying_key();
        ed25519_dalek::Verifier::verify(&vk, &pae, &signature)
            .expect("SLSA DSSE signature must verify against PAE(payloadType, payload)");
    }

    #[test]
    fn slsa_provenance_round_trips_through_json() {
        let prov = fixture_bundle().to_slsa_provenance();
        let json = serde_json::to_string(&prov).unwrap();
        let back: Provenance = serde_json::from_str(&json).unwrap();
        assert_eq!(
            back.build_definition.build_type,
            prov.build_definition.build_type
        );
        assert_eq!(
            back.build_definition.resolved_dependencies.len(),
            prov.build_definition.resolved_dependencies.len()
        );
    }

    #[test]
    fn sha256_digest_extractor_handles_well_formed_uri() {
        let uri = "spiffe://td/ns/x/sa/y/call/c/tool/Read/sha256:abcd1234";
        assert_eq!(
            sha256_digest_from_spiffe_uri(uri),
            Some("abcd1234".to_string())
        );
    }

    #[test]
    fn sha256_digest_extractor_handles_missing_suffix() {
        let uri = "spiffe://td/ns/x/sa/y";
        assert_eq!(sha256_digest_from_spiffe_uri(uri), None);
    }
}
