//! Golden traces: one JSON file, two consumers.
//!
//! `crates/ci-spec/tests/golden/queue_traces.json` is replayed by the Rust
//! mirror (`tests/golden.rs`) and rendered by [`render_lean`] into
//! `ci/lean/CiSpec/Golden.lean` as `example … := by decide` lines, which
//! the Lean kernel checks against `CiSpec.Queue` / `CiSpec.Capacity`. CI
//! regenerates the Lean file and diffs it (the `econ-lean.yml` golden-seal
//! pattern), so the two implementations cannot drift on a pinned vector
//! without a red.

use serde::Deserialize;

use crate::queue::{Ev, Loc, State, greedy_from, makespan, run};

#[derive(Debug, Deserialize)]
pub struct GoldenFile {
    pub traces: Vec<Trace>,
    pub capacity: Vec<CapacityVector>,
}

#[derive(Debug, Deserialize)]
pub struct Trace {
    pub name: String,
    pub events: Vec<String>,
    pub expect: Expect,
}

#[derive(Debug, Deserialize)]
pub struct Expect {
    pub queue: Vec<u32>,
    pub merged_log: Vec<u32>,
    pub enq_log: Vec<u32>,
    pub loc: std::collections::BTreeMap<String, Loc>,
}

#[derive(Debug, Deserialize)]
pub struct CapacityVector {
    pub name: String,
    pub runners: usize,
    pub initial: Vec<u64>,
    pub jobs: Vec<u64>,
    pub makespan: u64,
}

pub fn parse(json: &str) -> Result<GoldenFile, String> {
    serde_json::from_str(json).map_err(|e| format!("golden JSON: {e}"))
}

fn events_of(t: &Trace) -> Result<Vec<Ev>, String> {
    t.events
        .iter()
        .map(|s| Ev::parse(s).ok_or_else(|| format!("{}: bad event {s:?}", t.name)))
        .collect()
}

/// Replay every trace in Rust; the first mismatch, if any.
pub fn check_rust(g: &GoldenFile) -> Result<usize, String> {
    let mut n = 0;
    for t in &g.traces {
        let evs = events_of(t)?;
        let s = run(State::init(), &evs);
        if s.queue != t.expect.queue {
            return Err(format!("{}: queue {:?} ≠ {:?}", t.name, s.queue, t.expect.queue));
        }
        if s.merged_log != t.expect.merged_log {
            return Err(format!("{}: merged_log {:?} ≠ {:?}", t.name, s.merged_log, t.expect.merged_log));
        }
        if s.enq_log != t.expect.enq_log {
            return Err(format!("{}: enq_log {:?} ≠ {:?}", t.name, s.enq_log, t.expect.enq_log));
        }
        for (p, l) in &t.expect.loc {
            let p: u32 = p.parse().map_err(|_| format!("{}: bad pr {p:?}", t.name))?;
            if s.loc(p) != *l {
                return Err(format!("{}: loc {p} = {:?} ≠ {:?}", t.name, s.loc(p), l));
            }
        }
        n += 1;
    }
    for c in &g.capacity {
        if c.initial.len() != c.runners {
            return Err(format!("{}: {} initial loads for {} runners", c.name, c.initial.len(), c.runners));
        }
        let got = makespan(&greedy_from(&c.initial, &c.jobs));
        if got != c.makespan {
            return Err(format!("{}: makespan {got} ≠ {}", c.name, c.makespan));
        }
        n += 1;
    }
    Ok(n)
}

fn lean_list<T: std::fmt::Display>(v: &[T]) -> String {
    let items: Vec<String> = v.iter().map(ToString::to_string).collect();
    format!("[{}]", items.join(", "))
}

fn lean_loc(l: Loc) -> &'static str {
    match l {
        Loc::Waiting => ".waiting",
        Loc::Queued => ".queued",
        Loc::Merged => ".merged",
        Loc::Ejected => ".ejected",
    }
}

/// Render the golden file as `ci/lean/CiSpec/Golden.lean`.
pub fn render_lean(g: &GoldenFile) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "/-\n  CiSpec / Golden — GENERATED by `cargo xtask ci-spec gen-golden` from\n  \
         crates/ci-spec/tests/golden/queue_traces.json. Do not edit; edit the JSON\n  \
         and regenerate. CI regenerates and diffs this file (the econ-lean golden\n  \
         seal pattern), so the Rust mirror in crates/ci-spec/src/queue.rs and the\n  \
         Lean model cannot drift on a pinned vector without a red.\n\n  \
         Every `example` is closed by `decide`: the kernel evaluates the Lean\n  \
         transition function on the same events the Rust test replays.\n-/\n\n\
         import CiSpec.Queue\nimport CiSpec.Capacity\n\nnamespace CiSpec.Golden\n\nopen CiSpec\n\n",
    );
    for t in &g.traces {
        let evs = events_of(t)?;
        let lean_evs: Vec<String> = evs.iter().map(Ev::lean).collect();
        let run_expr = format!("run State.init [{}]", lean_evs.join(", "));
        let mut conj = vec![
            format!("({run_expr}).queue = {}", lean_list(&t.expect.queue)),
            format!("({run_expr}).mergedLog = {}", lean_list(&t.expect.merged_log)),
            format!("({run_expr}).enqLog = {}", lean_list(&t.expect.enq_log)),
        ];
        for (p, l) in &t.expect.loc {
            conj.push(format!("({run_expr}).loc {p} = {}", lean_loc(*l)));
        }
        out.push_str(&format!(
            "/-- {} -/\nexample :\n    {} := by\n  decide\n\n",
            t.name,
            conj.join(" ∧\n    ")
        ));
    }
    for c in &g.capacity {
        out.push_str(&format!(
            "/-- {} -/\nexample : makespan (greedyFrom {} {}) = {} := by\n  decide\n\n",
            c.name,
            lean_list(&c.initial),
            lean_list(&c.jobs),
            c.makespan
        ));
    }
    out.push_str("end CiSpec.Golden\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const GOLDEN: &str = include_str!("../tests/golden/queue_traces.json");

    #[test]
    fn rust_replays_every_golden_vector() {
        let g = parse(GOLDEN).unwrap();
        let n = check_rust(&g).unwrap();
        assert!(n >= 6, "{n} vectors");
    }

    #[test]
    fn lean_rendering_is_stable_and_names_every_vector() {
        let g = parse(GOLDEN).unwrap();
        let lean = render_lean(&g).unwrap();
        for t in &g.traces {
            assert!(lean.contains(&format!("/-- {} -/", t.name)));
        }
        assert!(lean.contains("by\n  decide"));
        assert!(!lean.contains("sorry"));
    }
}
