-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreMediation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::mediation::opcode]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 100:0-116:1
    Visibility: public -/
def extracted.mediation.opcode
  (op : extracted.mediation.MedOperation) : Result Std.U8 := do
  match op with
  | extracted.mediation.MedOperation.ReadFiles => ok 0#u8
  | extracted.mediation.MedOperation.WriteFiles => ok 1#u8
  | extracted.mediation.MedOperation.EditFiles => ok 2#u8
  | extracted.mediation.MedOperation.RunBash => ok 3#u8
  | extracted.mediation.MedOperation.GlobSearch => ok 4#u8
  | extracted.mediation.MedOperation.GrepSearch => ok 5#u8
  | extracted.mediation.MedOperation.WebSearch => ok 6#u8
  | extracted.mediation.MedOperation.WebFetch => ok 7#u8
  | extracted.mediation.MedOperation.GitCommit => ok 8#u8
  | extracted.mediation.MedOperation.GitPush => ok 9#u8
  | extracted.mediation.MedOperation.CreatePr => ok 10#u8
  | extracted.mediation.MedOperation.ManagePods => ok 11#u8
  | extracted.mediation.MedOperation.SpawnAgent => ok 12#u8

/-- [nucleus_ifc_kernel::extracted::mediation::sinkcode]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 119:0-141:1
    Visibility: public -/
def extracted.mediation.sinkcode
  (sink : extracted.mediation.MedSinkClass) : Result Std.U8 := do
  match sink with
  | extracted.mediation.MedSinkClass.WorkspaceWrite => ok 0#u8
  | extracted.mediation.MedSinkClass.SystemWrite => ok 1#u8
  | extracted.mediation.MedSinkClass.BashExec => ok 2#u8
  | extracted.mediation.MedSinkClass.HTTPEgress => ok 3#u8
  | extracted.mediation.MedSinkClass.GitCommit => ok 4#u8
  | extracted.mediation.MedSinkClass.GitPush => ok 5#u8
  | extracted.mediation.MedSinkClass.PRCommentWrite => ok 6#u8
  | extracted.mediation.MedSinkClass.EmailSend => ok 7#u8
  | extracted.mediation.MedSinkClass.MemoryPersist => ok 8#u8
  | extracted.mediation.MedSinkClass.AgentSpawn => ok 9#u8
  | extracted.mediation.MedSinkClass.MCPWrite => ok 10#u8
  | extracted.mediation.MedSinkClass.SecretRead => ok 11#u8
  | extracted.mediation.MedSinkClass.CloudMutation => ok 12#u8
  | extracted.mediation.MedSinkClass.ProposedTableWrite => ok 13#u8
  | extracted.mediation.MedSinkClass.VerifiedTableWrite => ok 14#u8
  | extracted.mediation.MedSinkClass.SearchIndexWrite => ok 15#u8
  | extracted.mediation.MedSinkClass.CacheWrite => ok 16#u8
  | extracted.mediation.MedSinkClass.TicketWrite => ok 17#u8
  | extracted.mediation.MedSinkClass.AuditLogAppend => ok 18#u8

/-- [nucleus_ifc_kernel::extracted::mediation::scope_admits]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 150:0-157:1
    Visibility: public -/
def extracted.mediation.scope_admits
  (earned_op : extracted.mediation.MedOperation)
  (earned_sink : extracted.mediation.MedSinkClass)
  (attempted_op : extracted.mediation.MedOperation)
  (attempted_sink : extracted.mediation.MedSinkClass) :
  Result Bool
  := do
  let i ← extracted.mediation.opcode earned_op
  let i1 ← extracted.mediation.opcode attempted_op
  if i = i1
  then
    let i2 ← extracted.mediation.sinkcode earned_sink
    let i3 ← extracted.mediation.sinkcode attempted_sink
    ok (i2 = i3)
  else ok false

/-- [nucleus_ifc_kernel::extracted::mediation::med_idle]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 199:0-205:1
    Visibility: public -/
def extracted.mediation.med_idle : Result extracted.mediation.MedState := do
  ok
    {
      held := false,
      op := extracted.mediation.MedOperation.ReadFiles,
      sink := extracted.mediation.MedSinkClass.AuditLogAppend
    }

/-- [nucleus_ifc_kernel::extracted::mediation::med_step]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 222:0-243:1
    Visibility: public -/
def extracted.mediation.med_step
  (state : extracted.mediation.MedState)
  (action : extracted.mediation.MedAction) :
  Result extracted.mediation.StepResult
  := do
  match action with
  | extracted.mediation.MedAction.Discharge o k =>
    ok { ok := true, next := { held := true, op := o, sink := k } }
  | extracted.mediation.MedAction.Effect o k =>
    if state.held
    then
      let b ← extracted.mediation.scope_admits state.op state.sink o k
      if b
      then
        let ms ← extracted.mediation.med_idle
        ok { ok := true, next := ms }
      else ok { ok := false, next := state }
    else ok { ok := false, next := state }

end nucleus_ifc_kernel
