-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreMediation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::mediation::opcode]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 100:0-116:1
    Visibility: public -/
def extracted.mediation.opcode
  (op : extracted.mediation.MedOperation) : Result Std.U8 := do
  match op with
  | extracted.mediation.MedOperation.ReadFiles => ok 0#u8
  | extracted.mediation.MedOperation.WriteFiles => ok 1#u8
  | extracted.mediation.MedOperation.EditFiles => ok 2#u8
  | extracted.mediation.MedOperation.RunBash => ok 3#u8
  | extracted.mediation.MedOperation.GlobSearch => ok 4#u8
  | extracted.mediation.MedOperation.GrepSearch => ok 5#u8
  | extracted.mediation.MedOperation.WebSearch => ok 6#u8
  | extracted.mediation.MedOperation.WebFetch => ok 7#u8
  | extracted.mediation.MedOperation.GitCommit => ok 8#u8
  | extracted.mediation.MedOperation.GitPush => ok 9#u8
  | extracted.mediation.MedOperation.CreatePr => ok 10#u8
  | extracted.mediation.MedOperation.ManagePods => ok 11#u8
  | extracted.mediation.MedOperation.SpawnAgent => ok 12#u8

/-- [nucleus_ifc_kernel::extracted::mediation::sinkcode]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 119:0-141:1
    Visibility: public -/
def extracted.mediation.sinkcode
  (sink : extracted.mediation.MedSinkClass) : Result Std.U8 := do
  match sink with
  | extracted.mediation.MedSinkClass.WorkspaceWrite => ok 0#u8
  | extracted.mediation.MedSinkClass.SystemWrite => ok 1#u8
  | extracted.mediation.MedSinkClass.BashExec => ok 2#u8
  | extracted.mediation.MedSinkClass.HTTPEgress => ok 3#u8
  | extracted.mediation.MedSinkClass.GitCommit => ok 4#u8
  | extracted.mediation.MedSinkClass.GitPush => ok 5#u8
  | extracted.mediation.MedSinkClass.PRCommentWrite => ok 6#u8
  | extracted.mediation.MedSinkClass.EmailSend => ok 7#u8
  | extracted.mediation.MedSinkClass.MemoryPersist => ok 8#u8
  | extracted.mediation.MedSinkClass.AgentSpawn => ok 9#u8
  | extracted.mediation.MedSinkClass.MCPWrite => ok 10#u8
  | extracted.mediation.MedSinkClass.SecretRead => ok 11#u8
  | extracted.mediation.MedSinkClass.CloudMutation => ok 12#u8
  | extracted.mediation.MedSinkClass.ProposedTableWrite => ok 13#u8
  | extracted.mediation.MedSinkClass.VerifiedTableWrite => ok 14#u8
  | extracted.mediation.MedSinkClass.SearchIndexWrite => ok 15#u8
  | extracted.mediation.MedSinkClass.CacheWrite => ok 16#u8
  | extracted.mediation.MedSinkClass.TicketWrite => ok 17#u8
  | extracted.mediation.MedSinkClass.AuditLogAppend => ok 18#u8

/-- [nucleus_ifc_kernel::extracted::mediation::scope_admits]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 150:0-157:1
    Visibility: public -/
def extracted.mediation.scope_admits
  (earned_op : extracted.mediation.MedOperation)
  (earned_sink : extracted.mediation.MedSinkClass)
  (attempted_op : extracted.mediation.MedOperation)
  (attempted_sink : extracted.mediation.MedSinkClass) :
  Result Bool
  := do
  let i ← extracted.mediation.opcode earned_op
  let i1 ← extracted.mediation.opcode attempted_op
  if i = i1
  then
    let i2 ← extracted.mediation.sinkcode earned_sink
    let i3 ← extracted.mediation.sinkcode attempted_sink
    ok (i2 = i3)
  else ok false

end nucleus_ifc_kernel
