-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::mediation::MedOperation]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 56:0-70:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.mediation.MedOperation where
| ReadFiles : extracted.mediation.MedOperation
| WriteFiles : extracted.mediation.MedOperation
| EditFiles : extracted.mediation.MedOperation
| RunBash : extracted.mediation.MedOperation
| GlobSearch : extracted.mediation.MedOperation
| GrepSearch : extracted.mediation.MedOperation
| WebSearch : extracted.mediation.MedOperation
| WebFetch : extracted.mediation.MedOperation
| GitCommit : extracted.mediation.MedOperation
| GitPush : extracted.mediation.MedOperation
| CreatePr : extracted.mediation.MedOperation
| ManagePods : extracted.mediation.MedOperation
| SpawnAgent : extracted.mediation.MedOperation

/-- [nucleus_ifc_kernel::extracted::mediation::MedSinkClass]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 76:0-96:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.mediation.MedSinkClass where
| WorkspaceWrite : extracted.mediation.MedSinkClass
| SystemWrite : extracted.mediation.MedSinkClass
| BashExec : extracted.mediation.MedSinkClass
| HTTPEgress : extracted.mediation.MedSinkClass
| GitCommit : extracted.mediation.MedSinkClass
| GitPush : extracted.mediation.MedSinkClass
| PRCommentWrite : extracted.mediation.MedSinkClass
| EmailSend : extracted.mediation.MedSinkClass
| MemoryPersist : extracted.mediation.MedSinkClass
| AgentSpawn : extracted.mediation.MedSinkClass
| MCPWrite : extracted.mediation.MedSinkClass
| SecretRead : extracted.mediation.MedSinkClass
| CloudMutation : extracted.mediation.MedSinkClass
| ProposedTableWrite : extracted.mediation.MedSinkClass
| VerifiedTableWrite : extracted.mediation.MedSinkClass
| SearchIndexWrite : extracted.mediation.MedSinkClass
| CacheWrite : extracted.mediation.MedSinkClass
| TicketWrite : extracted.mediation.MedSinkClass
| AuditLogAppend : extracted.mediation.MedSinkClass

end nucleus_ifc_kernel
