-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreIFC.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::irank]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 74:0-80:1
    Visibility: public -/
def extracted.ifc_integrity.irank
  (l : extracted.ifc_integrity.IntegLevel) : Result Std.U8 := do
  match l with
  | extracted.ifc_integrity.IntegLevel.Adversarial => ok 0#u8
  | extracted.ifc_integrity.IntegLevel.Untrusted => ok 1#u8
  | extracted.ifc_integrity.IntegLevel.Trusted => ok 2#u8

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::imeet]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 89:0-95:1
    Visibility: public -/
def extracted.ifc_integrity.imeet
  (a : extracted.ifc_integrity.IntegLevel)
  (b : extracted.ifc_integrity.IntegLevel) :
  Result extracted.ifc_integrity.IntegLevel
  := do
  let i ← extracted.ifc_integrity.irank a
  let i1 ← extracted.ifc_integrity.irank b
  if i <= i1
  then ok a
  else ok b

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::iflows_to]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 103:0-105:1
    Visibility: public -/
def extracted.ifc_integrity.iflows_to
  (a : extracted.ifc_integrity.IntegLevel)
  (ceiling : extracted.ifc_integrity.IntegLevel) :
  Result Bool
  := do
  let i ← extracted.ifc_integrity.irank a
  let i1 ← extracted.ifc_integrity.irank ceiling
  ok (i >= i1)

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::irun_step]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 110:0-112:1
    Visibility: public -/
def extracted.ifc_integrity.irun_step
  (eff : extracted.ifc_integrity.IntegLevel)
  (src : extracted.ifc_integrity.IntegLevel) :
  Result extracted.ifc_integrity.IntegLevel
  := do
  extracted.ifc_integrity.imeet eff src

end nucleus_ifc_kernel
