-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::IntegLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 62:0-69:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_integrity.IntegLevel where
| Adversarial : extracted.ifc_integrity.IntegLevel
| Untrusted : extracted.ifc_integrity.IntegLevel
| Trusted : extracted.ifc_integrity.IntegLevel

end nucleus_ifc_kernel
