-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace portcullis_core

/-- [portcullis_core::extracted::ifc_integrity::IntegLevel]
    Source: 'crates/portcullis-core/src/extracted/ifc_integrity.rs', lines 62:0-69:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_integrity.IntegLevel where
| Adversarial : extracted.ifc_integrity.IntegLevel
| Untrusted : extracted.ifc_integrity.IntegLevel
| Trusted : extracted.ifc_integrity.IntegLevel

end portcullis_core
