-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::capability_quantale::CapLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/capability_quantale.rs', lines 23:0-30:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.capability_quantale.CapLevel where
| Never : extracted.capability_quantale.CapLevel
| LowRisk : extracted.capability_quantale.CapLevel
| Always : extracted.capability_quantale.CapLevel

/-- [nucleus_ifc_kernel::extracted::channel::ChannelKind]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/channel.rs', lines 65:0-79:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.channel.ChannelKind where
| Env : extracted.channel.ChannelKind
| Argv : extracted.channel.ChannelKind
| Cwd : extracted.channel.ChannelKind
| Stdio : extracted.channel.ChannelKind
| ExtraFd : extracted.channel.ChannelKind
| Uid : extracted.channel.ChannelKind

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::ConfLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 21:0-28:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_confidentiality.ConfLevel where
| Public : extracted.ifc_confidentiality.ConfLevel
| Internal : extracted.ifc_confidentiality.ConfLevel
| Secret : extracted.ifc_confidentiality.ConfLevel

/-- [nucleus_ifc_kernel::extracted::identity::MaterialKind]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/identity.rs', lines 95:0-122:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.identity.MaterialKind where
| SvidCert : extracted.identity.MaterialKind
| SvidPrivateKey : extracted.identity.MaterialKind
| TrustBundle : extracted.identity.MaterialKind
| TaskToken : extracted.identity.MaterialKind
| BrokerSecret : extracted.identity.MaterialKind
| ApprovalSecret : extracted.identity.MaterialKind
| SandboxToken : extracted.identity.MaterialKind
| DlcCredentials : extracted.identity.MaterialKind
| ProxyAuthSecret : extracted.identity.MaterialKind
| EgressEnv : extracted.identity.MaterialKind
| OrdinaryData : extracted.identity.MaterialKind

/-- [nucleus_ifc_kernel::extracted::identity::Principal]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/identity.rs', lines 82:0-90:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.identity.Principal where
| Host : extracted.identity.Principal
| GuestRuntime : extracted.identity.Principal
| Workload : extracted.identity.Principal

/-- [nucleus_ifc_kernel::extracted::credential::CredSink]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/credential.rs', lines 41:0-47:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.credential.CredSink where
| Guest : extracted.credential.CredSink
| ExternalService : extracted.credential.CredSink

/-- [nucleus_ifc_kernel::extracted::egress::Dest]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 52:0-57:1
    Visibility: public -/
structure extracted.egress.Dest where
  addr : Std.U32
  port : Std.U16

/-- [nucleus_ifc_kernel::extracted::egress::Rule]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/egress.rs', lines 61:0-72:1
    Visibility: public -/
structure extracted.egress.Rule where
  net : Std.U32
  «prefix» : Std.U8
  port_specific : Bool
  port : Std.U16
  allow : Bool

/-- [nucleus_ifc_kernel::extracted::ifc_integrity::IntegLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_integrity.rs', lines 59:0-66:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_integrity.IntegLevel where
| Adversarial : extracted.ifc_integrity.IntegLevel
| Untrusted : extracted.ifc_integrity.IntegLevel
| Trusted : extracted.ifc_integrity.IntegLevel

/-- [nucleus_ifc_kernel::extracted::mediation::MedOperation]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 56:0-70:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.mediation.MedOperation where
| ReadFiles : extracted.mediation.MedOperation
| WriteFiles : extracted.mediation.MedOperation
| EditFiles : extracted.mediation.MedOperation
| RunBash : extracted.mediation.MedOperation
| GlobSearch : extracted.mediation.MedOperation
| GrepSearch : extracted.mediation.MedOperation
| WebSearch : extracted.mediation.MedOperation
| WebFetch : extracted.mediation.MedOperation
| GitCommit : extracted.mediation.MedOperation
| GitPush : extracted.mediation.MedOperation
| CreatePr : extracted.mediation.MedOperation
| ManagePods : extracted.mediation.MedOperation
| SpawnAgent : extracted.mediation.MedOperation

/-- [nucleus_ifc_kernel::extracted::mediation::MedSinkClass]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 76:0-96:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.mediation.MedSinkClass where
| WorkspaceWrite : extracted.mediation.MedSinkClass
| SystemWrite : extracted.mediation.MedSinkClass
| BashExec : extracted.mediation.MedSinkClass
| HTTPEgress : extracted.mediation.MedSinkClass
| GitCommit : extracted.mediation.MedSinkClass
| GitPush : extracted.mediation.MedSinkClass
| PRCommentWrite : extracted.mediation.MedSinkClass
| EmailSend : extracted.mediation.MedSinkClass
| MemoryPersist : extracted.mediation.MedSinkClass
| AgentSpawn : extracted.mediation.MedSinkClass
| MCPWrite : extracted.mediation.MedSinkClass
| SecretRead : extracted.mediation.MedSinkClass
| CloudMutation : extracted.mediation.MedSinkClass
| ProposedTableWrite : extracted.mediation.MedSinkClass
| VerifiedTableWrite : extracted.mediation.MedSinkClass
| SearchIndexWrite : extracted.mediation.MedSinkClass
| CacheWrite : extracted.mediation.MedSinkClass
| TicketWrite : extracted.mediation.MedSinkClass
| AuditLogAppend : extracted.mediation.MedSinkClass

/-- [nucleus_ifc_kernel::extracted::mediation::MedState]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 170:0-177:1
    Visibility: public -/
structure extracted.mediation.MedState where
  held : Bool
  op : extracted.mediation.MedOperation
  sink : extracted.mediation.MedSinkClass

/-- [nucleus_ifc_kernel::extracted::mediation::MedAction]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 181:0-186:1
    Visibility: public -/
@[discriminant isize]
inductive extracted.mediation.MedAction where
| Discharge :
  extracted.mediation.MedOperation →
  extracted.mediation.MedSinkClass →
  extracted.mediation.MedAction
| Effect :
  extracted.mediation.MedOperation →
  extracted.mediation.MedSinkClass →
  extracted.mediation.MedAction

/-- [nucleus_ifc_kernel::extracted::mediation::StepResult]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 190:0-196:1
    Visibility: public -/
structure extracted.mediation.StepResult where
  ok : Bool
  next : extracted.mediation.MedState

end nucleus_ifc_kernel
