-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: function definitions
import Aeneas
import PortcullisCoreDecide.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace portcullis_core

/-- [portcullis_core::{impl core::cmp::PartialEq<portcullis_core::CapabilityLevel> for portcullis_core::CapabilityLevel}::eq]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 162:29-162:38
    Visibility: public -/
def CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq
  (self : CapabilityLevel) (other : CapabilityLevel) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [portcullis_core::{portcullis_core::ExposureSet}::set]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1306:4-1312:5
    Visibility: public -/
def ExposureSet.set
  (self : ExposureSet) (label : ExposureLabel) : Result ExposureSet := do
  match label with
  | ExposureLabel.PrivateData => ok { self with private_data := true }
  | ExposureLabel.UntrustedContent =>
    ok { self with untrusted_content := true }
  | ExposureLabel.ExfilVector => ok { self with exfil_vector := true }

/-- [portcullis_core::{portcullis_core::ExposureSet}::is_uninhabitable]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1333:4-1335:5
    Visibility: public -/
def ExposureSet.is_uninhabitable (self : ExposureSet) : Result Bool := do
  if self.private_data
  then if self.untrusted_content
       then ok self.exfil_vector
       else ok false
  else ok false

/-- [portcullis_core::classify_operation]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1351:0-1365:1
    Visibility: public -/
def classify_operation (op : Operation) : Result (Option ExposureLabel) := do
  match op with
  | Operation.ReadFiles => ok (some ExposureLabel.PrivateData)
  | Operation.WriteFiles => ok none
  | Operation.EditFiles => ok none
  | Operation.RunBash => ok (some ExposureLabel.ExfilVector)
  | Operation.GlobSearch => ok (some ExposureLabel.PrivateData)
  | Operation.GrepSearch => ok (some ExposureLabel.PrivateData)
  | Operation.WebSearch => ok (some ExposureLabel.UntrustedContent)
  | Operation.WebFetch => ok (some ExposureLabel.UntrustedContent)
  | Operation.GitCommit => ok none
  | Operation.GitPush => ok (some ExposureLabel.ExfilVector)
  | Operation.CreatePr => ok (some ExposureLabel.ExfilVector)
  | Operation.ManagePods => ok none
  | Operation.SpawnAgent => ok (some ExposureLabel.ExfilVector)

/-- [portcullis_core::project_exposure]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1368:0-1377:1
    Visibility: public -/
def project_exposure
  (current : ExposureSet) (op : Operation) : Result ExposureSet := do
  let o ← classify_operation op
  match o with
  | none => ok current
  | some label => ExposureSet.set current label

/-- [portcullis_core::is_exfil_operation]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1385:0-1387:1
    Visibility: public -/
def is_exfil_operation (op : Operation) : Result Bool := do
  let o ← classify_operation op
  match o with
  | none => ok false
  | some el =>
    match el with
    | ExposureLabel.PrivateData => ok false
    | ExposureLabel.UntrustedContent => ok false
    | ExposureLabel.ExfilVector => ok true

/-- [portcullis_core::should_gate]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 1394:0-1397:1
    Visibility: public -/
def should_gate (current : ExposureSet) (op : Operation) : Result Bool := do
  let projected ← project_exposure current op
  let b ← ExposureSet.is_uninhabitable current
  if b
  then is_exfil_operation op
  else
    let b1 ← ExposureSet.is_uninhabitable projected
    if b1
    then is_exfil_operation op
    else ok false

/-- [portcullis_core::decide_pure]:
    Source: 'crates/portcullis-core/src/lib.rs', lines 2003:0-2020:1
    Visibility: public -/
def decide_pure
  (level : CapabilityLevel) (exposure : ExposureSet) (op : Operation) :
  Result PureVerdict
  := do
  let b ←
    CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq level
      CapabilityLevel.Never
  if b
  then ok PureVerdict.DenyCapability
  else
    let b1 ←
      CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq level
        CapabilityLevel.LowRisk
    if b1
    then ok PureVerdict.RequiresApproval
    else
      let b2 ← should_gate exposure op
      if b2
      then ok PureVerdict.GateExfil
      else ok PureVerdict.Allow

end portcullis_core
