-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreDecide.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::capability_level::{impl core::cmp::PartialEq<nucleus_ifc_kernel::capability_level::CapabilityLevel> for nucleus_ifc_kernel::capability_level::CapabilityLevel}::eq]:
    Source: 'crates/nucleus-ifc-kernel/src/capability_level.rs', lines 17:29-17:38
    Visibility: public -/
def capability_level.CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq
  (self : capability_level.CapabilityLevel)
  (other : capability_level.CapabilityLevel) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [nucleus_ifc_kernel::exposure::{nucleus_ifc_kernel::exposure::ExposureSet}::set]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 58:4-64:5
    Visibility: public -/
def exposure.ExposureSet.set
  (self : exposure.ExposureSet) (label : exposure.ExposureLabel) :
  Result exposure.ExposureSet
  := do
  match label with
  | exposure.ExposureLabel.PrivateData => ok { self with private_data := true }
  | exposure.ExposureLabel.UntrustedContent =>
    ok { self with untrusted_content := true }
  | exposure.ExposureLabel.ExfilVector => ok { self with exfil_vector := true }

/-- [nucleus_ifc_kernel::exposure::{nucleus_ifc_kernel::exposure::ExposureSet}::is_uninhabitable]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 85:4-87:5
    Visibility: public -/
def exposure.ExposureSet.is_uninhabitable
  (self : exposure.ExposureSet) : Result Bool := do
  if self.private_data
  then if self.untrusted_content
       then ok self.exfil_vector
       else ok false
  else ok false

/-- [nucleus_ifc_kernel::exposure::classify_operation]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 106:0-121:1
    Visibility: public -/
def exposure.classify_operation
  (op : ifc_ops.Operation) : Result (Option exposure.ExposureLabel) := do
  match op with
  | ifc_ops.Operation.ReadFiles => ok (some exposure.ExposureLabel.PrivateData)
  | ifc_ops.Operation.WriteFiles =>
    ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.EditFiles => ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.RunBash => ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.GlobSearch =>
    ok (some exposure.ExposureLabel.PrivateData)
  | ifc_ops.Operation.GrepSearch =>
    ok (some exposure.ExposureLabel.PrivateData)
  | ifc_ops.Operation.WebSearch =>
    ok (some exposure.ExposureLabel.UntrustedContent)
  | ifc_ops.Operation.WebFetch =>
    ok (some exposure.ExposureLabel.UntrustedContent)
  | ifc_ops.Operation.GitCommit => ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.GitPush => ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.CreatePr => ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.ManagePods =>
    ok (some exposure.ExposureLabel.ExfilVector)
  | ifc_ops.Operation.SpawnAgent =>
    ok (some exposure.ExposureLabel.ExfilVector)

/-- [nucleus_ifc_kernel::exposure::project_exposure]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 124:0-133:1
    Visibility: public -/
def exposure.project_exposure
  (current : exposure.ExposureSet) (op : ifc_ops.Operation) :
  Result exposure.ExposureSet
  := do
  let o ← exposure.classify_operation op
  match o with
  | none => ok current
  | some label => exposure.ExposureSet.set current label

/-- [nucleus_ifc_kernel::ifc_ops::is_exfil_operation]:
    Source: 'crates/nucleus-ifc-kernel/src/ifc_ops.rs', lines 470:0-482:1
    Visibility: public -/
def ifc_ops.is_exfil_operation (op : ifc_ops.Operation) : Result Bool := do
  match op with
  | ifc_ops.Operation.ReadFiles => ok false
  | ifc_ops.Operation.WriteFiles => ok true
  | ifc_ops.Operation.EditFiles => ok true
  | ifc_ops.Operation.RunBash => ok true
  | ifc_ops.Operation.GlobSearch => ok false
  | ifc_ops.Operation.GrepSearch => ok false
  | ifc_ops.Operation.WebSearch => ok false
  | ifc_ops.Operation.WebFetch => ok false
  | ifc_ops.Operation.GitCommit => ok true
  | ifc_ops.Operation.GitPush => ok true
  | ifc_ops.Operation.CreatePr => ok true
  | ifc_ops.Operation.ManagePods => ok true
  | ifc_ops.Operation.SpawnAgent => ok true

/-- [nucleus_ifc_kernel::exposure::should_gate]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 150:0-153:1
    Visibility: public -/
def exposure.should_gate
  (current : exposure.ExposureSet) (op : ifc_ops.Operation) : Result Bool := do
  let projected ← exposure.project_exposure current op
  let b ← exposure.ExposureSet.is_uninhabitable current
  if b
  then ifc_ops.is_exfil_operation op
  else
    let b1 ← exposure.ExposureSet.is_uninhabitable projected
    if b1
    then ifc_ops.is_exfil_operation op
    else ok false

/-- [nucleus_ifc_kernel::exposure::decide_pure]:
    Source: 'crates/nucleus-ifc-kernel/src/exposure.rs', lines 209:0-226:1
    Visibility: public -/
def exposure.decide_pure
  (level : capability_level.CapabilityLevel) (exposure : exposure.ExposureSet)
  (op : ifc_ops.Operation) :
  Result exposure.PureVerdict
  := do
  let b ←
    capability_level.CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq
      level capability_level.CapabilityLevel.Never
  if b
  then ok exposure.PureVerdict.DenyCapability
  else
    let b1 ←
      capability_level.CapabilityLevel.Insts.CoreCmpPartialEqCapabilityLevel.eq
        level capability_level.CapabilityLevel.LowRisk
    if b1
    then ok exposure.PureVerdict.RequiresApproval
    else
      let b2 ← exposure.should_gate exposure op
      if b2
      then ok exposure.PureVerdict.GateExfil
      else ok exposure.PureVerdict.Allow

end nucleus_ifc_kernel
