-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace portcullis_core

/-- [portcullis_core::CapabilityLevel]
    Source: 'crates/portcullis-core/src/lib.rs', lines 166:0-174:1
    Visibility: public -/
@[discriminant u8]
inductive CapabilityLevel where
| Never : CapabilityLevel
| LowRisk : CapabilityLevel
| Always : CapabilityLevel

/-- [portcullis_core::Operation]
    Source: 'crates/portcullis-core/src/lib.rs', lines 812:0-841:1
    Visibility: public -/
@[discriminant u8]
inductive Operation where
| ReadFiles : Operation
| WriteFiles : Operation
| EditFiles : Operation
| RunBash : Operation
| GlobSearch : Operation
| GrepSearch : Operation
| WebSearch : Operation
| WebFetch : Operation
| GitCommit : Operation
| GitPush : Operation
| CreatePr : Operation
| ManagePods : Operation
| SpawnAgent : Operation

/-- [portcullis_core::ExposureLabel]
    Source: 'crates/portcullis-core/src/lib.rs', lines 1264:0-1271:1
    Visibility: public -/
@[discriminant u8]
inductive ExposureLabel where
| PrivateData : ExposureLabel
| UntrustedContent : ExposureLabel
| ExfilVector : ExposureLabel

/-- [portcullis_core::ExposureSet]
    Source: 'crates/portcullis-core/src/lib.rs', lines 1286:0-1290:1
    Visibility: public -/
structure ExposureSet where
  private_data : Bool
  untrusted_content : Bool
  exfil_vector : Bool

/-- [portcullis_core::PureVerdict]
    Source: 'crates/portcullis-core/src/lib.rs', lines 1981:0-1990:1
    Visibility: public -/
@[discriminant isize]
inductive PureVerdict where
| Allow : PureVerdict
| DenyCapability : PureVerdict
| RequiresApproval : PureVerdict
| GateExfil : PureVerdict

end portcullis_core
