//! `cargo xtask live-boot-evidence` — turn a CI live boot into a verified
//! evidence bundle.
//!
//! On a KVM host after `nucleus setup`:
//!
//! 1. **Collect.** The `nucleus-cli` live collector boots a fresh,
//!    host-spec-enforcing node from the installed binary and runs two pods: the
//!    posture workload (the in-guest probes), which yields the admission, the
//!    signed execution receipt, the exact logs and a declared artifact; and one
//!    credentialed request, which yields the host-effect journal. It also
//!    measures the node binaries as they ran, the platform the receipt states,
//!    and timings. It verifies nothing.
//! 2. **Predict.** The reference manifest a release of this build would publish
//!    is generated by the release's own function and its predictions are
//!    checked against what booted.
//! 3. **Verify, publicly.** `nucleus-audit` (prepare-execution, then
//!    verify-execution, verify-logs, verify-artifacts, verify-host-effects, and
//!    verify-node-evidence when the receipt names evidence), the JS SDK and the
//!    Python SDK judge the same inputs and must agree. Each verifier is also
//!    handed a tampered input it must refuse.
//! 4. **Write** the bundle directory and `summary.json`, and exit non-zero on
//!    any failure. Every check is `pass | fail | could_not_run`, and
//!    `could_not_run` is red unless `--allow-could-not-run` names it.
//!
//! An unattested node is recorded as `unattested` with the receipt's reason.
//! Nothing here upgrades it.

mod parity;
mod posture;
mod predict;
mod verdict;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail, ensure};
use nucleus_spec::live_boot::{self, Collection, NodeEvidence};
use serde::Serialize;

use crate::release_reference::Arch;
use parity::Seen;
use verdict::{Check, Outcome, Verdict};

/// The summary's schema.
const SUMMARY_SCHEMA: &str = "nucleus-live-boot-summary/v1";

/// How long the prepared expectations stay valid, from now.
const EXPECTATIONS_VALID_MICROS: u64 = 30 * 60 * 1_000_000;

/// Arguments.
#[derive(clap::Args, Debug)]
pub struct Args {
    /// The build's musl release directory: `nucleus-node`, `nucleus-hostctl`,
    /// `nucleus-audit`.
    #[arg(long)]
    bin_dir: PathBuf,
    /// The node binary the collector starts. The installed one, because a
    /// release manifest names the install path.
    #[arg(long, default_value = "/usr/local/bin/nucleus-node")]
    node_bin: PathBuf,
    /// The bundle directory to create. It must not exist.
    #[arg(long)]
    out: PathBuf,
    /// Run the collector as root through sudo.
    #[arg(long)]
    sudo: bool,
    /// The build's architecture, for the reference manifest.
    #[arg(long, value_enum)]
    arch: Arch,
    /// A check allowed to end `could_not_run`, by name (e.g.
    /// `posture.landlock`). It must name a check this run has; it never
    /// covers a `fail`.
    #[arg(long)]
    allow_could_not_run: Vec<String>,
    /// The node's TPM. Without it the node runs unattested, and the summary
    /// says so with the receipt's own reason.
    #[arg(long)]
    node_evidence_tpm: Option<PathBuf>,
    /// Passed to the node as `--node-evidence-ak-template`.
    #[arg(long, requires = "node_evidence_tpm")]
    node_evidence_ak_template: Option<String>,
    /// Passed to the node as `--node-evidence-anchor`.
    #[arg(long, requires = "node_evidence_tpm")]
    node_evidence_anchor: Option<String>,
    /// `SOURCE=SPKI_SHA256`: an operator pin for appraising node evidence.
    #[arg(long)]
    operator_pin: Vec<String>,
}

/// A tool's run, kept in the bundle beside the verdict it produced.
struct Ran {
    success: bool,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
}

impl Ran {
    fn json(&self) -> Option<serde_json::Value> {
        serde_json::from_slice(&self.stdout).ok()
    }
    fn why(&self) -> String {
        let text = String::from_utf8_lossy(&self.stderr);
        let text = text.trim();
        text.lines().last().unwrap_or("no output").to_string()
    }
}

struct Bundle {
    root: PathBuf,
    outputs: PathBuf,
    collection: Collection,
}

impl Bundle {
    fn path(&self, name: &str) -> PathBuf {
        self.root.join(name)
    }

    /// Run `command`, saving its output as `verifier-output/<name>.{stdout,stderr}`.
    fn run(&self, name: &str, command: &mut Command) -> Result<Ran> {
        let output = command
            .output()
            .with_context(|| format!("running {name} ({:?})", command.get_program()))?;
        std::fs::write(self.outputs.join(format!("{name}.stdout")), &output.stdout)?;
        std::fs::write(self.outputs.join(format!("{name}.stderr")), &output.stderr)?;
        Ok(Ran {
            success: output.status.success(),
            stdout: output.stdout,
            stderr: output.stderr,
        })
    }
}

fn nonce() -> Result<String> {
    use std::io::Read;
    let mut bytes = [0u8; 16];
    std::fs::File::open("/dev/urandom")?.read_exact(&mut bytes)?;
    Ok(hex::encode(bytes))
}

fn now_micros() -> Result<u64> {
    Ok(u64::try_from(
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_micros(),
    )?)
}

/// Step 1: run the collector, under sudo when asked, and give the files back
/// to the invoking user.
fn collect(root: &Path, a: &Args, out: &Path, nonce: &str) -> Result<()> {
    let bins = a.bin_dir.canonicalize().context("binary directory")?;
    for name in ["nucleus-hostctl", "nucleus-audit"] {
        ensure!(
            bins.join(name).is_file(),
            "missing {}",
            bins.join(name).display()
        );
    }
    ensure!(a.node_bin.is_file(), "missing {}", a.node_bin.display());
    let test = crate::host_evidence_live::cli_test_executable(root)?;
    let mut node_args = Vec::new();
    if let Some(tpm) = &a.node_evidence_tpm {
        node_args.push(format!("--node-evidence-tpm={}", tpm.display()));
    }
    if let Some(t) = &a.node_evidence_ak_template {
        node_args.push(format!("--node-evidence-ak-template={t}"));
    }
    if let Some(anchor) = &a.node_evidence_anchor {
        node_args.push(format!("--node-evidence-anchor={anchor}"));
    }
    let witness_dir = tempfile::tempdir()?;
    let witness = witness_dir.path().join("collected");
    let mut command = if a.sudo {
        let mut c = Command::new("sudo");
        c.args(["--", "env"]);
        c
    } else {
        Command::new("env")
    };
    command
        .arg(format!("NUCLEUS_LIVE_BOOT_BIN_DIR={}", bins.display()))
        .arg(format!(
            "NUCLEUS_LIVE_BOOT_NODE_BIN={}",
            a.node_bin.display()
        ))
        .arg(format!("NUCLEUS_LIVE_BOOT_OUT={}", out.display()))
        .arg(format!("NUCLEUS_LIVE_BOOT_WITNESS={}", witness.display()))
        .arg(format!("NUCLEUS_LIVE_BOOT_NONCE={nonce}"))
        .arg(format!(
            "NUCLEUS_LIVE_BOOT_NODE_ARGS={}",
            node_args.join("\n")
        ))
        .arg(test)
        .args([
            "live_boot_evidence::collect_live_boot_evidence",
            "--ignored",
            "--exact",
            "--nocapture",
        ]);
    let status = command.status()?;
    if a.sudo {
        // The collector ran as root; the bundle is uploaded as this user.
        use std::os::unix::fs::MetadataExt;
        let meta = std::fs::metadata(out)?;
        let owner = format!("{}:{}", meta.uid(), meta.gid());
        let chown = Command::new("sudo")
            .args(["chown", "-R", &owner])
            .arg(out)
            .status()?;
        ensure!(
            chown.success(),
            "returning {} to {owner}: {chown}",
            out.display()
        );
    }
    ensure!(status.success(), "the live collector failed: {status}");
    // The witness is written only after every file and the node's shutdown:
    // a zero exit with no tests selected is not a collection.
    ensure!(
        std::fs::read_to_string(&witness).context("the collector produced no witness")? == nonce,
        "the collector's witness does not identify this invocation"
    );
    Ok(())
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T> {
    serde_json::from_slice(
        &std::fs::read(path).with_context(|| format!("reading {}", path.display()))?,
    )
    .with_context(|| format!("parsing {}", path.display()))
}

/// Everything the appraisal decided.
#[derive(Serialize)]
struct Summary {
    schema: &'static str,
    nonce: String,
    execution_pod: Option<String>,
    effect_pod: Option<String>,
    outcome: Outcome,
    checks: Vec<Check>,
    /// The platform tier `nucleus-audit verify-execution` reported.
    tier: String,
    /// The AK anchor, when the evidence was appraised; `none` otherwise.
    anchor: String,
    /// `verify-execution`'s platform report, verbatim.
    platform: serde_json::Value,
    posture: Vec<posture::Observed>,
    not_checked: Vec<predict::NotChecked>,
    timings: Option<live_boot::Timings>,
}

/// Run.
pub fn run(root: &Path, a: &Args) -> Result<()> {
    ensure!(
        cfg!(target_os = "linux"),
        "live-boot-evidence requires Linux and KVM"
    );
    ensure!(!a.out.exists(), "{} already exists", a.out.display());
    std::fs::create_dir_all(&a.out)?;
    let out = a.out.canonicalize()?;
    let nonce = nonce()?;
    let mut checks = Vec::new();
    let collected = collect(root, a, &out, &nonce);
    let mut summary = Summary {
        schema: SUMMARY_SCHEMA,
        nonce: nonce.clone(),
        execution_pod: None,
        effect_pod: None,
        outcome: Outcome::Red {
            reasons: vec!["not decided".into()],
        },
        checks: Vec::new(),
        tier: "unknown".into(),
        anchor: "none".into(),
        platform: serde_json::Value::Null,
        posture: Vec::new(),
        not_checked: Vec::new(),
        timings: None,
    };
    match collected {
        Err(e) => checks.push(Check::new("collect", Verdict::Fail(format!("{e:#}")))),
        Ok(()) => {
            let appraised = (|| {
                let collection: Collection = read_json(&out.join(live_boot::COLLECTION_FILE))?;
                ensure!(
                    collection.schema == live_boot::SCHEMA,
                    "unknown collection schema"
                );
                ensure!(
                    collection.nonce == nonce,
                    "the collection is not this run's"
                );
                summary.execution_pod = Some(collection.execution_pod.clone());
                summary.effect_pod = Some(collection.effect_pod.clone());
                summary.timings = Some(collection.timings.clone());
                checks.push(Check::new(
                    "collect",
                    Verdict::Pass(format!(
                        "pods {} and {}",
                        collection.execution_pod, collection.effect_pod
                    )),
                ));
                let outputs = out.join("verifier-output");
                std::fs::create_dir_all(&outputs)?;
                let bundle = Bundle {
                    root: out.clone(),
                    outputs,
                    collection,
                };
                appraise(root, a, &bundle, &mut checks, &mut summary)
            })();
            if let Err(e) = appraised {
                // Whatever was decided before the error stands; the error is
                // its own failure, never a silent stop.
                checks.push(Check::new("appraise", Verdict::Fail(format!("{e:#}"))));
            }
        }
    }
    let allowed: BTreeSet<String> = a.allow_could_not_run.iter().cloned().collect();
    summary.outcome = verdict::fold(&checks, &allowed);
    summary.checks = checks;
    std::fs::write(
        out.join("summary.json"),
        serde_json::to_vec_pretty(&summary)?,
    )?;
    print_summary(&summary);
    match &summary.outcome {
        Outcome::Green { .. } => Ok(()),
        Outcome::Red { reasons } => bail!(
            "live-boot-evidence is red ({} reasons); see {}/summary.json",
            reasons.len(),
            out.display()
        ),
    }
}

fn print_summary(s: &Summary) {
    println!("live-boot-evidence {}", s.nonce);
    for c in &s.checks {
        let (tag, detail) = match &c.verdict {
            Verdict::Pass(d) => ("PASS", d),
            Verdict::Fail(d) => ("FAIL", d),
            Verdict::CouldNotRun(d) => ("COULD-NOT-RUN", d),
        };
        println!("  {tag:<13} {:<44} {detail}", c.name);
    }
    println!("  tier: {}  anchor: {}", s.tier, s.anchor);
    for n in &s.not_checked {
        println!("  not checked: {}: {}", n.what, n.reason);
    }
    if let Some(t) = &s.timings {
        println!(
            "  timings (ms): node ready {}, pod create {}, guest proxy ready {}, workload exit {}, effect pod create {}, total {}",
            t.node_ready_ms,
            t.pod_create_ms,
            t.guest_proxy_ready_ms,
            t.workload_exit_ms,
            t.effect_pod_create_ms,
            t.total_ms
        );
    }
    match &s.outcome {
        Outcome::Green { stale_allowances } => {
            println!("  GREEN");
            for a in stale_allowances {
                println!("  warning: --allow-could-not-run {a} is no longer needed: it passed");
            }
        }
        Outcome::Red { reasons } => {
            println!("  RED");
            for r in reasons {
                println!("    {r}");
            }
        }
    }
}

/// A copy of `name` under `tamper/`, changed by `change`.
fn tampered(
    b: &Bundle,
    name: &str,
    change: impl FnOnce(Vec<u8>) -> Result<Vec<u8>>,
) -> Result<PathBuf> {
    let dir = b.root.join("tamper");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join(name);
    std::fs::write(&path, change(std::fs::read(b.path(name))?)?)?;
    Ok(path)
}

fn json_change(
    bytes: Vec<u8>,
    change: impl FnOnce(&mut serde_json::Value) -> Option<()>,
) -> Result<Vec<u8>> {
    let mut v: serde_json::Value = serde_json::from_slice(&bytes)?;
    change(&mut v).context("the field to tamper with is absent")?;
    Ok(serde_json::to_vec_pretty(&v)?)
}

/// A refusal control: the verifier must reject the tampered input.
fn must_refuse(name: &str, ran: Result<Ran>) -> Check {
    Check::new(
        name,
        match ran {
            Ok(r) if r.success => Verdict::Fail("the verifier ACCEPTED a tampered input".into()),
            Ok(r) => Verdict::Pass(format!("refused: {}", r.why())),
            Err(e) => Verdict::CouldNotRun(format!("{e:#}")),
        },
    )
}

fn appraise(
    root: &Path,
    a: &Args,
    b: &Bundle,
    checks: &mut Vec<Check>,
    summary: &mut Summary,
) -> Result<()> {
    let files = &b.collection.files;
    let audit = a.bin_dir.join("nucleus-audit");

    // ── 2. The manifest this build would publish, against what booted ──
    let work = tempfile::tempdir()?;
    match predict::generate(&a.bin_dir, a.arch, work.path()) {
        Ok(manifest) => {
            std::fs::write(
                b.path("reference-manifest.json"),
                serde_json::to_vec_pretty(&manifest)?,
            )?;
            let (predicted, not_checked) = predict::check(&manifest, &b.collection.measured);
            checks.extend(predicted);
            summary.not_checked = not_checked;
        }
        Err(e) => checks.push(Check::new(
            "prediction",
            Verdict::CouldNotRun(format!("generating the reference manifest: {e:#}")),
        )),
    }

    // ── 3. The public verifiers ──
    // The signer is enrolled from the node's authenticated admission record,
    // never from the receipt it is about to check.
    let admission: nucleus_spec::workload_admission::WorkloadAdmission =
        read_json(&b.path(&files.admission))?;
    let signer = hex::encode(admission.verifying_key);
    let expectations = b.path("expectations.json");
    let prepared = b.run(
        "prepare-execution",
        Command::new(&audit)
            .arg("prepare-execution")
            .arg("--admission")
            .arg(b.path(&files.admission))
            .args(["--signer-key-hex", &signer])
            .arg("--environment-inputs")
            .arg(b.path(&files.environment_inputs))
            .args([
                "--valid-until-micros",
                &(now_micros()? + EXPECTATIONS_VALID_MICROS).to_string(),
            ])
            .arg("--artifacts")
            .arg(b.path(&files.artifact_selection)),
    )?;
    ensure!(
        prepared.success,
        "nucleus-audit prepare-execution: {}",
        prepared.why()
    );
    std::fs::write(&expectations, &prepared.stdout)?;
    checks.push(Check::new(
        "audit.prepare_execution",
        Verdict::Pass(
            "expectations from the authenticated admission and the requested inputs".into(),
        ),
    ));

    let receipt = b.path(&files.receipt);
    let receipt_json: serde_json::Value = read_json(&receipt)?;
    let root_hash = receipt_json["root_hash_hex"]
        .as_str()
        .unwrap_or_default()
        .to_string();
    let reference = b.path("reference-manifest.json");
    let evidence = match &b.collection.node_evidence {
        NodeEvidence::Evidence { file, .. } => Some(b.path(file)),
        NodeEvidence::Unattested { .. } => None,
    };
    let verify_execution = |receipt: &Path, name: &str| -> Result<Ran> {
        let mut c = Command::new(&audit);
        c.arg("verify-execution")
            .arg("--receipt")
            .arg(receipt)
            .arg("--expectations")
            .arg(&expectations);
        if let Some(evidence) = &evidence {
            c.arg("--node-evidence")
                .arg(evidence)
                .arg("--node-reference")
                .arg(&reference);
            for pin in &a.operator_pin {
                c.args(["--operator-pin", pin]);
            }
        }
        b.run(name, &mut c)
    };
    let executed = verify_execution(&receipt, "verify-execution")?;
    let audit_seen = if executed.success {
        let report = executed.json().unwrap_or_default();
        let platform = report["node_platform"]["platform"].clone();
        summary.tier = platform["tier"]
            .as_str()
            .map(str::to_owned)
            .unwrap_or_else(|| platform.to_string());
        let anchor = &platform["ear"]["submods"]["node"]["nucleus.appraisal"]["anchor"];
        summary.anchor = if anchor.is_null() {
            "none".into()
        } else {
            anchor.to_string()
        };
        summary.platform = report["node_platform"].clone();
        let exit = report["claim"]["exit_code"].clone();
        checks.push(Check::new(
            "audit.verify_execution",
            if exit == serde_json::json!(0) {
                Verdict::Pass(format!(
                    "{}; tier {}",
                    report["node_platform"]["verdict"], summary.tier
                ))
            } else {
                Verdict::Fail(format!(
                    "the receipt is genuine and the workload exited {exit}"
                ))
            },
        ));
        Seen::Accepted(None)
    } else {
        checks.push(Check::new(
            "audit.verify_execution",
            Verdict::Fail(executed.why()),
        ));
        Seen::Refused(executed.why())
    };
    if let NodeEvidence::Unattested { reason } = &b.collection.node_evidence {
        // Recorded as the receipt states it, never upgraded.
        if summary.tier == "unknown" {
            summary.tier = "unattested".into();
        }
        summary.platform =
            serde_json::json!({"tier": "unattested", "reason": reason, "from": "receipt"});
    }

    let logs = b.run(
        "verify-logs",
        Command::new(&audit)
            .arg("verify-logs")
            .arg("--receipt")
            .arg(&receipt)
            .arg("--expectations")
            .arg(&expectations)
            .arg("--stdout")
            .arg(b.path(&files.stdout))
            .arg("--stderr")
            .arg(b.path(&files.stderr)),
    )?;
    checks.push(Check::new(
        "audit.verify_logs",
        if logs.success {
            Verdict::Pass(format!(
                "{}",
                logs.json().unwrap_or_default()["log_bytes_verified"]
            ))
        } else {
            Verdict::Fail(logs.why())
        },
    ));

    let verified_dir = b.path("verified-artifacts");
    let artifacts = b.run(
        "verify-artifacts",
        Command::new(&audit)
            .arg("verify-artifacts")
            .arg("--bundle")
            .arg(b.path(&files.artifacts_bundle))
            .arg("--expectations")
            .arg(&expectations)
            .arg("--output-dir")
            .arg(&verified_dir),
    )?;
    let note = live_boot::artifact_bytes(&b.collection.nonce);
    checks.push(Check::new(
        "audit.verify_artifacts",
        if !artifacts.success {
            Verdict::Fail(artifacts.why())
        } else {
            match std::fs::read(verified_dir.join(live_boot::ARTIFACT_NAME)) {
                Ok(bytes) if bytes == note.as_bytes() => Verdict::Pass(format!(
                    "{} holds the requested bytes",
                    live_boot::ARTIFACT_NAME
                )),
                Ok(bytes) => Verdict::Fail(format!(
                    "the verified artifact is {:?}, not the requested {note:?}",
                    String::from_utf8_lossy(&bytes)
                )),
                Err(e) => Verdict::Fail(format!(
                    "the verifier saved no {}: {e}",
                    live_boot::ARTIFACT_NAME
                )),
            }
        },
    ));

    let host_key = std::fs::read_to_string(b.path(&files.host_key))?
        .trim()
        .to_string();
    let host_effects = |log: &Path, name: &str| {
        b.run(
            name,
            Command::new(&audit)
                .arg("verify-host-effects")
                .arg("--log")
                .arg(log)
                .arg("--outcomes")
                .arg(b.path(&files.host_effect_outcomes))
                .args([
                    "--host-pubkey",
                    &host_key,
                    "--pod",
                    &b.collection.effect_pod,
                ]),
        )
    };
    let effects = host_effects(&b.path(&files.host_effects), "verify-host-effects")?;
    checks.push(Check::new(
        "audit.verify_host_effects",
        if effects.success {
            Verdict::Pass(
                String::from_utf8_lossy(&effects.stdout)
                    .lines()
                    .next()
                    .unwrap_or("")
                    .to_string(),
            )
        } else {
            Verdict::Fail(effects.why())
        },
    ));

    // Node evidence, when the receipt names a document.
    let mut node_jobs = Vec::new();
    if let (NodeEvidence::Evidence { file, .. }, Some(evidence)) =
        (&b.collection.node_evidence, &evidence)
    {
        let issued = receipt_json["session"]["issued_at_micros"]
            .as_u64()
            .context("the receipt has no issue time")?;
        let receipt_time = i64::try_from(issued / 1_000_000)?;
        let document: nucleus_node_evidence::NodeEvidence = read_json(evidence)?;
        let federation = match &document.binding.federation {
            nucleus_node_evidence::Federation::NotFederated => "not-federated".to_string(),
            nucleus_node_evidence::Federation::JwksSha256(h) => hex::encode(h),
        };
        let mut c = Command::new(&audit);
        c.arg("verify-node-evidence")
            .arg("--evidence")
            .arg(evidence)
            .arg("--reference")
            .arg(&reference)
            .args(["--executor-ed25519", &signer, "--federation", &federation])
            .args(["--receipt-time", &receipt_time.to_string()]);
        for pin in &a.operator_pin {
            c.args(["--operator-pin", pin]);
        }
        let ran = b.run("verify-node-evidence", &mut c)?;
        let status = ran
            .json()
            .map(|ear| ear["submods"]["node"]["ear.status"].clone());
        checks.push(Check::new(
            "audit.verify_node_evidence",
            match &status {
                Some(s) if !s.is_null() => Verdict::Pass(format!("appraised: ear.status {s}")),
                _ => Verdict::Fail(format!("not appraised: {}", ran.why())),
            },
        ));
        let signer_bytes: [u8; 32] = hex::decode(&signer)?
            .try_into()
            .map_err(|_| anyhow::anyhow!("the signer key is not 32 bytes"))?;
        let mut operator_pins = Vec::new();
        for pin in &a.operator_pin {
            let (source, fp) = pin
                .rsplit_once('=')
                .context("--operator-pin is SOURCE=SPKI_SHA256")?;
            operator_pins.push(nucleus_node_evidence::OperatorPin {
                source: source.into(),
                ak_spki_sha256: fp.to_ascii_lowercase(),
            });
        }
        let relying_party = nucleus_node_evidence::RelyingParty {
            binding: nucleus_node_evidence::KeyBinding {
                executor_key: nucleus_node_evidence::ExecutorKey::Ed25519(signer_bytes),
                federation: document.binding.federation.clone(),
            },
            freshness: nucleus_node_evidence::FreshnessExpectation::Epoch {
                receipt_time,
                max_age_secs: 900,
                max_future_secs: 60,
            },
            trust_roots: Vec::new(),
            operator_pins,
            now: i64::try_from(now_micros()? / 1_000_000)?,
        };
        let rp = b.path("relying-party.json");
        std::fs::write(&rp, serde_json::to_vec_pretty(&relying_party)?)?;
        node_jobs.push(serde_json::json!({
            "name": "node_evidence", "kind": "node_evidence",
            "evidence": b.path(file), "reference": reference, "relying_party": rp,
        }));
        summary.platform["ear_status_audit"] = status.unwrap_or_default();
    }

    // ── Tamper controls for nucleus-audit ──
    let tampered_receipt = tampered(b, &files.receipt, |bytes| {
        json_change(bytes, |v| {
            let t = v.pointer_mut("/session/issued_at_micros")?;
            *t = serde_json::json!(t.as_u64()? + 1);
            Some(())
        })
    })?;
    checks.push(must_refuse(
        "tamper.audit.receipt",
        verify_execution(&tampered_receipt, "tamper-verify-execution"),
    ));
    let audit_tamper_seen = match checks.last().map(|c| &c.verdict) {
        Some(Verdict::Pass(why)) => Seen::Refused(why.clone()),
        Some(Verdict::Fail(_)) => Seen::Accepted(None),
        _ => Seen::CouldNotRun("the tampered receipt was not judged".into()),
    };
    let tampered_stdout = tampered(b, &files.stdout, |mut bytes| {
        bytes.extend_from_slice(b"tampered\n");
        Ok(bytes)
    })?;
    checks.push(must_refuse(
        "tamper.audit.logs",
        b.run(
            "tamper-verify-logs",
            Command::new(&audit)
                .arg("verify-logs")
                .arg("--receipt")
                .arg(&receipt)
                .arg("--expectations")
                .arg(&expectations)
                .arg("--stdout")
                .arg(&tampered_stdout)
                .arg("--stderr")
                .arg(b.path(&files.stderr)),
        ),
    ));
    let tampered_bundle = tampered(b, &files.artifacts_bundle, |bytes| {
        json_change(bytes, |v| {
            use base64::Engine as _;
            *v.pointer_mut(&format!("/artifacts/{}", live_boot::ARTIFACT_NAME))? = serde_json::json!(
                base64::engine::general_purpose::STANDARD.encode(b"live-boot-evidence tampered\n")
            );
            Some(())
        })
    })?;
    let tamper_artifacts_dir = b.root.join("tamper").join("verified-artifacts");
    checks.push(must_refuse(
        "tamper.audit.artifacts",
        b.run(
            "tamper-verify-artifacts",
            Command::new(&audit)
                .arg("verify-artifacts")
                .arg("--bundle")
                .arg(&tampered_bundle)
                .arg("--expectations")
                .arg(&expectations)
                .arg("--output-dir")
                .arg(&tamper_artifacts_dir),
        ),
    ));
    let tampered_effects = tampered(b, &files.host_effects, |bytes| {
        let text = String::from_utf8(bytes)?;
        let mut lines: Vec<String> = text.lines().map(str::to_owned).collect();
        let first = lines
            .first_mut()
            .context("the host-effect journal is empty")?;
        let changed = json_change(first.as_bytes().to_vec(), |v| {
            let s = v.pointer_mut("/authorization/subject")?;
            *s = serde_json::json!(format!("{}/tampered", s.as_str()?));
            Some(())
        })?;
        *first = serde_json::to_string(&serde_json::from_slice::<serde_json::Value>(&changed)?)?;
        Ok((lines.join("\n") + "\n").into_bytes())
    })?;
    checks.push(must_refuse(
        "tamper.audit.host_effects",
        host_effects(&tampered_effects, "tamper-verify-host-effects"),
    ));

    // ── The SDKs, on the same receipt and the same tampered copy ──
    let mut jobs = vec![
        serde_json::json!({"name": "receipt", "kind": "receipt", "receipt": receipt, "key": signer}),
        serde_json::json!({"name": "tampered", "kind": "receipt", "receipt": tampered_receipt, "key": signer}),
    ];
    jobs.extend(node_jobs.iter().cloned());
    let request = b.path("sdk-request.json");
    std::fs::write(
        &request,
        serde_json::to_vec_pretty(&serde_json::json!({"jobs": jobs}))?,
    )?;
    let js = sdk_js(root, b, &request);
    let py = sdk_py(root, b, &request);
    let mut seen_by: BTreeMap<&str, (Seen, Seen)> = BTreeMap::new();
    for (who, results) in [("js", &js), ("py", &py)] {
        let (genuine, tamper) = match results {
            Ok(r) => (
                parity::sdk(r.get("receipt")),
                parity::sdk(r.get("tampered")),
            ),
            Err(e) => (
                Seen::CouldNotRun(format!("{e:#}")),
                Seen::CouldNotRun(format!("{e:#}")),
            ),
        };
        checks.push(Check::new(
            format!("{who}.verify_receipt"),
            match &genuine {
                Seen::Accepted(_) => Verdict::Pass("verified".into()),
                Seen::Refused(how) => Verdict::Fail(how.clone()),
                Seen::CouldNotRun(why) => Verdict::CouldNotRun(why.clone()),
            },
        ));
        checks.push(Check::new(
            format!("tamper.{who}.receipt"),
            match &tamper {
                Seen::Refused(how) => Verdict::Pass(format!("refused: {how}")),
                Seen::Accepted(_) => {
                    Verdict::Fail("the verifier ACCEPTED a tampered receipt".into())
                }
                Seen::CouldNotRun(why) => Verdict::CouldNotRun(why.clone()),
            },
        ));
        seen_by.insert(who, (genuine, tamper));
    }
    let (js_seen, py_seen) = (&seen_by["js"], &seen_by["py"]);
    checks.push(Check::new(
        "parity.receipt",
        parity::agree(
            true,
            &root_hash,
            &[
                ("nucleus-audit", audit_seen),
                ("js", js_seen.0.clone()),
                ("py", py_seen.0.clone()),
            ],
        ),
    ));
    checks.push(Check::new(
        "parity.tampered_receipt",
        parity::agree(
            false,
            &root_hash,
            &[
                ("nucleus-audit", audit_tamper_seen),
                ("js", js_seen.1.clone()),
                ("py", py_seen.1.clone()),
            ],
        ),
    ));
    if !node_jobs.is_empty() {
        let status = |r: &Result<serde_json::Value>| -> Option<serde_json::Value> {
            let report = r.as_ref().ok()?.get("node_evidence")?;
            Some(match report["outcome"].as_str() {
                Some("appraised") => report["ear"]["submods"]["node"]["ear.status"].clone(),
                _ => serde_json::json!(format!("{}", report["outcome"])),
            })
        };
        let audit_status = summary.platform["ear_status_audit"].clone();
        let (js_status, py_status) = (status(&js), status(&py));
        checks.push(Check::new(
            "parity.node_evidence",
            match (js_status, py_status) {
                (Some(j), Some(p)) if j == audit_status && p == audit_status => {
                    Verdict::Pass(format!("all three: ear.status {audit_status}"))
                }
                (Some(j), Some(p)) => Verdict::Fail(format!(
                    "the verifiers disagree: nucleus-audit {audit_status}, js {j}, py {p}"
                )),
                _ => Verdict::CouldNotRun("an SDK did not appraise the evidence".into()),
            },
        ));
    }

    // ── Posture, from the receipt-bound log bytes and the console ──
    let logs_verified = matches!(
        checks
            .iter()
            .find(|c| c.name == "audit.verify_logs")
            .map(|c| &c.verdict),
        Some(Verdict::Pass(_))
    );
    let workload_text = format!(
        "{}\n{}",
        String::from_utf8_lossy(&std::fs::read(b.path(&files.stdout))?),
        String::from_utf8_lossy(&std::fs::read(b.path(&files.stderr))?)
    );
    let console =
        String::from_utf8_lossy(&std::fs::read(b.path(&files.guest_console))?).into_owned();
    for p in posture::POSTURES {
        let observed = match p.source {
            posture::Source::VerifiedWorkloadLogs if !logs_verified => posture::Observed {
                name: p.name,
                source: p.source,
                verdict: Verdict::CouldNotRun("the logs did not verify against the receipt".into()),
                lines: Vec::new(),
            },
            posture::Source::VerifiedWorkloadLogs => posture::judge(p, &workload_text),
            posture::Source::GuestConsole => posture::judge(p, &console),
        };
        checks.push(Check::new(
            format!("posture.{}", p.name),
            observed.verdict.clone(),
        ));
        summary.posture.push(observed);
    }
    Ok(())
}

/// The JS SDK runner. Only calls the SDK and prints its verdicts; every
/// decision about them is made in Rust.
const JS_RUNNER: &str = r#"import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
const [index, request] = process.argv.slice(2);
const sdk = await import(pathToFileURL(index).href);
const out = {};
for (const job of JSON.parse(readFileSync(request, "utf8")).jobs) {
  try {
    out[job.name] = job.kind === "receipt"
      ? await sdk.verifyReceipt(readFileSync(job.receipt, "utf8"), job.key)
      : await sdk.verifyNodeEvidence(new Uint8Array(readFileSync(job.evidence)), readFileSync(job.reference, "utf8"), readFileSync(job.relying_party, "utf8"));
  } catch (e) {
    out[job.name] = { outcome: "error", message: String(e?.message ?? e) };
  }
}
process.stdout.write(JSON.stringify(out));
"#;

/// The Python SDK runner, the same shape as [`JS_RUNNER`].
const PY_RUNNER: &str = r#"import json, sys
sys.path.insert(0, sys.argv[1])
import nucleus_verifier as v
out = {}
for job in json.load(open(sys.argv[2]))["jobs"]:
    try:
        if job["kind"] == "receipt":
            out[job["name"]] = json.loads(v.verify_receipt(open(job["receipt"]).read(), job["key"]))
        else:
            out[job["name"]] = json.loads(v.verify_node_evidence(open(job["evidence"], "rb").read(), open(job["reference"]).read(), open(job["relying_party"]).read()))
    except Exception as e:
        out[job["name"]] = {"outcome": "error", "message": str(e)}
print(json.dumps(out))
"#;

fn sdk_output(ran: Ran, who: &str) -> Result<serde_json::Value> {
    ensure!(ran.success, "the {who} runner failed: {}", ran.why());
    ran.json()
        .with_context(|| format!("the {who} runner printed no JSON"))
}

/// Build the wasm SDK from this tree (`wasm-pack`, as CI does) and run it.
fn sdk_js(root: &Path, b: &Bundle, request: &Path) -> Result<serde_json::Value> {
    let sdk = root.join("sdks/verifier-js");
    let built = b
        .run(
            "build-verifier-js",
            Command::new("wasm-pack")
                .args(["build", "--target", "web", "--release"])
                .current_dir(&sdk),
        )
        .context("wasm-pack is not installed")?;
    ensure!(built.success, "wasm-pack build failed: {}", built.why());
    let runner = b.outputs.join("runner.mjs");
    std::fs::write(&runner, JS_RUNNER)?;
    sdk_output(
        b.run(
            "verifier-js",
            Command::new("node")
                .arg(&runner)
                .arg(sdk.join("index.js"))
                .arg(request),
        )
        .context("node is not installed")?,
        "js",
    )
}

/// Build the Python extension from this tree and run it under `python3`.
fn sdk_py(root: &Path, b: &Bundle, request: &Path) -> Result<serde_json::Value> {
    let manifest = root.join("sdks/verifier-py/Cargo.toml");
    let built = b.run(
        "build-verifier-py",
        Command::new("cargo")
            .args([
                "build",
                "--release",
                "--locked",
                "--features",
                "pyo3/extension-module",
                "--message-format=json-render-diagnostics",
                "--manifest-path",
            ])
            .arg(&manifest),
    )?;
    ensure!(
        built.success,
        "building the Python SDK failed: {}",
        built.why()
    );
    let mut library = None;
    for line in built
        .stdout
        .split(|c| *c == b'\n')
        .filter(|l| !l.is_empty())
    {
        let message: serde_json::Value = serde_json::from_slice(line)?;
        if message["reason"] == "compiler-artifact"
            && message["target"]["name"] == "nucleus_verifier"
        {
            library = message["filenames"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(|f| f.as_str())
                .find(|f| f.ends_with(".so"))
                .map(PathBuf::from);
        }
    }
    let library = library.context("cargo built no nucleus_verifier shared library")?;
    let module_dir = b.outputs.join("python");
    std::fs::create_dir_all(&module_dir)?;
    std::fs::copy(&library, module_dir.join("nucleus_verifier.so"))?;
    let runner = b.outputs.join("runner.py");
    std::fs::write(&runner, PY_RUNNER)?;
    let result = sdk_output(
        b.run(
            "verifier-py",
            Command::new("python3")
                .arg(&runner)
                .arg(&module_dir)
                .arg(request),
        )
        .context("python3 is not installed")?,
        "py",
    );
    // A shared library is not evidence; keep the bundle to what was judged.
    let _ = std::fs::remove_dir_all(&module_dir);
    result
}
