import GkatUniquenessFrontierProofs
import GkatPullbackWitnessProofs
import GkatChainEliminationProofs

/-!
# The hard frontier: semantic UA₂ does not extract a syntactic pullback

The pullback decomposition proves a positive syntactic result: a definable guard-pullback
witness is sufficient to reduce `UA₂` to `UA₁`. A tempting converse would infer such a
witness merely from uniqueness of every productive two-state system.

That converse is false already in the standard guarded-string model. Productive two-state
systems have unique languages by well-founded induction on strings, while the genuine action
and guard from `GkatPullbackWitnessProofs` admit no syntactic pullback guard. Therefore any
successful converse must be proof-theoretic and stronger than semantic uniqueness: it must
extract a *uniform derivation/closed form*, not merely know that solutions agree.

The distinction is not peculiar to two states. `indexed_cycle_semantic_unique` below proves
semantic uniqueness for an arbitrary finite (indeed, arbitrary-indexed) productive cycle.
Thus semantic `UAₙ` and syntactic pullback-based elimination diverge at every arity.
-/

namespace GkatHardFrontier

open GkatSyntax GkatGS GkatUAIndep GkatUniqFrontier GkatPullbackWitness GkatChainElim

/-- One unfolding of an indexed guarded cycle at state `i`, with recursive languages `P`.
    This is the semantic equation `Pᵢ = bᵢ ? (eᵢ · P(next i)) : fᵢ`, abstracting only the
    recursive continuation away from expression syntax. -/
def CycleStep {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) (P : I → GS A Atom → Prop)
    (i : I) (gs : GS A Atom) : Prop :=
  (bval V (b i) gs.1 = true ∧
    ∃ l₁ l₂, gs.2 = l₁ ++ l₂ ∧ den V (e i) (gs.1, l₁) ∧
      P (next i) (lastAtom gs.1 l₁, l₂)) ∨
  (bval V (b i) gs.1 = false ∧ den V (f i) gs)

/-- A family of languages solves the whole indexed cycle. -/
def CycleSolves {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) (P : I → GS A Atom → Prop) : Prop :=
  ∀ i gs, P i gs ↔ CycleStep V next b e f P i gs

/-- The least language generated by an indexed guarded cycle. Unlike `CycleSolves`, this
    inductive presentation chooses the least fixed point directly and needs neither
    finiteness of the state space nor a productivity hypothesis. -/
inductive CycleRun {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) : I → GS A Atom → Prop where
  | exit (i : I) (gs : GS A Atom) :
      bval V (b i) gs.1 = false → den V (f i) gs → CycleRun V next b e f i gs
  | step (i : I) (a : Atom) (l₁ l₂ : List (A × Atom)) :
      bval V (b i) a = true → den V (e i) (a, l₁) →
      CycleRun V next b e f (next i) (lastAtom a l₁, l₂) →
      CycleRun V next b e f i (a, l₁ ++ l₂)

/-- The inductively generated family unfolds to exactly one application of the cycle
    functional. -/
theorem cycleRun_unfold {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) :
    CycleSolves V next b e f (CycleRun V next b e f) := by
  intro i gs
  constructor
  · intro h
    cases h with
    | exit i gs hb hf => exact Or.inr ⟨hb, hf⟩
    | step i a l₁ l₂ hb he hr => exact Or.inl ⟨hb, l₁, l₂, rfl, he, hr⟩
  · rintro (⟨hb, l₁, l₂, hs, he, hr⟩ | ⟨hb, hf⟩)
    · rcases gs with ⟨a, w⟩
      simp only at hs
      subst w
      exact .step i a l₁ l₂ hb he hr
    · exact .exit i gs hb hf

/-- **Arbitrary-index leastness.** Every pre-fixed family contains every finite run of the
    guarded cycle. This is the semantic simultaneous analogue of ordered star induction. -/
theorem cycleRun_least {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) (Q : I → GS A Atom → Prop)
    (prefixed : ∀ i gs, CycleStep V next b e f Q i gs → Q i gs) :
    ∀ i gs, CycleRun V next b e f i gs → Q i gs := by
  intro i gs h
  induction h with
  | exit i gs hb hf => exact prefixed i gs (Or.inr ⟨hb, hf⟩)
  | step i a l₁ l₂ hb he hr ih =>
      exact prefixed i (a, l₁ ++ l₂) (Or.inl ⟨hb, l₁, l₂, rfl, he, ih⟩)

/-- The one-state cycle is reified by the ordinary GKAT loop followed by its exit. This is
    the scalar base case for finite state elimination. -/
theorem cycleRun_singleton_reify {A T Atom : Type} (V : T → Atom → Bool)
    (b : BExp T) (e f : Exp A T) : ∀ gs,
    CycleRun V (fun _ : Unit => ()) (fun _ => b) (fun _ => e) (fun _ => f) () gs ↔
      den V (.seq (.wh b e) f) gs := by
  intro gs
  constructor
  · intro h
    have forward : ∀ (i : Unit) (run : GS A Atom),
        CycleRun V (fun _ : Unit => ()) (fun _ => b) (fun _ => e) (fun _ => f) i run →
          den V (.seq (.wh b e) f) run := by
      intro i run hr
      induction hr with
      | exit i run hb hf =>
          rcases run with ⟨a, w⟩
          exact ⟨[], w, rfl, InLoop.exit a hb, hf⟩
      | step i a l₁ l₂ hb he hr ih =>
          rcases ih with ⟨loop, tail, hs, hloop, hf⟩
          change l₂ = loop ++ tail at hs
          change den V (.wh b e) (lastAtom a l₁, loop) at hloop
          refine ⟨l₁ ++ loop, tail, ?_, InLoop.step a l₁ loop hb he hloop, ?_⟩
          · rw [List.append_assoc, hs]
          · rw [lastAtom_append]
            exact hf
    exact forward () gs h
  · have reverse : ∀ (run : GS A Atom), InLoop V b (den V e) run →
        ∀ tail, den V f (lastAtom run.1 run.2, tail) →
          CycleRun V (fun _ : Unit => ()) (fun _ => b) (fun _ => e) (fun _ => f) ()
            (run.1, run.2 ++ tail) := by
      intro run hloop
      induction hloop with
      | exit a hb =>
          intro tail hf
          exact CycleRun.exit () (a, tail) hb hf
      | step a body rest hb he hrest ih =>
          intro tail hf
          simp only [List.append_assoc]
          exact CycleRun.step () a body (rest ++ tail) hb he
            (ih tail (by rw [lastAtom_append] at hf; exact hf))
    rcases gs with ⟨a, w⟩
    rintro ⟨loop, tail, hs, hloop, hf⟩
    change w = loop ++ tail at hs
    subst w
    exact reverse (a, loop) hloop tail hf

/-- A syntactic reification of an indexed cycle assigns one GKAT expression to each
    control state and proves that its guarded-string language is the least cycle language.
    Constructing this object for finite `I` is the remaining finite-SCC elimination problem. -/
structure CycleReification {I A T Atom : Type} (V : T → Atom → Bool) (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) where
  expr : I → Exp A T
  correct : ∀ i gs, den V (expr i) gs ↔ CycleRun V next b e f i gs

/-- A concrete three-point cycle, used to expose the first genuinely composite-prefix
    elimination step without encoding control states as arithmetic. -/
inductive Cycle3 where
  | s0 | s1 | s2
  deriving DecidableEq, Repr

def Cycle3.next : Cycle3 → Cycle3
  | .s0 => .s1
  | .s1 => .s2
  | .s2 => .s0

/-- The scalar loop proof gives the base inhabitant of the finite-SCC reification
    interface. -/
def singletonCycleReification {A T Atom : Type} (V : T → Atom → Bool)
    (b : BExp T) (e f : Exp A T) :
    CycleReification V (fun _ : Unit => ()) (fun _ => b) (fun _ => e) (fun _ => f) where
  expr _ := .seq (.wh b e) f
  correct _ gs := (cycleRun_singleton_reify V b e f gs).symm

/-- A reification is automatically a semantic solution of the original simultaneous
    equations. -/
theorem CycleReification.solves {I A T Atom : Type} {V : T → Atom → Bool} {next : I → I}
    {b : I → BExp T} {e f : I → Exp A T} (r : CycleReification V next b e f) :
    CycleSolves V next b e f (fun i gs => den V (r.expr i) gs) := by
  intro i gs
  change den V (r.expr i) gs ↔
    CycleStep V next b e f (fun j run => den V (r.expr j) run) i gs
  rw [r.correct]
  constructor
  · intro h
    have hs := (cycleRun_unfold V next b e f i gs).mp h
    simpa only [CycleStep, r.correct] using hs
  · intro h
    apply (cycleRun_unfold V next b e f i gs).mpr
    simpa only [CycleStep, r.correct] using h

/-- **Semantic `UAₙ`, at arbitrary arity.** Two solutions of the same productive indexed
    guarded cycle coincide. No finiteness of `I` is actually needed: every recursive hop
    consumes a nonempty prefix, so induction on the finite guarded string is well-founded.
    This generalizes `two_state_semantic_uniqueness` and makes the hard-frontier diagnosis
    arity-independent. -/
theorem indexed_cycle_semantic_unique {I A T Atom : Type} (V : T → Atom → Bool)
    (next : I → I) (b : I → BExp T) (e f : I → Exp A T)
    (productive : ∀ i a, ¬ den V (e i) (a, []))
    {P Q : I → GS A Atom → Prop} (hP : CycleSolves V next b e f P)
    (hQ : CycleSolves V next b e f Q) : ∀ i gs, P i gs ↔ Q i gs := by
  have bounded : ∀ (n : Nat) (w : List (A × Atom)), w.length ≤ n →
      ∀ (i : I) (a : Atom), P i (a, w) ↔ Q i (a, w) := by
    intro n
    induction n with
    | zero =>
        intro w hw i a
        obtain rfl : w = [] := by simpa using Nat.le_zero.mp hw
        rw [hP i (a, []), hQ i (a, [])]
        simp only [CycleStep]
        constructor
        · rintro (⟨_, l₁, l₂, hs, he, _⟩ | exit)
          · obtain ⟨rfl, rfl⟩ : l₁ = [] ∧ l₂ = [] := by simpa using hs.symm
            exact absurd he (productive i a)
          · exact Or.inr exit
        · rintro (⟨_, l₁, l₂, hs, he, _⟩ | exit)
          · obtain ⟨rfl, rfl⟩ : l₁ = [] ∧ l₂ = [] := by simpa using hs.symm
            exact absurd he (productive i a)
          · exact Or.inr exit
    | succ n ih =>
        intro w hw i a
        rw [hP i (a, w), hQ i (a, w)]
        simp only [CycleStep]
        have tail_bound : ∀ l₁ l₂ : List (A × Atom), w = l₁ ++ l₂ → l₁ ≠ [] →
            l₂.length ≤ n := by
          intro l₁ l₂ hs hn
          have hlen : l₁.length + l₂.length = w.length := by rw [hs, List.length_append]
          have hpos : 0 < l₁.length := by
            cases l₁ with
            | nil => exact absurd rfl hn
            | cons _ _ => exact Nat.succ_pos _
          omega
        constructor
        · rintro (⟨hb, l₁, l₂, hs, he, hp⟩ | exit)
          · have hn : l₁ ≠ [] := by rintro rfl; exact productive i a he
            exact Or.inl ⟨hb, l₁, l₂, hs, he,
              (ih l₂ (tail_bound l₁ l₂ hs hn) (next i) (lastAtom a l₁)).mp hp⟩
          · exact Or.inr exit
        · rintro (⟨hb, l₁, l₂, hs, he, hq⟩ | exit)
          · have hn : l₁ ≠ [] := by rintro rfl; exact productive i a he
            exact Or.inl ⟨hb, l₁, l₂, hs, he,
              (ih l₂ (tail_bound l₁ l₂ hs hn) (next i) (lastAtom a l₁)).mpr hq⟩
          · exact Or.inr exit
  intro i gs
  exact bounded gs.2.length gs.2 (Nat.le_refl _) i gs.1

/-- Under productivity, the inductive least solution is also the unique solution. This
    packages the semantic target that a syntactic finite-SCC elimination theorem must
    reify as a family of GKAT expressions. -/
theorem cycleRun_unique {I A T Atom : Type} (V : T → Atom → Bool)
    (next : I → I) (b : I → BExp T) (e f : I → Exp A T)
    (productive : ∀ i a, ¬ den V (e i) (a, []))
    {P : I → GS A Atom → Prop} (hP : CycleSolves V next b e f P) :
    ∀ i gs, P i gs ↔ CycleRun V next b e f i gs :=
  indexed_cycle_semantic_unique V next b e f productive hP
    (cycleRun_unfold V next b e f)

/-- The purely syntactic deliverable for finite-state elimination: one expression per
    state, with a GKAT derivation of every simultaneous equation. -/
structure EquationalCycleSolution {I A T : Type} (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) where
  expr : I → Exp A T
  equation : ∀ i, Equiv (expr i) (.ite (b i) (.seq (e i) (expr (next i))) (f i))

/-- The certificate shape produced by finite chain elimination. Only the distinguished
    head needs a nontrivial elimination proof; all other states are reconstructed backward
    and carry their ordinary one-step equations. -/
structure HeadCycleCertificate {I A T : Type} (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) where
  head : I
  expr : I → Exp A T
  headEquation : Equiv (expr head)
    (.ite (b head) (.seq (e head) (expr (next head))) (f head))
  tailEquation : ∀ i, i ≠ head →
    Equiv (expr i) (.ite (b i) (.seq (e i) (expr (next i))) (f i))

/-- The backward-reconstruction half of finite chain synthesis. It records all state
    expressions and discharges every equation except the distinguished head. -/
structure ReconstructedCycleTail {I A T : Type} (next : I → I)
    (b : I → BExp T) (e f : I → Exp A T) where
  head : I
  expr : I → Exp A T
  equation : ∀ i, i ≠ head →
    Equiv (expr i) (.ite (b i) (.seq (e i) (expr (next i))) (f i))

/-- One non-head state in a linearized finite cycle. The list order follows `next`; the
    final link returns to the synthesized head. -/
structure ChainLink (A T : Type) where
  guard : BExp T
  body : Exp A T
  exit : Exp A T

def ChainLink.rhs {A T : Type} (link : ChainLink A T) (next : Exp A T) : Exp A T :=
  .ite link.guard (.seq link.body next) link.exit

/-- Expressions reconstructed backward from the head. For `[s₁, …, sₙ]`, the last state
    points to `head`, and every preceding state points to the next list expression. -/
def reconstructChain {A T : Type} (head : Exp A T) : List (ChainLink A T) → List (Exp A T)
  | [] => []
  | link :: links =>
      let rest := reconstructChain head links
      link.rhs (rest.head?.getD head) :: rest

/-- Proof-relevant graph of the equations generated by `reconstructChain`. -/
inductive ReconstructedChain {A T : Type} (head : Exp A T) :
    List (ChainLink A T) → List (Exp A T) → Prop where
  | nil : ReconstructedChain head [] []
  | cons (link : ChainLink A T) {links exprs}
      (tail : ReconstructedChain head links exprs) :
      ReconstructedChain head (link :: links)
        (link.rhs (exprs.head?.getD head) :: exprs)

/-- Backward folding always produces a certified reconstructed chain. -/
theorem reconstructChain_correct {A T : Type} (head : Exp A T) :
    ∀ links, ReconstructedChain head links (reconstructChain head links) := by
  intro links
  induction links with
  | nil => exact .nil
  | cons link links ih => exact .cons link ih

@[simp] theorem reconstructChain_length {A T : Type} (head : Exp A T)
    (links : List (ChainLink A T)) :
    (reconstructChain head links).length = links.length := by
  induction links with
  | nil => rfl
  | cons link links ih =>
      change Nat.succ (reconstructChain head links).length = Nat.succ links.length
      exact congrArg Nat.succ ih

/-- A reconstruction proof cannot change the number of control states. -/
theorem ReconstructedChain.length_eq {A T : Type} {head : Exp A T}
    {links : List (ChainLink A T)} {exprs : List (Exp A T)}
    (h : ReconstructedChain head links exprs) : exprs.length = links.length := by
  induction h with
  | nil => rfl
  | cons link tail ih =>
      change Nat.succ _ = Nat.succ _
      exact congrArg Nat.succ ih

/-- Numeric lookup form of the reconstruction invariant. The next expression is the next
    list entry when present and the synthesized head after the final link. -/
theorem reconstructChain_get?_equation {A T : Type} (head : Exp A T) :
    ∀ (links : List (ChainLink A T)) (k : Nat),
      (reconstructChain head links)[k]? =
        (links[k]?).map (fun link =>
          link.rhs ((reconstructChain head links)[k + 1]?.getD head)) := by
  intro links
  induction links with
  | nil => intro k; rfl
  | cons link links ih =>
      intro k
      cases k with
      | zero =>
          cases links <;> rfl
      | succ k => exact ih k

/-- A linearized cycle always has one distinguished head plus its tail links. -/
abbrev ChainState {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) := Fin (headLink :: tailLinks).length

def chainHead {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) : ChainState headLink tailLinks :=
  ⟨0, Nat.succ_pos _⟩

def chainTailState {A T : Type} {headLink : ChainLink A T}
    {tailLinks : List (ChainLink A T)} (k : Fin tailLinks.length) :
    ChainState headLink tailLinks :=
  ⟨k.val + 1, Nat.succ_lt_succ k.isLt⟩

/-- Cyclic successor on the finite linearization. -/
def chainNext {A T : Type} {headLink : ChainLink A T}
    {tailLinks : List (ChainLink A T)} (i : ChainState headLink tailLinks) :
    ChainState headLink tailLinks :=
  if h : i.val + 1 < (headLink :: tailLinks).length then ⟨i.val + 1, h⟩
  else chainHead headLink tailLinks

def chainLinkAt {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) (i : ChainState headLink tailLinks) : ChainLink A T :=
  (headLink :: tailLinks).get i

def chainGuard {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) (i : ChainState headLink tailLinks) : BExp T :=
  (chainLinkAt headLink tailLinks i).guard

def chainBody {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) (i : ChainState headLink tailLinks) : Exp A T :=
  (chainLinkAt headLink tailLinks i).body

def chainExit {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) (i : ChainState headLink tailLinks) : Exp A T :=
  (chainLinkAt headLink tailLinks i).exit

/-- Total reconstructed expression lookup, with the synthesized head at index zero. -/
def chainExprAt {A T : Type} (head : Exp A T) (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) (i : ChainState headLink tailLinks) : Exp A T :=
  (head :: reconstructChain head tailLinks).get
    ⟨i.val, by
      change i.val < Nat.succ (reconstructChain head tailLinks).length
      rw [reconstructChain_length]
      exact i.isLt⟩

theorem chainNext_of_lt {A T : Type} {headLink : ChainLink A T}
    {tailLinks : List (ChainLink A T)} (i : ChainState headLink tailLinks)
    (h : i.val + 1 < (headLink :: tailLinks).length) :
    chainNext i = ⟨i.val + 1, h⟩ := by
  unfold chainNext
  exact dif_pos h

theorem chainNext_of_not_lt {A T : Type} {headLink : ChainLink A T}
    {tailLinks : List (ChainLink A T)} (i : ChainState headLink tailLinks)
    (h : ¬ i.val + 1 < (headLink :: tailLinks).length) :
    chainNext i = chainHead headLink tailLinks := by
  unfold chainNext
  exact dif_neg h

/-- Finite-index form of `reconstructChain_get?_equation`. -/
theorem chainTailState_equation {A T : Type} (head : Exp A T)
    (headLink : ChainLink A T) (tailLinks : List (ChainLink A T))
    (k : Fin tailLinks.length) :
    chainExprAt head headLink tailLinks (chainTailState k) =
      (chainLinkAt headLink tailLinks (chainTailState k)).rhs
        (chainExprAt head headLink tailLinks (chainNext (chainTailState k))) := by
  have core := reconstructChain_get?_equation head tailLinks k.val
  have hkExpr : k.val < (reconstructChain head tailLinks).length := by
    rw [reconstructChain_length]
    exact k.isLt
  rw [List.getElem?_eq_getElem hkExpr, List.getElem?_eq_getElem k.isLt] at core
  simp only [Option.map_some, Option.some.injEq] at core
  by_cases hn : k.val + 1 < tailLinks.length
  · have hnExpr : k.val + 1 < (reconstructChain head tailLinks).length := by
      rw [reconstructChain_length]
      exact hn
    have hget : (reconstructChain head tailLinks)[k.val + 1]? =
        some ((reconstructChain head tailLinks)[k.val + 1]) :=
      List.getElem?_eq_getElem hnExpr
    rw [hget] at core
    simp only [Option.getD_some] at core
    have hs : (chainTailState (headLink := headLink) k).val + 1 <
        (headLink :: tailLinks).length := by
      change k.val + 1 + 1 < tailLinks.length + 1
      omega
    rw [chainNext_of_lt _ hs]
    change (reconstructChain head tailLinks)[k.val] =
      (tailLinks[k.val]).rhs ((reconstructChain head tailLinks)[k.val + 1])
    exact core
  · have hnExpr : (reconstructChain head tailLinks).length ≤ k.val + 1 := by
      rw [reconstructChain_length]
      exact Nat.le_of_not_gt hn
    have hnone : (reconstructChain head tailLinks)[k.val + 1]? = none :=
      List.getElem?_eq_none hnExpr
    rw [hnone] at core
    simp only [Option.getD_none] at core
    have hs : ¬ (chainTailState (headLink := headLink) k).val + 1 <
        (headLink :: tailLinks).length := by
      change ¬ k.val + 1 + 1 < tailLinks.length + 1
      omega
    rw [chainNext_of_not_lt _ hs]
    change (reconstructChain head tailLinks)[k.val] = (tailLinks[k.val]).rhs head
    exact core

/-- Any finite link list now yields the complete reconstructed-tail object expected by
    `closeIntroduction`; only the head equation remains to be supplied by elimination. -/
def reconstructedCycleTail {A T : Type} (head : Exp A T)
    (headLink : ChainLink A T) (tailLinks : List (ChainLink A T)) :
    ReconstructedCycleTail (chainNext (headLink := headLink) (tailLinks := tailLinks))
      (chainGuard headLink tailLinks) (chainBody headLink tailLinks)
      (chainExit headLink tailLinks) where
  head := chainHead headLink tailLinks
  expr := chainExprAt head headLink tailLinks
  equation i hi := by
    have hpos : 0 < i.val := by
      cases Nat.eq_zero_or_pos i.val with
      | inl hz =>
          exfalso
          apply hi
          apply Fin.ext
          simp only [chainHead]
          exact hz
      | inr hp => exact hp
    let k : Fin tailLinks.length := ⟨i.val - 1, by
      change i.val - 1 < tailLinks.length
      have hi' := i.isLt
      change i.val < tailLinks.length + 1 at hi'
      omega⟩
    have hik : i = chainTailState k := by
      apply Fin.ext
      simp only [chainTailState, k]
      omega
    rw [hik]
    change Equiv (chainExprAt head headLink tailLinks (chainTailState k))
      ((chainLinkAt headLink tailLinks (chainTailState k)).rhs
        (chainExprAt head headLink tailLinks (chainNext (chainTailState k))))
    rw [chainTailState_equation]
    exact Equiv.refl _

@[simp] theorem chainLinkAt_head {A T : Type} (headLink : ChainLink A T)
    (tailLinks : List (ChainLink A T)) :
    chainLinkAt headLink tailLinks (chainHead headLink tailLinks) = headLink := rfl

@[simp] theorem chainExprAt_head {A T : Type} (head : Exp A T)
    (headLink : ChainLink A T) (tailLinks : List (ChainLink A T)) :
    chainExprAt head headLink tailLinks (chainHead headLink tailLinks) = head := rfl

/-- Close a reconstructed tail with an arbitrary-length `Introduction` certificate for
    its head. The induction over all crossed guards is exactly `introduction_equiv`; this
    adapter preserves the reconstructed state family that the original certificate omits. -/
def ReconstructedCycleTail.closeIntroduction {I A T : Type}
    {next : I → I} {b : I → BExp T} {e f : I → Exp A T}
    (tail : ReconstructedCycleTail next b e f) (n : Nat)
    (intro : Introduction n (tail.expr tail.head)
      (.ite (b tail.head) (.seq (e tail.head) (tail.expr (next tail.head))) (f tail.head))) :
    HeadCycleCertificate next b e f where
  head := tail.head
  expr := tail.expr
  headEquation := introduction_equiv intro
  tailEquation := tail.equation

/-- Arbitrary-length finite-cycle compiler. Backward reconstruction supplies every tail
    expression, while the `Introduction n` trace supplies the sole nontrivial head equation. -/
def reconstructedChainHeadCertificate {A T : Type} (head : Exp A T)
    (headLink : ChainLink A T) (tailLinks : List (ChainLink A T)) (n : Nat)
    (intro : let tail := reconstructedCycleTail head headLink tailLinks
      Introduction n (tail.expr tail.head)
        (.ite ((chainGuard headLink tailLinks) tail.head)
          (.seq ((chainBody headLink tailLinks) tail.head)
            (tail.expr (chainNext tail.head)))
          ((chainExit headLink tailLinks) tail.head))) :
    HeadCycleCertificate (chainNext (headLink := headLink) (tailLinks := tailLinks))
      (chainGuard headLink tailLinks) (chainBody headLink tailLinks)
      (chainExit headLink tailLinks) := by
  let tail := reconstructedCycleTail head headLink tailLinks
  exact tail.closeIntroduction n intro

/-- Compile the head/tail certificate into the uniform per-state interface. This is the
    final generic step after an arbitrary `Introduction` trace has reconstructed the tail. -/
def HeadCycleCertificate.compile {I A T : Type} [DecidableEq I]
    {next : I → I} {b : I → BExp T} {e f : I → Exp A T}
    (c : HeadCycleCertificate next b e f) : EquationalCycleSolution next b e f where
  expr := c.expr
  equation i := if h : i = c.head then by
      subst i
      exact c.headEquation
    else c.tailEquation i h

/-- Uniform equational solution produced by the arbitrary finite-cycle compiler. -/
def reconstructedChainSolution {A T : Type} (head : Exp A T)
    (headLink : ChainLink A T) (tailLinks : List (ChainLink A T)) (n : Nat)
    (intro : let tail := reconstructedCycleTail head headLink tailLinks
      Introduction n (tail.expr tail.head)
        (.ite ((chainGuard headLink tailLinks) tail.head)
          (.seq ((chainBody headLink tailLinks) tail.head)
            (tail.expr (chainNext tail.head)))
          ((chainExit headLink tailLinks) tail.head))) :
    EquationalCycleSolution (chainNext (headLink := headLink) (tailLinks := tailLinks))
      (chainGuard headLink tailLinks) (chainBody headLink tailLinks)
      (chainExit headLink tailLinks) :=
  (reconstructedChainHeadCertificate head headLink tailLinks n intro).compile

/-- Equational soundness turns a syntactic cycle solution into a semantic solution. -/
theorem EquationalCycleSolution.solves {I A T Atom : Type} {V : T → Atom → Bool}
    {next : I → I} {b : I → BExp T} {e f : I → Exp A T}
    (s : EquationalCycleSolution next b e f) :
    CycleSolves V next b e f (fun i gs => den V (s.expr i) gs) := by
  intro i gs
  have h := sound V (s.equation i) gs
  simpa only [CycleStep, den_ite, den_seq] using h

/-- Consequently, any productive equational solution is a reification of the least cycle
    language. This is the semantic back end for the remaining arbitrary finite certificate
    compiler. -/
def EquationalCycleSolution.reify {I A T Atom : Type} {V : T → Atom → Bool}
    {next : I → I} {b : I → BExp T} {e f : I → Exp A T}
    (s : EquationalCycleSolution next b e f)
    (productive : ∀ i a, ¬ den V (e i) (a, [])) : CycleReification V next b e f where
  expr := s.expr
  correct := cycleRun_unique V next b e f productive s.solves

/-- End-to-end semantic reification of an enriched finite-chain certificate. -/
def HeadCycleCertificate.reify {I A T Atom : Type} [DecidableEq I]
    {V : T → Atom → Bool} {next : I → I} {b : I → BExp T} {e f : I → Exp A T}
    (c : HeadCycleCertificate next b e f)
    (productive : ∀ i a, ¬ den V (e i) (a, [])) : CycleReification V next b e f :=
  c.compile.reify productive

/-- The enriched two-state chain certificate: state `false` carries the elimination proof
    and state `true` is reconstructed definitionally. -/
def twoCycleHeadCertificate {A T : Type}
    (b0 b1 c1 : BExp T) (e0 e1 f0 f1 : Exp A T)
    (hpb : Pullback e0 b1 c1) :
    HeadCycleCertificate (fun i : Bool => !i)
      (fun i => if i then b1 else b0) (fun i => if i then e1 else e0)
      (fun i => if i then f1 else f0) := by
  let g0 : Exp A T :=
    .seq (.wh (.and c1 b0) (.seq e0 e1)) (.ite b0 (.seq e0 f1) f0)
  let g1 : Exp A T := .ite b1 (.seq e1 g0) f1
  refine ⟨false, fun i => if i then g1 else g0, ?_, ?_⟩
  · change Equiv g0 (.ite b0 (.seq e0 g1) f0)
    exact crossed_solvable_of_pullback hpb
  · intro i hi
    cases i with
    | false => exact absurd rfl hi
    | true => exact Equiv.refl g1

/-- Axiom-free syntactic compilation of a pullback-equipped two-cycle. -/
def twoCycleEquationalSolution {A T : Type}
    (b0 b1 c1 : BExp T) (e0 e1 f0 f1 : Exp A T)
    (hpb : Pullback e0 b1 c1) :
    EquationalCycleSolution (fun i : Bool => !i)
      (fun i => if i then b1 else b0) (fun i => if i then e1 else e0)
      (fun i => if i then f1 else f0) :=
  (twoCycleHeadCertificate b0 b1 c1 e0 e1 f0 f1 hpb).compile

/-- The enriched three-state certificate, with the composite-prefix derivation isolated at
    `s0` and the two reconstructed equations stored as reflexive tail steps. -/
def threeCycleHeadCertificate {A T : Type}
    (b0 b1 b2 c1 c2 : BExp T) (e0 e1 e2 f0 f1 f2 : Exp A T)
    (hpb1 : Pullback e0 b1 c1)
    (hpb2 : Pullback (.seq e0 e1) b2 c2) :
    HeadCycleCertificate Cycle3.next
      (fun i => match i with | .s0 => b0 | .s1 => b1 | .s2 => b2)
      (fun i => match i with | .s0 => e0 | .s1 => e1 | .s2 => e2)
      (fun i => match i with | .s0 => f0 | .s1 => f1 | .s2 => f2) := by
  let g0 : Exp A T :=
    .seq (.wh (.and c2 (.and c1 b0)) (.seq (.seq e0 e1) e2))
      (.ite (.and c1 b0) (.seq (.seq e0 e1) f2) (.ite b0 (.seq e0 f1) f0))
  let g2 : Exp A T := .ite b2 (.seq e2 g0) f2
  let g1 : Exp A T := .ite b1 (.seq e1 g2) f1
  let tail : ReconstructedCycleTail Cycle3.next
      (fun i => match i with | .s0 => b0 | .s1 => b1 | .s2 => b2)
      (fun i => match i with | .s0 => e0 | .s1 => e1 | .s2 => e2)
      (fun i => match i with | .s0 => f0 | .s1 => f1 | .s2 => f2) := {
    head := .s0
    expr := fun i => match i with | .s0 => g0 | .s1 => g1 | .s2 => g2
    equation := by
      intro i hi
      cases i with
      | s0 => exact absurd rfl hi
      | s1 => exact Equiv.refl g1
      | s2 => exact Equiv.refl g2 }
  exact tail.closeIntroduction 2 (threeCycleIntroduction hpb1 hpb2)

/-- Axiom-free syntactic compilation of the three-cycle, including the first pullback
    across an accumulated composite body. -/
def threeCycleEquationalSolution {A T : Type}
    (b0 b1 b2 c1 c2 : BExp T) (e0 e1 e2 f0 f1 f2 : Exp A T)
    (hpb1 : Pullback e0 b1 c1)
    (hpb2 : Pullback (.seq e0 e1) b2 c2) :
    EquationalCycleSolution Cycle3.next
      (fun i => match i with | .s0 => b0 | .s1 => b1 | .s2 => b2)
      (fun i => match i with | .s0 => e0 | .s1 => e1 | .s2 => e2)
      (fun i => match i with | .s0 => f0 | .s1 => f1 | .s2 => f2) :=
  (threeCycleHeadCertificate b0 b1 b2 c1 c2 e0 e1 e2 f0 f1 f2 hpb1 hpb2).compile

/-- Two control states can be reified when the first body transports the second guard.
    State `false` is collapsed to the standard crossed-system closed form; state `true`
    is then reconstructed by one unfolding. Productivity identifies this semantic solution
    with the inductively generated least solution. -/
def twoCycleReification {A T Atom : Type} (V : T → Atom → Bool)
    (b0 b1 c1 : BExp T) (e0 e1 f0 f1 : Exp A T)
    (hpb : Pullback e0 b1 c1)
    (productive0 : ∀ a, ¬ den V e0 (a, []))
    (productive1 : ∀ a, ¬ den V e1 (a, [])) :
    CycleReification V (fun i : Bool => !i)
      (fun i => if i then b1 else b0) (fun i => if i then e1 else e0)
      (fun i => if i then f1 else f0) := by
  have productive : ∀ (i : Bool) a, ¬ den V (if i then e1 else e0) (a, []) := by
    intro i a
    cases i with
    | false => exact productive0 a
    | true => exact productive1 a
  exact (twoCycleEquationalSolution b0 b1 c1 e0 e1 f0 f1 hpb).reify productive

/-- The three-state reification is the first case requiring a pullback across an
    accumulated body: first `e0` crosses `b1`, then `e0·e1` crosses `b2`. The remaining
    states are reconstructed by unfolding backward from the synthesized head. -/
def threeCycleReification {A T Atom : Type} (V : T → Atom → Bool)
    (b0 b1 b2 c1 c2 : BExp T) (e0 e1 e2 f0 f1 f2 : Exp A T)
    (hpb1 : Pullback e0 b1 c1)
    (hpb2 : Pullback (.seq e0 e1) b2 c2)
    (productive0 : ∀ a, ¬ den V e0 (a, []))
    (productive1 : ∀ a, ¬ den V e1 (a, []))
    (productive2 : ∀ a, ¬ den V e2 (a, [])) :
    CycleReification V Cycle3.next
      (fun i => match i with | .s0 => b0 | .s1 => b1 | .s2 => b2)
      (fun i => match i with | .s0 => e0 | .s1 => e1 | .s2 => e2)
      (fun i => match i with | .s0 => f0 | .s1 => f1 | .s2 => f2) := by
  have productive : ∀ (i : Cycle3) a, ¬ den V
      (match i with | .s0 => e0 | .s1 => e1 | .s2 => e2) (a, []) := by
    intro i a
    cases i with
    | s0 => exact productive0 a
    | s1 => exact productive1 a
    | s2 => exact productive2 a
  exact (threeCycleEquationalSolution b0 b1 b2 c1 c2 e0 e1 e2 f0 f1 f2 hpb1 hpb2).reify
    productive

/-- Semantic `UA₂` for fixed productive bodies: every pair of semantic solutions of every
    guarded two-state system agrees at both states. -/
def SemanticUA2 {A T Atom : Type} (V : T → Atom → Bool) (e₀ e₁ : Exp A T) : Prop :=
  ∀ (b₀ b₁ : BExp T) (f₀ f₁ g₀ g₁ g₀' g₁' : Exp A T),
    (∀ gs, den V g₀ gs ↔ den V (.ite b₀ (.seq e₀ g₁) f₀) gs) →
    (∀ gs, den V g₁ gs ↔ den V (.ite b₁ (.seq e₁ g₀) f₁) gs) →
    (∀ gs, den V g₀' gs ↔ den V (.ite b₀ (.seq e₀ g₁') f₀) gs) →
    (∀ gs, den V g₁' gs ↔ den V (.ite b₁ (.seq e₁ g₀') f₁) gs) →
    (∀ gs, den V g₀ gs ↔ den V g₀' gs) ∧ (∀ gs, den V g₁ gs ↔ den V g₁' gs)

/-- The standard model validates semantic `UA₂` for two genuine actions: actions consume
    one symbol, so the existing length induction applies. -/
theorem semanticUA2_action :
    SemanticUA2 GkatPullbackWitness.V0 (Exp.act () : Exp Unit Unit) (Exp.act ()) := by
  intro b₀ b₁ f₀ f₁ g₀ g₁ g₀' g₁' h₀ h₁ h₀' h₁'
  refine two_state_semantic_uniqueness GkatPullbackWitness.V0
    (e0 := (Exp.act () : Exp Unit Unit)) (e1 := (Exp.act () : Exp Unit Unit))
    ?_ ?_ h₀ h₁ h₀' h₁'
  · intro a; simp [den]
  · intro a; simp [den]

/-- **Semantic uniqueness does not manufacture a pullback.** The left conjunct is full
    semantic `UA₂` for the productive action bodies; the right conjunct says that the first
    action cannot transport the genuine guard to any syntactic test. -/
theorem semanticUA2_without_pullback :
    SemanticUA2 GkatPullbackWitness.V0 (Exp.act () : Exp Unit Unit) (Exp.act ()) ∧
      ¬ ∃ c : BExp Unit, Pullback (Exp.act () : Exp Unit Unit) (.prim ()) c :=
  ⟨semanticUA2_action, no_pullback_witness⟩

/-- The naïve converse, stated directly as an extractor implication, is refuted. -/
theorem no_semantic_UA2_pullback_extraction :
    ¬ (SemanticUA2 GkatPullbackWitness.V0 (Exp.act () : Exp Unit Unit) (Exp.act ()) →
      ∃ c : BExp Unit, Pullback (Exp.act () : Exp Unit Unit) (.prim ()) c) := by
  intro extract
  exact no_pullback_witness (extract semanticUA2_action)

#print axioms semanticUA2_action
#print axioms cycleRun_unfold
#print axioms cycleRun_least
#print axioms cycleRun_singleton_reify
#print axioms singletonCycleReification
#print axioms CycleReification.solves
#print axioms indexed_cycle_semantic_unique
#print axioms cycleRun_unique
#print axioms EquationalCycleSolution.solves
#print axioms EquationalCycleSolution.reify
#print axioms HeadCycleCertificate.compile
#print axioms HeadCycleCertificate.reify
#print axioms ReconstructedCycleTail.closeIntroduction
#print axioms reconstructChain_correct
#print axioms reconstructChain_length
#print axioms ReconstructedChain.length_eq
#print axioms reconstructChain_get?_equation
#print axioms chainNext_of_lt
#print axioms chainNext_of_not_lt
#print axioms chainTailState_equation
#print axioms reconstructedCycleTail
#print axioms reconstructedChainHeadCertificate
#print axioms reconstructedChainSolution
#print axioms twoCycleHeadCertificate
#print axioms threeCycleHeadCertificate
#print axioms twoCycleEquationalSolution
#print axioms threeCycleEquationalSolution
#print axioms twoCycleReification
#print axioms threeCycleReification
#print axioms semanticUA2_without_pullback
#print axioms no_semantic_UA2_pullback_extraction

end GkatHardFrontier
