import PortcullisCore.Types
import PortcullisCore.CoreFuns
import Mathlib.Order.Heyting.Basic

/-!
# HeytingAlgebra + Function Correspondence for Aeneas-Generated CapabilityLevel

Proves two things about the Aeneas-generated `portcullis_core.CapabilityLevel`:

1. **Algebraic structure**: The type is a `HeytingAlgebra` (LinearOrder + HImp).
2. **Function correspondence**: The Aeneas-generated monadic `meet` function
   (translated from Rust MIR) computes the same result as the lattice `inf`.

Together, these connect the Lean type-checker's algebraic verification to the
actual Rust code's behavior via the Aeneas translation pipeline.

All proofs discharge via `decide`/`simp` over the 3-element type.
No SMT oracle, no Z3 — kernel-checked by the Lean 4 type-checker.
-/

open portcullis_core

-- Extensionality for CapabilityLattice.
-- Types.lean is auto-generated by Aeneas and does not carry @[ext], so we
-- register the theorem here. Without it, `ext` in the HeytingAlgebra proof
-- (himp_bot) has no applicable extensionality theorem to invoke.
@[ext]
theorem CapabilityLattice.ext {a b : CapabilityLattice}
    (h1  : a.read_files  = b.read_files)  (h2  : a.write_files = b.write_files)
    (h3  : a.edit_files  = b.edit_files)  (h4  : a.run_bash    = b.run_bash)
    (h5  : a.glob_search = b.glob_search) (h6  : a.grep_search = b.grep_search)
    (h7  : a.web_search  = b.web_search)  (h8  : a.web_fetch   = b.web_fetch)
    (h9  : a.git_commit  = b.git_commit)  (h10 : a.git_push    = b.git_push)
    (h11 : a.create_pr   = b.create_pr)   (h12 : a.manage_pods = b.manage_pods)
    (h13 : a.spawn_agent = b.spawn_agent) : a = b := by
  cases a; cases b; simp_all

namespace PortcullisCoreBridge

-- ═══════════════════════════════════════════════════════════════════════
-- Natural number encoding (matching Rust #[repr(u8)] discriminants)
-- ═══════════════════════════════════════════════════════════════════════

def toNat : CapabilityLevel → Nat
  | .Never   => 0
  | .LowRisk => 1
  | .Always  => 2

theorem toNat_injective : Function.Injective toNat := by
  intro a b h
  cases a <;> cases b <;> first | rfl | (simp [toNat] at h)

-- ═══════════════════════════════════════════════════════════════════════
-- DecidableEq
-- ═══════════════════════════════════════════════════════════════════════

instance : DecidableEq CapabilityLevel :=
  fun a b => match a, b with
  | .Never, .Never => isTrue rfl
  | .Never, .LowRisk => isFalse (by intro h; cases h)
  | .Never, .Always => isFalse (by intro h; cases h)
  | .LowRisk, .Never => isFalse (by intro h; cases h)
  | .LowRisk, .LowRisk => isTrue rfl
  | .LowRisk, .Always => isFalse (by intro h; cases h)
  | .Always, .Never => isFalse (by intro h; cases h)
  | .Always, .LowRisk => isFalse (by intro h; cases h)
  | .Always, .Always => isTrue rfl

-- ═══════════════════════════════════════════════════════════════════════
-- LE, LT, Decidable instances
-- ═══════════════════════════════════════════════════════════════════════

instance instLE : LE CapabilityLevel where
  le a b := toNat a ≤ toNat b

instance instLT : LT CapabilityLevel where
  lt a b := toNat a < toNat b

instance instDecidableLE : DecidableRel (α := CapabilityLevel) (· ≤ ·) :=
  fun a b => inferInstanceAs (Decidable (toNat a ≤ toNat b))

instance instDecidableLT : DecidableRel (α := CapabilityLevel) (· < ·) :=
  fun a b => inferInstanceAs (Decidable (toNat a < toNat b))

-- ═══════════════════════════════════════════════════════════════════════
-- Preorder → PartialOrder → LinearOrder
-- ═══════════════════════════════════════════════════════════════════════

instance instPreorder : Preorder CapabilityLevel where
  le_refl a := Nat.le_refl _
  le_trans _ _ _ h1 h2 := Nat.le_trans h1 h2
  lt_iff_le_not_ge a b := Nat.lt_iff_le_not_le

instance instPartialOrder : PartialOrder CapabilityLevel where
  le_antisymm a b h1 h2 := toNat_injective (Nat.le_antisymm h1 h2)

instance instLinearOrder : LinearOrder CapabilityLevel where
  le_total a b := Nat.le_total _ _
  toDecidableLE := instDecidableLE

-- ═══════════════════════════════════════════════════════════════════════
-- Bounded lattice (⊥ = Never, ⊤ = Always)
-- ═══════════════════════════════════════════════════════════════════════

theorem le_always (a : CapabilityLevel) : a ≤ .Always := by cases a <;> decide
theorem never_le (a : CapabilityLevel) : .Never ≤ a := by cases a <;> decide

instance instBot : Bot CapabilityLevel := ⟨.Never⟩
instance instTop : Top CapabilityLevel := ⟨.Always⟩

instance instBoundedOrder : BoundedOrder CapabilityLevel where
  bot_le := never_le
  le_top := le_always

-- ═══════════════════════════════════════════════════════════════════════
-- Heyting implication and complement
-- ═══════════════════════════════════════════════════════════════════════

instance instHImp : HImp CapabilityLevel where
  himp a b := if a ≤ b then .Always else b

instance instCompl : Compl CapabilityLevel where
  compl a := if a ≤ (⊥ : CapabilityLevel) then .Always else .Never

-- ═══════════════════════════════════════════════════════════════════════
-- HeytingAlgebra axioms
-- ═══════════════════════════════════════════════════════════════════════

theorem le_himp_iff (a b c : CapabilityLevel) :
    a ≤ b ⇨ c ↔ a ⊓ b ≤ c := by
  cases a <;> cases b <;> cases c <;> decide

theorem himp_bot (a : CapabilityLevel) :
    a ⇨ (⊥ : CapabilityLevel) = aᶜ := by
  cases a <;> decide

-- ═══════════════════════════════════════════════════════════════════════
-- The HeytingAlgebra instance
-- ═══════════════════════════════════════════════════════════════════════

instance instGeneralizedHeytingAlgebra : GeneralizedHeytingAlgebra CapabilityLevel where
  le_top  := le_always
  le_himp_iff a b c := le_himp_iff a b c

instance instHeytingAlgebra : HeytingAlgebra CapabilityLevel where
  bot_le  := never_le
  himp_bot := himp_bot

-- ═══════════════════════════════════════════════════════════════════════
-- Function correspondence: Rust meet() = lattice inf
--
-- The Aeneas-generated CapabilityLevel.meet (from Funs.lean) calls
-- PartialOrd::le and returns the smaller element — this is exactly
-- the lattice inf operation. We prove this correspondence, closing
-- the loop between the Rust implementation and the algebraic proof.
-- ═══════════════════════════════════════════════════════════════════════

open Aeneas.Std (Result)

/-- The Aeneas-generated `meet` never fails — it always returns `ok`. -/
theorem meet_never_fails (a b : CapabilityLevel) :
    ∃ r, portcullis_core.CapabilityLevel.meet a b = .ok r := by
  cases a <;> cases b <;> exact ⟨_, rfl⟩

/-- The Aeneas-generated `meet` computes the lattice inf (min).
    This connects the Rust implementation to the algebraic structure. -/
theorem meet_eq_inf (a b : CapabilityLevel) :
    portcullis_core.CapabilityLevel.meet a b = .ok (a ⊓ b) := by
  cases a <;> cases b <;> rfl

/-- The Aeneas-generated `join` never fails. -/
theorem join_never_fails (a b : CapabilityLevel) :
    ∃ r, portcullis_core.CapabilityLevel.join a b = .ok r := by
  cases a <;> cases b <;> exact ⟨_, rfl⟩

/-- The Aeneas-generated `join` computes the lattice sup (max). -/
theorem join_eq_sup (a b : CapabilityLevel) :
    portcullis_core.CapabilityLevel.join a b = .ok (a ⊔ b) := by
  cases a <;> cases b <;> rfl

/-- The Aeneas-generated `implies` computes the Heyting implication. -/
theorem implies_eq_himp (a b : CapabilityLevel) :
    portcullis_core.CapabilityLevel.implies a b = .ok (a ⇨ b) := by
  cases a <;> cases b <;> rfl

-- ═══════════════════════════════════════════════════════════════════════
-- Complement correspondence
-- ═══════════════════════════════════════════════════════════════════════

/-- The Aeneas-generated `complement` never fails. -/
theorem complement_never_fails (a : CapabilityLevel) :
    ∃ r, portcullis_core.CapabilityLevel.complement a = .ok r := by
  cases a <;> exact ⟨_, rfl⟩

/-- The Aeneas-generated `complement` computes the lattice complement. -/
theorem complement_eq_compl (a : CapabilityLevel) :
    portcullis_core.CapabilityLevel.complement a = .ok aᶜ := by
  cases a <;> rfl

/-- The Aeneas-generated `leq` never fails. -/
theorem leq_never_fails (a b : CapabilityLevel) :
    ∃ r, portcullis_core.CapabilityLevel.leq a b = .ok r := by
  cases a <;> cases b <;> exact ⟨_, rfl⟩

/-- The Aeneas-generated `leq` computes the lattice ≤. -/
theorem leq_eq_le (a b : CapabilityLevel) :
    portcullis_core.CapabilityLevel.leq a b = .ok (decide (a ≤ b)) := by
  cases a <;> cases b <;> rfl

-- ═══════════════════════════════════════════════════════════════════════
-- Product lattice: CapabilityLattice is a HeytingAlgebra
--
-- CapabilityLattice is a structure of 13 CapabilityLevel fields.
-- Since CapabilityLevel is a HeytingAlgebra, the product inherits the
-- structure pointwise. We build up the full Mathlib typeclass chain:
--
--   LE → Preorder → PartialOrder
--   Inf → SemilatticeInf ─┐
--   Sup → SemilatticeSup ─┴→ Lattice
--   Bot → OrderBot ─┐
--   Top → OrderTop ─┴→ BoundedOrder
--   HImp → GeneralizedHeytingAlgebra
--   Compl → HeytingAlgebra
--
-- Every axiom reduces to the component-level CapabilityLevel proof.
-- No SMT oracle, no Z3 — all kernel-checked by Lean 4.
-- ═══════════════════════════════════════════════════════════════════════

namespace ProductLattice

-- ─── Pointwise operations (as raw functions) ─────────────────────────

private def latticeLE (a b : CapabilityLattice) : Prop :=
  a.read_files ≤ b.read_files ∧ a.write_files ≤ b.write_files ∧
  a.edit_files ≤ b.edit_files ∧ a.run_bash ≤ b.run_bash ∧
  a.glob_search ≤ b.glob_search ∧ a.grep_search ≤ b.grep_search ∧
  a.web_search ≤ b.web_search ∧ a.web_fetch ≤ b.web_fetch ∧
  a.git_commit ≤ b.git_commit ∧ a.git_push ≤ b.git_push ∧
  a.create_pr ≤ b.create_pr ∧ a.manage_pods ≤ b.manage_pods ∧
  a.spawn_agent ≤ b.spawn_agent

private def latticeInf (a b : CapabilityLattice) : CapabilityLattice := {
  read_files := a.read_files ⊓ b.read_files
  write_files := a.write_files ⊓ b.write_files
  edit_files := a.edit_files ⊓ b.edit_files
  run_bash := a.run_bash ⊓ b.run_bash
  glob_search := a.glob_search ⊓ b.glob_search
  grep_search := a.grep_search ⊓ b.grep_search
  web_search := a.web_search ⊓ b.web_search
  web_fetch := a.web_fetch ⊓ b.web_fetch
  git_commit := a.git_commit ⊓ b.git_commit
  git_push := a.git_push ⊓ b.git_push
  create_pr := a.create_pr ⊓ b.create_pr
  manage_pods := a.manage_pods ⊓ b.manage_pods
  spawn_agent := a.spawn_agent ⊓ b.spawn_agent
}

private def latticeSup (a b : CapabilityLattice) : CapabilityLattice := {
  read_files := a.read_files ⊔ b.read_files
  write_files := a.write_files ⊔ b.write_files
  edit_files := a.edit_files ⊔ b.edit_files
  run_bash := a.run_bash ⊔ b.run_bash
  glob_search := a.glob_search ⊔ b.glob_search
  grep_search := a.grep_search ⊔ b.grep_search
  web_search := a.web_search ⊔ b.web_search
  web_fetch := a.web_fetch ⊔ b.web_fetch
  git_commit := a.git_commit ⊔ b.git_commit
  git_push := a.git_push ⊔ b.git_push
  create_pr := a.create_pr ⊔ b.create_pr
  manage_pods := a.manage_pods ⊔ b.manage_pods
  spawn_agent := a.spawn_agent ⊔ b.spawn_agent
}

private def latticeBot : CapabilityLattice := {
  read_files := ⊥, write_files := ⊥, edit_files := ⊥,
  run_bash := ⊥, glob_search := ⊥, grep_search := ⊥,
  web_search := ⊥, web_fetch := ⊥, git_commit := ⊥,
  git_push := ⊥, create_pr := ⊥, manage_pods := ⊥,
  spawn_agent := ⊥
}

private def latticeTop : CapabilityLattice := {
  read_files := ⊤, write_files := ⊤, edit_files := ⊤,
  run_bash := ⊤, glob_search := ⊤, grep_search := ⊤,
  web_search := ⊤, web_fetch := ⊤, git_commit := ⊤,
  git_push := ⊤, create_pr := ⊤, manage_pods := ⊤,
  spawn_agent := ⊤
}

private def latticeHImp (a b : CapabilityLattice) : CapabilityLattice := {
  read_files := a.read_files ⇨ b.read_files
  write_files := a.write_files ⇨ b.write_files
  edit_files := a.edit_files ⇨ b.edit_files
  run_bash := a.run_bash ⇨ b.run_bash
  glob_search := a.glob_search ⇨ b.glob_search
  grep_search := a.grep_search ⇨ b.grep_search
  web_search := a.web_search ⇨ b.web_search
  web_fetch := a.web_fetch ⇨ b.web_fetch
  git_commit := a.git_commit ⇨ b.git_commit
  git_push := a.git_push ⇨ b.git_push
  create_pr := a.create_pr ⇨ b.create_pr
  manage_pods := a.manage_pods ⇨ b.manage_pods
  spawn_agent := a.spawn_agent ⇨ b.spawn_agent
}

private def latticeCompl (a : CapabilityLattice) : CapabilityLattice := {
  read_files := a.read_filesᶜ, write_files := a.write_filesᶜ,
  edit_files := a.edit_filesᶜ, run_bash := a.run_bashᶜ,
  glob_search := a.glob_searchᶜ, grep_search := a.grep_searchᶜ,
  web_search := a.web_searchᶜ, web_fetch := a.web_fetchᶜ,
  git_commit := a.git_commitᶜ, git_push := a.git_pushᶜ,
  create_pr := a.create_prᶜ, manage_pods := a.manage_podsᶜ,
  spawn_agent := a.spawn_agentᶜ
}

-- ─── Full HeytingAlgebra instance (single definition) ────────────────
--
-- We define the entire HeytingAlgebra in one `where` block to avoid
-- instance chain mismatches between LE, PartialOrder, SemilatticeInf.

-- Increase heartbeats for the 13-field product lattice proofs (#798).
-- The `simp only` in le_himp_iff needs more reduction steps than the default 200000.
set_option maxHeartbeats 800000 in
instance instHeytingAlgebra : HeytingAlgebra CapabilityLattice where
  le := latticeLE
  lt a b := latticeLE a b ∧ ¬latticeLE b a
  inf := latticeInf
  sup := latticeSup
  bot := latticeBot
  top := latticeTop
  himp := latticeHImp
  compl := latticeCompl
  le_refl a :=
    ⟨le_refl _, le_refl _, le_refl _, le_refl _, le_refl _, le_refl _,
     le_refl _, le_refl _, le_refl _, le_refl _, le_refl _, le_refl _,
     le_refl _⟩
  le_trans a b c hab hbc :=
    ⟨le_trans hab.1 hbc.1, le_trans hab.2.1 hbc.2.1,
     le_trans hab.2.2.1 hbc.2.2.1, le_trans hab.2.2.2.1 hbc.2.2.2.1,
     le_trans hab.2.2.2.2.1 hbc.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.1 hbc.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.2.2.1,
     le_trans hab.2.2.2.2.2.2.2.2.2.2.2.2 hbc.2.2.2.2.2.2.2.2.2.2.2.2⟩
  lt_iff_le_not_ge _ _ := Iff.rfl
  le_antisymm a b hab hba := by
    have e1 := le_antisymm hab.1 hba.1
    have e2 := le_antisymm hab.2.1 hba.2.1
    have e3 := le_antisymm hab.2.2.1 hba.2.2.1
    have e4 := le_antisymm hab.2.2.2.1 hba.2.2.2.1
    have e5 := le_antisymm hab.2.2.2.2.1 hba.2.2.2.2.1
    have e6 := le_antisymm hab.2.2.2.2.2.1 hba.2.2.2.2.2.1
    have e7 := le_antisymm hab.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.1
    have e8 := le_antisymm hab.2.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.2.1
    have e9 := le_antisymm hab.2.2.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.2.2.1
    have e10 := le_antisymm hab.2.2.2.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.2.2.2.1
    have e11 := le_antisymm hab.2.2.2.2.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.2.2.2.2.1
    have e12 := le_antisymm hab.2.2.2.2.2.2.2.2.2.2.2.1 hba.2.2.2.2.2.2.2.2.2.2.2.1
    have e13 := le_antisymm hab.2.2.2.2.2.2.2.2.2.2.2.2 hba.2.2.2.2.2.2.2.2.2.2.2.2
    cases a; cases b; simp_all
  inf_le_left a b :=
    ⟨inf_le_left, inf_le_left, inf_le_left, inf_le_left,
     inf_le_left, inf_le_left, inf_le_left, inf_le_left,
     inf_le_left, inf_le_left, inf_le_left, inf_le_left,
     inf_le_left⟩
  inf_le_right a b :=
    ⟨inf_le_right, inf_le_right, inf_le_right, inf_le_right,
     inf_le_right, inf_le_right, inf_le_right, inf_le_right,
     inf_le_right, inf_le_right, inf_le_right, inf_le_right,
     inf_le_right⟩
  le_inf a b c hab hac :=
    ⟨le_inf hab.1 hac.1, le_inf hab.2.1 hac.2.1,
     le_inf hab.2.2.1 hac.2.2.1, le_inf hab.2.2.2.1 hac.2.2.2.1,
     le_inf hab.2.2.2.2.1 hac.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.1 hac.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.2.2.2.2.1 hac.2.2.2.2.2.2.2.2.2.2.2.1,
     le_inf hab.2.2.2.2.2.2.2.2.2.2.2.2 hac.2.2.2.2.2.2.2.2.2.2.2.2⟩
  le_sup_left a b :=
    ⟨le_sup_left, le_sup_left, le_sup_left, le_sup_left,
     le_sup_left, le_sup_left, le_sup_left, le_sup_left,
     le_sup_left, le_sup_left, le_sup_left, le_sup_left,
     le_sup_left⟩
  le_sup_right a b :=
    ⟨le_sup_right, le_sup_right, le_sup_right, le_sup_right,
     le_sup_right, le_sup_right, le_sup_right, le_sup_right,
     le_sup_right, le_sup_right, le_sup_right, le_sup_right,
     le_sup_right⟩
  sup_le a b c hab hbc :=
    ⟨sup_le hab.1 hbc.1, sup_le hab.2.1 hbc.2.1,
     sup_le hab.2.2.1 hbc.2.2.1, sup_le hab.2.2.2.1 hbc.2.2.2.1,
     sup_le hab.2.2.2.2.1 hbc.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.1 hbc.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.2.2.2.2.1 hbc.2.2.2.2.2.2.2.2.2.2.2.1,
     sup_le hab.2.2.2.2.2.2.2.2.2.2.2.2 hbc.2.2.2.2.2.2.2.2.2.2.2.2⟩
  bot_le a :=
    ⟨bot_le, bot_le, bot_le, bot_le, bot_le, bot_le,
     bot_le, bot_le, bot_le, bot_le, bot_le, bot_le,
     bot_le⟩
  le_top a :=
    ⟨le_top, le_top, le_top, le_top, le_top, le_top,
     le_top, le_top, le_top, le_top, le_top, le_top,
     le_top⟩
  le_himp_iff a b c := by
    show latticeLE a (latticeHImp b c) ↔ latticeLE (latticeInf a b) c
    simp only [latticeLE, latticeHImp, latticeInf]
    constructor
    · intro ⟨h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13⟩
      exact ⟨(PortcullisCoreBridge.le_himp_iff _ _ _).mp h1,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h2,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h3,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h4,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h5,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h6,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h7,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h8,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h9,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h10,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h11,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h12,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mp h13⟩
    · intro ⟨h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13⟩
      exact ⟨(PortcullisCoreBridge.le_himp_iff _ _ _).mpr h1,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h2,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h3,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h4,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h5,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h6,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h7,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h8,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h9,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h10,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h11,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h12,
             (PortcullisCoreBridge.le_himp_iff _ _ _).mpr h13⟩
  himp_bot a := by
    show latticeHImp a latticeBot = latticeCompl a
    simp only [latticeHImp, latticeBot, latticeCompl]
    ext <;> exact PortcullisCoreBridge.himp_bot _

end ProductLattice

-- ═══════════════════════════════════════════════════════════════════════
-- Product lattice function correspondence
--
-- The Aeneas-generated CapabilityLattice.meet/join/implies call
-- CapabilityLevel.meet/join/implies pointwise. Since we proved those
-- equal the lattice inf/sup/himp, the product operations compose.
-- ═══════════════════════════════════════════════════════════════════════

open ProductLattice in
/-- The Aeneas-generated `CapabilityLattice.meet` computes pointwise inf.
    Connects the Rust implementation to the algebraic structure. -/
theorem lattice_meet_eq_inf (a b : CapabilityLattice) :
    portcullis_core.CapabilityLattice.meet a b = .ok (a ⊓ b) := by
  show _ = Result.ok (latticeInf a b)
  simp [portcullis_core.CapabilityLattice.meet, meet_eq_inf, latticeInf]

open ProductLattice in
/-- The Aeneas-generated `CapabilityLattice.join` computes pointwise sup. -/
theorem lattice_join_eq_sup (a b : CapabilityLattice) :
    portcullis_core.CapabilityLattice.join a b = .ok (a ⊔ b) := by
  show _ = Result.ok (latticeSup a b)
  simp [portcullis_core.CapabilityLattice.join, join_eq_sup, latticeSup]

open ProductLattice in
/-- The Aeneas-generated `CapabilityLattice.implies` computes pointwise himp. -/
theorem lattice_implies_eq_himp (a b : CapabilityLattice) :
    portcullis_core.CapabilityLattice.implies a b = .ok (a ⇨ b) := by
  show _ = Result.ok (latticeHImp a b)
  simp [portcullis_core.CapabilityLattice.implies, implies_eq_himp, latticeHImp]

open ProductLattice in
/-- The Aeneas-generated `CapabilityLattice.bottom` is the lattice ⊥. -/
theorem lattice_bottom_eq_bot :
    portcullis_core.CapabilityLattice.bottom = .ok ⊥ := by
  show _ = Result.ok latticeBot
  simp [portcullis_core.CapabilityLattice.bottom, latticeBot]
  constructor <;> rfl

open ProductLattice in
/-- The Aeneas-generated `CapabilityLattice.top` is the lattice ⊤. -/
theorem lattice_top_eq_top :
    portcullis_core.CapabilityLattice.top = .ok ⊤ := by
  show _ = Result.ok latticeTop
  simp [portcullis_core.CapabilityLattice.top, latticeTop]
  constructor <;> rfl

-- ═══════════════════════════════════════════════════════════════════════
-- MONOTONICITY — the core safety claim (VC-001)
--
-- Authority can only tighten: meet(current, restriction) ≤ current.
-- This is the mathematical foundation of "permissions never escalate."
-- ═══════════════════════════════════════════════════════════════════════

/-- Meet is deflationary on CapabilityLevel: a ⊓ b ≤ a. -/
theorem meet_deflationary (a b : CapabilityLevel) : a ⊓ b ≤ a := inf_le_left

open ProductLattice in
/-- **The 13-dimensional proof that permissions never escalate.**
    For all 13 capability dimensions: (policy ⊓ session).field ≤ policy.field. -/
theorem lattice_meet_deflationary_left (a b : CapabilityLattice) :
    (a ⊓ b) ≤ a := by
  show latticeLE (latticeInf a b) a
  simp only [latticeLE, latticeInf]
  exact ⟨inf_le_left, inf_le_left, inf_le_left, inf_le_left,
         inf_le_left, inf_le_left, inf_le_left, inf_le_left,
         inf_le_left, inf_le_left, inf_le_left, inf_le_left,
         inf_le_left⟩

open ProductLattice in
/-- Meet is deflationary on the right. -/
theorem lattice_meet_deflationary_right (a b : CapabilityLattice) :
    (a ⊓ b) ≤ b := by
  show latticeLE (latticeInf a b) b
  simp only [latticeLE, latticeInf]
  exact ⟨inf_le_right, inf_le_right, inf_le_right, inf_le_right,
         inf_le_right, inf_le_right, inf_le_right, inf_le_right,
         inf_le_right, inf_le_right, inf_le_right, inf_le_right,
         inf_le_right⟩

open ProductLattice in
/-- Meet is idempotent: a ⊓ a = a. Applying the same policy twice is a no-op. -/
theorem lattice_meet_idempotent (a : CapabilityLattice) : a ⊓ a = a := by
  have h1 : (a ⊓ a) ≤ a := lattice_meet_deflationary_left a a
  have h2 : a ≤ (a ⊓ a) := by
    show latticeLE a (latticeInf a a)
    simp only [latticeLE, latticeInf]
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> exact le_inf (le_refl _) (le_refl _)
  exact le_antisymm h1 h2

end PortcullisCoreBridge
