#!/usr/bin/env python3
"""The `test-*` shard gates, DERIVED: scopes from cargo's dependency graph, never written by hand.

    scripts/gatehouse-test-shards.py            rewrite .gatehouse/gates/test-*.json and the
                                                generated block of .gatehouse/pipeline.writ
    scripts/gatehouse-test-shards.py --check    exit 1 if either differs from what is committed

The shard layout is `.gatehouse/test-shards.json`. Each shard names the packages whose tests it
runs; one shard may say `"rest": true` and takes every member no other shard names, so a new crate
lands in a shard without anyone remembering to put it there. Every member is in exactly one shard,
and the generator refuses a layout where that is not so.

A shard's scope is the union of
  * the WORKSPACE inputs every cargo invocation reads: the root manifest, Cargo.lock, the toolchain
    file, .cargo/** and .config/** (nextest's own configuration), and EVERY member's Cargo.toml --
    cargo loads the whole workspace to resolve one package, `--locked` holds that resolve to
    Cargo.lock, and with workspace feature unification every manifest can change what a selected
    package is compiled with;
  * the directory of every member its packages' tests compile: the packages themselves and their
    workspace-internal dependency closure (`cargo metadata`: normal and build dependencies
    transitively, dev-dependencies at the root only, because a dependency's dev-dependencies are
    never built);
  * the fixtures its tests read outside those directories, declared per package in the layout
    with the measurement that found them (strace of every test process, rustc dep-info and every
    build script's rerun-if-changed, nucleus 2fc73eda);
  * for a shard whose closure holds nucleus-verifier-service, the verifier SDK's own inputs and its
    path dependencies, because step 0 builds the SDK that crate's build script embeds.
A shard that runs a test binary reading the whole repository says `"scope": "**"`.

The pod sees exactly this selection (the lane MATERIALIZES the scope), so an under-declared read
is a file that is not there: the shard fails, it does not pass.
"""
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LAYOUT = ROOT / ".gatehouse/test-shards.json"
WRIT = ROOT / ".gatehouse/pipeline.writ"
BEGIN = "-- BEGIN generated by scripts/gatehouse-test-shards.py: edit .gatehouse/test-shards.json, not this block"
END = "-- END generated test shards"

WORKSPACE_INPUTS = ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml", ".cargo/**", ".config/**",
                    "crates/*/Cargo.toml", "scripts/test-shard.py"]
SDK_CRATE = "nucleus-verifier-service"
SDK_INPUTS = ["scripts/gatehouse-verifier-sdk.sh", "sdks/verifier-js/Cargo.toml",
              "sdks/verifier-js/Cargo.lock", "sdks/verifier-js/package.json",
              "sdks/verifier-js/index.js", "sdks/verifier-js/index.d.ts", "sdks/verifier-js/src/**",
              "sdks/verifier-js/test/**", "sdks/verifier-js/tests/**",
              "sdks/verifier-js/demo-fixtures/**"]
WRITES = ["target/**", "sdks/verifier-js/pkg/**", "sdks/verifier-js/target/**"]
# What scripts/test-shard.py writes for a member outside the selection, and nothing else.
STUB_WRITES = ["crates/*/src/lib.rs", "crates/*/src/main.rs", "crates/*/src/bin/*"]
NEXTEST = ["cargo", "nextest", "run", "--offline", "--locked", "--all-features", "--no-fail-fast",
           "--no-tests=fail"]


def metadata(manifest="Cargo.toml"):
    out = subprocess.run(["cargo", "metadata", "--offline", "--no-deps", "--format-version", "1",
                          "--manifest-path", str(ROOT / manifest)],
                         check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def members(meta):
    root = meta["workspace_root"].rstrip("/") + "/"
    pk = {}
    for p in meta["packages"]:
        d = p["manifest_path"][len(root):].rsplit("/Cargo.toml", 1)[0]
        deps = {}
        for dep in p["dependencies"]:
            if dep.get("path"):
                deps.setdefault(dep["name"], set()).add(dep.get("kind") or "normal")
        pk[p["name"]] = {"dir": d, "deps": deps}
    return pk


def closure(pk, roots):
    seen, stack = set(roots), []
    for r in roots:
        stack += [d for d in pk[r]["deps"] if d in pk]
    while stack:
        x = stack.pop()
        if x in seen:
            continue
        seen.add(x)
        stack += [d for d, kinds in pk[x]["deps"].items() if d in pk and kinds - {"dev"}]
    return seen


def sdk_closure(pk):
    sdk = metadata("sdks/verifier-js/Cargo.toml")
    names = set()
    for p in sdk["packages"]:
        if not p["manifest_path"].endswith("sdks/verifier-js/Cargo.toml"):
            continue
        for dep in p["dependencies"]:
            if dep.get("path") and dep["name"] in pk and dep.get("kind") in (None, "normal", "build"):
                names.add(dep["name"])
    return closure(pk, sorted(names)) if names else set()


def shards(layout, pk):
    named = {c for s in layout["shards"] for c in s.get("packages", [])}
    unknown = named - set(pk)
    if unknown:
        sys.exit(f"the layout names packages that are not workspace members: {sorted(unknown)}")
    rest = [s for s in layout["shards"] if s.get("rest")]
    if len(rest) > 1:
        sys.exit("at most one shard may take the rest")
    out = []
    for s in layout["shards"]:
        pkgs = sorted(set(s.get("packages", [])) | (set(pk) - named if s.get("rest") else set()))
        out.append(dict(s, packages=pkgs))
    seen = {}
    for s in out:
        for c in s["packages"]:
            if c in seen:
                sys.exit(f"{c} is in both {seen[c]} and {s['name']}")
            seen[c] = s["name"]
    missing = set(pk) - set(seen)
    if missing:
        sys.exit(f"members in no shard: {sorted(missing)} (give one shard \"rest\": true)")
    return out


def derive(layout, pk):
    sdk_deps = None
    gates = []
    base = layout["base"]
    for s in shards(layout, pk):
        clo = closure(pk, s["packages"])
        needs_sdk = SDK_CRATE in clo
        if s.get("scope") == "**":
            scope = ["**", "scripts/**"]
        else:
            scope = list(WORKSPACE_INPUTS) + sorted(pk[c]["dir"] + "/**" for c in clo)
            for c in s["packages"]:
                scope += layout.get("fixtures", {}).get(c, [])
            if needs_sdk:
                if sdk_deps is None:
                    sdk_deps = sdk_closure(pk)
                scope += SDK_INPUTS + sorted(pk[c]["dir"] + "/**" for c in sdk_deps)
            scope = list(dict.fromkeys(scope))
        args = ["--workspace-features"] + NEXTEST
        if s.get("rest"):
            # The rest at RUN time, not at generation time: a member added after this file was
            # generated is selected too, and test-shard.py refuses it until its directory is in
            # the scope -- a red, never a crate whose tests no shard runs.
            args += ["--workspace"]
            for c in sorted(set(pk) - set(s["packages"])):
                args += ["--exclude", c]
        else:
            for c in s["packages"] + s.get("build_also", []):
                args += ["-p", c]
        if s.get("filter"):
            args += ["-E", s["filter"]]
        writes = WRITES + STUB_WRITES
        steps = []
        tools = list(base["tools"])
        if needs_sdk:
            steps.append({"program": "scripts/gatehouse-verifier-sdk.sh", "args": [], "reads": scope,
                          "writes": writes, "loopback": False, "uid": 0})
            tools += ["wasm-pack@0.13.1", "wasm-bindgen@0.2.122"]
        steps.append({"program": "scripts/test-shard.py", "args": args, "reads": scope,
                      "writes": writes, "loopback": True, "uid": 1001})
        if s.get("git_checkout"):
            tools.append("git@2.39.5")
        g = {
            "scope": {"include": scope, "exclude": [], "external": [], "git_history": False},
            "env": base["env"],
            "cap": {"net": "none", "fs_read": scope, "fs_write": writes, "exec": "scoped",
                    "wall_ms": s["timeout_s"] * 1000, "cpu_ms": s["timeout_s"] * 1000,
                    "mem_mb": base["resources"]["mem_mb"], "secrets": []},
            "cmd": [],
            "steps": steps,
            "tools": tools,
            "cwd": "",
            "timeout_s": s["timeout_s"],
            "outputs": [],
            "resources": base["resources"],
            "falsifier": None,
            "seeds": base["seeds"],
        }
        if s.get("git_checkout"):
            g["scope"]["git_checkout"] = True
        gates.append((s, g))
    return gates


def b(xs):
    return "[" + ", ".join(f'#b"{x}"' for x in xs) + "] : Bytes"


def writ_block(gates):
    lines = [BEGIN]
    for s, g in gates:
        v = s["writ"]
        cap = g["cap"]
        lines.append(f"let {v}Cap : ci.Cap = (tag 3 0, tag 3 1, {cap['wall_ms']}, {cap['cpu_ms']}, "
                     f"{cap['mem_mb']}, {b(cap['fs_read'])}, {b(cap['fs_write'])}, [] : Bytes)")
        steps = ", ".join(
            f'(#b"{st["program"]}", {b(st["args"])}, {b(st["reads"])}, {b(st["writes"])}, '
            f'{1 if st["loopback"] else 0}, {st["uid"]})' for st in g["steps"])
        lines.append(
            f'let {v} : ci.Gate = (#b"{s["name"]}", #d"{s["placeholder"]}", {b(g["scope"]["include"])}, '
            f'env, {v}Cap, [] : Bytes, {s["timeout_s"] * 1000}, [] : Bytes, image, {b(g["tools"])}, '
            f'{g["resources"]["disk_mb"]}, {g["resources"]["mem_mb"]}, platform, [] : Bytes, '
            f'{b(g["seeds"])}, {s["measured_ms"]}, [] : Bytes, [{steps}] : ci.Step, '
            f'[(#b"linux/arm64", toolsArm64), (#b"linux/amd64", toolsAmd64)] : ci.Pin)')
    lines.append(END)
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    layout = json.loads(LAYOUT.read_text())
    pk = members(metadata())
    gates = derive(layout, pk)
    want = {ROOT / f".gatehouse/gates/{s['name']}.json": json.dumps(g, indent=2) + "\n" for s, g in gates}
    writ = WRIT.read_text()
    m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), writ, re.S)
    if not m:
        sys.exit(f"{WRIT} has no generated block ({BEGIN!r} ... {END!r})")
    want[WRIT] = writ[:m.start()] + writ_block(gates) + writ[m.end():]
    stale = [p for p, text in want.items() if not p.exists() or p.read_text() != text]
    if check:
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}")
        sys.exit(1 if stale else 0)
    for p in stale:
        p.write_text(want[p])
        print(f"wrote {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
