#!/usr/bin/env bash
# Generate Nucleus/Golden.lean from the golden-vector JSON (gap G3).
#
# tests/golden/*.json is the SINGLE SOURCE. This emits `by decide` checks that the
# Lean kernels (SettlementDecision.sellerGross/refund/classify, Commons.routed)
# reproduce those exact vectors. CI runs this script and `git diff --exit-code`, so
# editing the JSON without regenerating — or a Lean kernel diverging from the
# vectors (caught by `lake build`'s `decide`) — turns CI red. Requires `jq`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
gdir="$root/crates/nucleus-econ-kernels/tests/golden"
out="$root/crates/nucleus-econ-kernels/lean/Nucleus/Golden.lean"

verdict_ctor() { case "$1" in 0) echo Reverse;; 1) echo Partial;; 2) echo Release;; esac; }

{
  echo "/-"
  echo "  GENERATED by scripts/gen-golden-lean.sh from tests/golden/*.json — DO NOT EDIT."
  echo "  Decide-checks that the Lean kernels reproduce the golden vectors (gap G3); the"
  echo "  JSON is the single source shared with the Rust / Solidity / WASM readers."
  echo "-/"
  echo "import Nucleus.Auctions.SettlementDecision"
  echo "import Nucleus.Commons"
  echo ""
  echo "namespace Nucleus.Golden"
  echo "open Nucleus.Auctions.SettlementDecision"
  echo "open Nucleus.Commons"
  echo ""
  echo "-- settlement.json (4-language seal: this Lean reader + Rust + Solidity + WASM)"
  jq -r '.vectors[] |
    "example : classify \(.delivered_bps) = Verdict.VERDICTCTOR_\(.verdict) := by decide\n" +
    "example : sellerGross \(.price_micro) \(.delivered_bps) = \(.seller_gross) := by decide\n" +
    "example : refund \(.price_micro) \(.delivered_bps) = \(.refund) := by decide"' \
    "$gdir/settlement.json"
  echo ""
  echo "-- commons.json (no-skim routing, dust to first): Lean Commons.routed + Rust + WASM."
  echo "-- bps list is shared across vectors (from .shares); routed_conserves PROVES the"
  echo "-- sum == pool for all inputs — these decide the exact per-share split."
  bps="$(jq -r '[.shares[].bps] | join(", ")' "$gdir/commons.json")"
  jq -r --arg bps "$bps" '.vectors[] |
    "example : routed \(.pool_micro) [\($bps)] = [\(.allocations | join(", "))] := by decide"' \
    "$gdir/commons.json"
  echo ""
  echo "-- NOTE: vcg's Lean is property-level (truthfulness/IR/budget), not per-vector;"
  echo "-- VCG vectors are sealed Rust↔WASM (see PROOFS.md + vcg.json _doc)."
  echo "end Nucleus.Golden"
} > "$out.tmp"

# Resolve the verdict-constructor placeholders (jq can't easily branch inline).
sed -e 's/Verdict.VERDICTCTOR_0/Verdict.Reverse/g' \
    -e 's/Verdict.VERDICTCTOR_1/Verdict.Partial/g' \
    -e 's/Verdict.VERDICTCTOR_2/Verdict.Release/g' \
    "$out.tmp" > "$out"
rm -f "$out.tmp"
echo "wrote $out"
