-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: function definitions
import Aeneas
import PortcullisCoreDeclass.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::mediation::opcode]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 100:0-116:1
    Visibility: public -/
def extracted.mediation.opcode
  (op : extracted.mediation.MedOperation) : Result Std.U8 := do
  match op with
  | extracted.mediation.MedOperation.ReadFiles => ok 0#u8
  | extracted.mediation.MedOperation.WriteFiles => ok 1#u8
  | extracted.mediation.MedOperation.EditFiles => ok 2#u8
  | extracted.mediation.MedOperation.RunBash => ok 3#u8
  | extracted.mediation.MedOperation.GlobSearch => ok 4#u8
  | extracted.mediation.MedOperation.GrepSearch => ok 5#u8
  | extracted.mediation.MedOperation.WebSearch => ok 6#u8
  | extracted.mediation.MedOperation.WebFetch => ok 7#u8
  | extracted.mediation.MedOperation.GitCommit => ok 8#u8
  | extracted.mediation.MedOperation.GitPush => ok 9#u8
  | extracted.mediation.MedOperation.CreatePr => ok 10#u8
  | extracted.mediation.MedOperation.ManagePods => ok 11#u8
  | extracted.mediation.MedOperation.SpawnAgent => ok 12#u8

/-- [nucleus_ifc_kernel::extracted::declassify::mask_admits]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 50:0-53:1
    Visibility: public -/
def extracted.declassify.mask_admits
  (mask : Std.U16) (op : extracted.mediation.MedOperation) : Result Bool := do
  let i ← extracted.mediation.opcode op
  let bit ← 1#u16 <<< i
  let i1 ← lift (mask &&& bit)
  ok (i1 != 0#u16)

/-- [nucleus_ifc_kernel::extracted::declassify::effective_conf]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 62:0-73:1
    Visibility: public -/
def extracted.declassify.effective_conf
  (strict : extracted.ifc_confidentiality.ConfLevel)
  (released : extracted.ifc_confidentiality.ConfLevel) (mask : Std.U16)
  (op : extracted.mediation.MedOperation) :
  Result extracted.ifc_confidentiality.ConfLevel
  := do
  let b ← extracted.declassify.mask_admits mask op
  if b
  then ok released
  else ok strict

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::crank]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 33:0-39:1
    Visibility: public -/
def extracted.ifc_confidentiality.crank
  (l : extracted.ifc_confidentiality.ConfLevel) : Result Std.U8 := do
  match l with
  | extracted.ifc_confidentiality.ConfLevel.Public => ok 0#u8
  | extracted.ifc_confidentiality.ConfLevel.Internal => ok 1#u8
  | extracted.ifc_confidentiality.ConfLevel.Secret => ok 2#u8

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::cflows_to]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 58:0-60:1
    Visibility: public -/
def extracted.ifc_confidentiality.cflows_to
  (a : extracted.ifc_confidentiality.ConfLevel)
  (ceiling : extracted.ifc_confidentiality.ConfLevel) :
  Result Bool
  := do
  let i ← extracted.ifc_confidentiality.crank a
  let i1 ← extracted.ifc_confidentiality.crank ceiling
  ok (i <= i1)

/-- [nucleus_ifc_kernel::extracted::declassify::declass_release_ok]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 78:0-86:1
    Visibility: public -/
def extracted.declassify.declass_release_ok
  (strict : extracted.ifc_confidentiality.ConfLevel)
  (released : extracted.ifc_confidentiality.ConfLevel) (mask : Std.U16)
  (op : extracted.mediation.MedOperation)
  (sink_cap : extracted.ifc_confidentiality.ConfLevel) :
  Result Bool
  := do
  let cl ← extracted.declassify.effective_conf strict released mask op
  extracted.ifc_confidentiality.cflows_to cl sink_cap

/-- [nucleus_ifc_kernel::extracted::declassify::declass_fresh]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 104:0-106:1
    Visibility: public -/
def extracted.declassify.declass_fresh
  : Result extracted.declassify.DeclassState := do
  ok { burned := false }

/-- [nucleus_ifc_kernel::extracted::declassify::declass_step]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 129:0-141:1
    Visibility: public -/
def extracted.declassify.declass_step
  (state : extracted.declassify.DeclassState) (sig_ok : Bool)
  (precond_ok : Bool) :
  Result extracted.declassify.DeclassStepResult
  := do
  if state.burned
  then ok { ok := false, next := { burned := true } }
  else
    if sig_ok
    then
      if precond_ok
      then ok { ok := true, next := { burned := true } }
      else ok { ok := false, next := { burned := false } }
    else ok { ok := false, next := { burned := false } }

/-- [nucleus_ifc_kernel::extracted::declassify::value_authorized]:
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 175:0-182:1
    Visibility: public -/
def extracted.declassify.value_authorized
  (committed_bound : Bool) (recorded_present : Bool) (committed : Std.U64)
  (recorded : Std.U64) :
  Result Bool
  := do
  if committed_bound
  then
    if recorded_present
    then ok (committed == recorded)
    else ok false
  else ok false

end nucleus_ifc_kernel
