-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nucleus_ifc_kernel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nucleus_ifc_kernel

/-- [nucleus_ifc_kernel::extracted::mediation::MedOperation]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/mediation.rs', lines 56:0-70:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.mediation.MedOperation where
| ReadFiles : extracted.mediation.MedOperation
| WriteFiles : extracted.mediation.MedOperation
| EditFiles : extracted.mediation.MedOperation
| RunBash : extracted.mediation.MedOperation
| GlobSearch : extracted.mediation.MedOperation
| GrepSearch : extracted.mediation.MedOperation
| WebSearch : extracted.mediation.MedOperation
| WebFetch : extracted.mediation.MedOperation
| GitCommit : extracted.mediation.MedOperation
| GitPush : extracted.mediation.MedOperation
| CreatePr : extracted.mediation.MedOperation
| ManagePods : extracted.mediation.MedOperation
| SpawnAgent : extracted.mediation.MedOperation

/-- [nucleus_ifc_kernel::extracted::ifc_confidentiality::ConfLevel]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/ifc_confidentiality.rs', lines 21:0-28:1
    Visibility: public -/
@[discriminant u8]
inductive extracted.ifc_confidentiality.ConfLevel where
| Public : extracted.ifc_confidentiality.ConfLevel
| Internal : extracted.ifc_confidentiality.ConfLevel
| Secret : extracted.ifc_confidentiality.ConfLevel

/-- [nucleus_ifc_kernel::extracted::declassify::DeclassState]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 98:0-101:1
    Visibility: public -/
structure extracted.declassify.DeclassState where
  burned : Bool

/-- [nucleus_ifc_kernel::extracted::declassify::DeclassStepResult]
    Source: 'crates/nucleus-ifc-kernel/src/extracted/declassify.rs', lines 111:0-119:1
    Visibility: public -/
structure extracted.declassify.DeclassStepResult where
  ok : Bool
  next : extracted.declassify.DeclassState

end nucleus_ifc_kernel
