//! Symmetry reduction for checking N interchangeable pods.
//!
//! Verifying that 10 pods cannot see each other's data naively means checking
//! every ordered pair: 90 checks, each one a booted microVM and a tool call. At
//! 50 pods it is 2450. The standard escape is symmetry reduction — if the pods
//! are genuinely interchangeable then the symmetric group `S_n` acts on the
//! system, the ordered pairs collapse into a single orbit, and checking ONE
//! representative pair establishes the property for all of them.
//!
//! The catch is that this is only sound when the symmetry actually holds, and a
//! reduction that assumes its own precondition is worse than no reduction: it
//! reports success over checks it never ran. Model-checking practice is explicit
//! that unique representatives are guaranteed only for a restricted class of
//! systems, and that deciding orbit membership — the *orbit problem* — is the
//! hard part.
//!
//! So this module never reduces on request. It reduces only after
//! [`verify_equivariance`] has confirmed the observation function really is
//! invariant under the group action, and [`PairSchedule::justification`] records
//! which of the two happened. When symmetry cannot be established the schedule
//! silently widens back to every ordered pair rather than quietly checking less.
//!
//! **nucleus is not fully symmetric, and that matters here.** Pods differ by
//! allocation index: the network allocator hands pod *i* a different subnet from
//! pod *j*, and each pod carries its own SVID and netns. Any observation that
//! can see allocation state is therefore NOT equivariant, and the tests below
//! demonstrate the reduction correctly refusing in exactly that case.

/// A permutation of `0..n`, in one-line notation: `image[i]` is where `i` goes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Permutation {
    image: Vec<usize>,
}

impl Permutation {
    /// The identity on `n` points.
    ///
    /// Composition and the identity exist for the closure test, which verifies
    /// that `generators` really do generate `S_n`. The runtime path only ever
    /// APPLIES a generator, never multiplies two together.
    #[cfg(test)]
    pub fn identity(n: usize) -> Self {
        Self {
            image: (0..n).collect(),
        }
    }

    /// Build from one-line notation, rejecting anything that is not a bijection.
    ///
    /// A non-bijective "permutation" would silently make the orbit computation
    /// wrong rather than loudly wrong, so this is checked rather than trusted.
    pub fn from_image(image: Vec<usize>) -> Option<Self> {
        let n = image.len();
        let mut seen = vec![false; n];
        for &x in &image {
            if x >= n || seen[x] {
                return None;
            }
            seen[x] = true;
        }
        Some(Self { image })
    }

    /// Where this permutation sends `i`.
    pub fn apply(&self, i: usize) -> usize {
        self.image[i]
    }

    /// Compose: `self.then(other)` applies `self` first. Test-only; see `identity`.
    #[cfg(test)]
    pub fn then(&self, other: &Self) -> Self {
        Self {
            image: self.image.iter().map(|&i| other.apply(i)).collect(),
        }
    }
}

/// A generating set for the symmetric group on `n` points.
///
/// `S_n` is generated by the transposition `(0 1)` together with the n-cycle
/// `(0 1 ... n-1)`. That is the whole reason this module is affordable: checking
/// equivariance against two generators costs O(n) work, while checking it
/// against every group element costs `n!` — 3.6 million permutations at n = 10,
/// and the check would be slower than the thing it was meant to avoid.
///
/// Soundness of that shortcut rests on equivariance being closed under
/// composition: if the observation is invariant under each generator, it is
/// invariant under every product of them, hence under the whole group. The
/// tests confirm these really do generate `S_n` for small `n` by closing the
/// set and counting `n!` — otherwise the shortcut would check a subgroup and
/// report a symmetry the system does not have.
pub fn generators(n: usize) -> Vec<Permutation> {
    if n < 2 {
        return Vec::new();
    }
    let mut swap: Vec<usize> = (0..n).collect();
    swap.swap(0, 1);
    let cycle: Vec<usize> = (0..n).map(|i| (i + 1) % n).collect();
    vec![
        Permutation::from_image(swap).expect("transposition is a bijection"),
        Permutation::from_image(cycle).expect("n-cycle is a bijection"),
    ]
}

/// An observation that broke equivariance, with the witness that broke it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SymmetryViolation {
    /// The pair whose observation changed under the permutation.
    pub pair: (usize, usize),
    /// Where the permutation sent that pair.
    pub permuted_pair: (usize, usize),
    /// What the original pair observed.
    pub observed: u64,
    /// What the permuted pair observed. Differs from `observed`, which is the
    /// violation: under a genuine symmetry these must agree.
    pub permuted_observed: u64,
}

impl std::fmt::Display for SymmetryViolation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "pair {:?} observed {} but its image {:?} observed {} — the pods are \
             not interchangeable, so checking one pair would not establish the \
             property for the rest",
            self.pair, self.observed, self.permuted_pair, self.permuted_observed
        )
    }
}

/// Check that `obs` is invariant under the action of `S_n` on ordered pairs.
///
/// `obs(i, j)` is whatever the check actually looks at for observer `i` and
/// subject `j`, reduced to a comparable value. Equivariance means the value
/// depends on the pair's *shape*, not on which particular pods fill it:
///
/// ```text
/// ∀ π ∈ S_n, ∀ i ≠ j.  obs(π(i), π(j)) = obs(i, j)
/// ```
///
/// Returns how many (generator, pair) combinations were checked, so a caller can
/// report the reduction's evidence rather than merely its conclusion.
pub fn verify_equivariance<F>(n: usize, obs: F) -> Result<usize, SymmetryViolation>
where
    F: Fn(usize, usize) -> u64,
{
    let mut checked = 0usize;
    for g in generators(n) {
        for i in 0..n {
            for j in 0..n {
                if i == j {
                    continue;
                }
                let (pi, pj) = (g.apply(i), g.apply(j));
                let before = obs(i, j);
                let after = obs(pi, pj);
                checked += 1;
                if before != after {
                    return Err(SymmetryViolation {
                        pair: (i, j),
                        permuted_pair: (pi, pj),
                        observed: before,
                        permuted_observed: after,
                    });
                }
            }
        }
    }
    Ok(checked)
}

/// Why a schedule has the size it does.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Justification {
    /// Equivariance held, so the ordered pairs form one orbit and a single
    /// representative establishes the property for all of them.
    SymmetryVerified {
        /// How many (generator, pair) combinations were checked.
        combinations_checked: usize,
    },
    /// Symmetry was not established, so nothing is skipped.
    NotReduced {
        /// What went wrong, in the caller's terms.
        reason: String,
    },
}

/// The ordered pairs a cross-pod check must actually run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PairSchedule {
    /// Pairs to check, as `(observer, subject)`.
    pub pairs: Vec<(usize, usize)>,
    /// How many pairs a full enumeration would have been.
    pub full_size: usize,
    /// Why this schedule is the size it is.
    pub justification: Justification,
}

impl PairSchedule {
    /// True when the schedule is smaller than a full enumeration.
    pub fn is_reduced(&self) -> bool {
        self.pairs.len() < self.full_size
    }
}

/// Every ordered pair of distinct participants.
fn all_pairs(n: usize) -> Vec<(usize, usize)> {
    (0..n)
        .flat_map(|i| (0..n).filter(move |&j| j != i).map(move |j| (i, j)))
        .collect()
}

/// Decide which ordered pairs to check, reducing ONLY if symmetry is verified.
///
/// This is the whole point of the module: the reduction is a consequence of a
/// checked property, never of a caller's assertion. If `obs` is not equivariant
/// the schedule is the full enumeration and the violation is reported in the
/// justification, so a run that could not be reduced says so instead of
/// appearing to have verified more than it did.
pub fn pair_schedule<F>(n: usize, obs: F) -> PairSchedule
where
    F: Fn(usize, usize) -> u64,
{
    let full = all_pairs(n);
    let full_size = full.len();
    if n < 2 {
        return PairSchedule {
            pairs: full,
            full_size,
            justification: Justification::NotReduced {
                reason: format!("{n} participant(s): nothing to compare"),
            },
        };
    }
    match verify_equivariance(n, obs) {
        Ok(combinations_checked) => PairSchedule {
            // One orbit, so one representative. `(0, 1)` is as good as any.
            pairs: vec![(0, 1)],
            full_size,
            justification: Justification::SymmetryVerified {
                combinations_checked,
            },
        },
        Err(v) => PairSchedule {
            pairs: full,
            full_size,
            justification: Justification::NotReduced {
                reason: v.to_string(),
            },
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Close the generating set under composition and count the result.
    fn closure(n: usize) -> HashSet<Vec<usize>> {
        let mut seen: HashSet<Vec<usize>> = HashSet::new();
        let mut frontier = vec![Permutation::identity(n)];
        seen.insert(Permutation::identity(n).image.clone());
        let gens = generators(n);
        while let Some(p) = frontier.pop() {
            for g in &gens {
                let q = p.then(g);
                if seen.insert(q.image.clone()) {
                    frontier.push(q);
                }
            }
        }
        seen
    }

    fn factorial(n: usize) -> usize {
        (1..=n).product()
    }

    /// THE soundness test for the whole module.
    ///
    /// Equivariance is checked against two generators rather than all `n!`
    /// group elements. That is only valid if those two really do generate the
    /// whole symmetric group — if they generated a proper subgroup, the check
    /// would pass on a system symmetric merely under that subgroup, and the
    /// reduction would then skip pairs whose property had never been examined.
    #[test]
    fn the_generators_generate_the_whole_symmetric_group() {
        for n in 2..=6 {
            assert_eq!(
                closure(n).len(),
                factorial(n),
                "generators(n={n}) close to a proper subgroup, so verifying \
                 against them would prove symmetry the system may not have"
            );
        }
    }

    /// A genuinely interchangeable observation reduces.
    #[test]
    fn an_equivariant_observation_collapses_to_one_pair() {
        // "did the observer see the subject's canary" -- always no, and in a way
        // that does not depend on which pods are involved.
        let s = pair_schedule(10, |_i, _j| 0);
        assert_eq!(s.pairs, vec![(0, 1)]);
        assert_eq!(s.full_size, 90);
        assert!(s.is_reduced());
        assert!(matches!(
            s.justification,
            Justification::SymmetryVerified { .. }
        ));
    }

    /// An observation that depends on WHICH pod must not reduce.
    ///
    /// This is nucleus's actual situation: the network allocator gives pod `i` a
    /// different subnet from pod `j`, so anything that can observe allocation
    /// state distinguishes the pods and the pairs do not form one orbit.
    #[test]
    fn an_index_dependent_observation_refuses_to_reduce() {
        let s = pair_schedule(10, |i, _j| i as u64);
        assert_eq!(s.pairs.len(), 90, "must fall back to every ordered pair");
        assert!(!s.is_reduced());
        match s.justification {
            Justification::NotReduced { reason } => {
                assert!(reason.contains("not interchangeable"), "{reason}")
            }
            other => panic!("expected a refusal, got {other:?}"),
        }
    }

    /// The violation names a concrete witness, not just "not symmetric".
    #[test]
    fn a_violation_carries_the_pair_that_broke_it() {
        let v = verify_equivariance(4, |i, _j| i as u64).expect_err("must detect asymmetry");
        assert_ne!(v.observed, v.permuted_observed);
        assert_ne!(v.pair, v.permuted_pair);
    }

    /// Non-vacuity: the checker must actually look at pairs. A `verify` that
    /// examined nothing would return `Ok` for every input and every schedule
    /// would "reduce" -- passing the equivariant test above for the wrong reason.
    #[test]
    fn verification_examines_a_pair_for_every_generator() {
        let checked = verify_equivariance(5, |_i, _j| 7).expect("constant obs is equivariant");
        // 2 generators x 5x4 ordered distinct pairs.
        assert_eq!(checked, 2 * 5 * 4);
    }

    /// Fewer than two participants cannot be reduced, and must not claim to be.
    #[test]
    fn a_degenerate_population_is_not_reported_as_reduced() {
        for n in 0..2 {
            let s = pair_schedule(n, |_i, _j| 0);
            assert!(!s.is_reduced());
            assert!(matches!(s.justification, Justification::NotReduced { .. }));
        }
    }

    /// A non-bijection is rejected rather than silently corrupting the orbits.
    #[test]
    fn a_non_bijection_is_not_a_permutation() {
        assert!(Permutation::from_image(vec![0, 0]).is_none());
        assert!(Permutation::from_image(vec![0, 5]).is_none());
        assert!(Permutation::from_image(vec![1, 0]).is_some());
    }
}
