/-
  CiSpec / Golden — GENERATED by `cargo xtask ci-spec gen-golden` from
  crates/ci-spec/tests/golden/queue_traces.json. Do not edit; edit the JSON
  and regenerate. CI regenerates and diffs this file (the econ-lean golden
  seal pattern), so the Rust mirror in crates/ci-spec/src/queue.rs and the
  Lean model cannot drift on a pinned vector without a red.

  Every `example` is closed by `decide`: the kernel evaluates the Lean
  transition function on the same events the Rust test replays.
-/

import CiSpec.Queue
import CiSpec.Capacity

namespace CiSpec.Golden

open CiSpec

/-- one_pr_merges -/
example :
    (run State.init [.enqueue 1, .pass 1, .merge]).queue = [] ∧
    (run State.init [.enqueue 1, .pass 1, .merge]).mergedLog = [1] ∧
    (run State.init [.enqueue 1, .pass 1, .merge]).enqLog = [1] ∧
    (run State.init [.enqueue 1, .pass 1, .merge]).loc 1 = .merged := by
  decide

/-- merge_is_in_enqueue_order -/
example :
    (run State.init [.enqueue 1, .enqueue 2, .pass 2, .merge, .pass 1, .merge, .merge]).queue = [] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 2, .merge, .pass 1, .merge, .merge]).mergedLog = [1, 2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 2, .merge, .pass 1, .merge, .merge]).enqLog = [1, 2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 2, .merge, .pass 1, .merge, .merge]).loc 1 = .merged ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 2, .merge, .pass 1, .merge, .merge]).loc 2 = .merged := by
  decide

/-- timeout_ejects_the_head_and_the_next_moves_up -/
example :
    (run State.init [.enqueue 1, .enqueue 2, .fail 1, .pass 2, .merge]).queue = [] ∧
    (run State.init [.enqueue 1, .enqueue 2, .fail 1, .pass 2, .merge]).mergedLog = [2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .fail 1, .pass 2, .merge]).enqLog = [1, 2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .fail 1, .pass 2, .merge]).loc 1 = .ejected ∧
    (run State.init [.enqueue 1, .enqueue 2, .fail 1, .pass 2, .merge]).loc 2 = .merged := by
  decide

/-- push_dequeues_and_a_re_enqueue_goes_to_the_tail -/
example :
    (run State.init [.enqueue 1, .enqueue 2, .push 1, .enqueue 1, .pass 2, .merge]).queue = [1] ∧
    (run State.init [.enqueue 1, .enqueue 2, .push 1, .enqueue 1, .pass 2, .merge]).mergedLog = [2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .push 1, .enqueue 1, .pass 2, .merge]).enqLog = [1, 2, 1] ∧
    (run State.init [.enqueue 1, .enqueue 2, .push 1, .enqueue 1, .pass 2, .merge]).loc 1 = .queued ∧
    (run State.init [.enqueue 1, .enqueue 2, .push 1, .enqueue 1, .pass 2, .merge]).loc 2 = .merged := by
  decide

/-- cancelling_the_head_ejects_it -/
example :
    (run State.init [.enqueue 1, .pass 1, .cancel 1]).queue = [] ∧
    (run State.init [.enqueue 1, .pass 1, .cancel 1]).mergedLog = [] ∧
    (run State.init [.enqueue 1, .pass 1, .cancel 1]).enqLog = [1] ∧
    (run State.init [.enqueue 1, .pass 1, .cancel 1]).loc 1 = .ejected := by
  decide

/-- cancelling_a_dequeued_pr_changes_nothing_in_the_queue -/
example :
    (run State.init [.enqueue 1, .enqueue 2, .pass 1, .push 2, .cancel 2]).queue = [1] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 1, .push 2, .cancel 2]).mergedLog = [] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 1, .push 2, .cancel 2]).enqLog = [1, 2] ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 1, .push 2, .cancel 2]).loc 1 = .queued ∧
    (run State.init [.enqueue 1, .enqueue 2, .pass 1, .push 2, .cancel 2]).loc 2 = .waiting := by
  decide

/-- the_2026_09_04_group_on_four_runners -/
example : makespan (greedyFrom [0, 0, 0, 0] [45, 30, 28, 25, 23, 20, 15, 15, 10, 10, 5, 5]) = 60 := by
  decide

/-- the_same_group_behind_50_minutes_of_pr_runs -/
example : makespan (greedyFrom [50, 50, 50, 50] [45, 30, 28, 25, 23, 20, 15, 15, 10, 10, 5, 5]) = 110 := by
  decide

/-- one_runner_is_the_sum -/
example : makespan (greedyFrom [0] [3, 4, 5]) = 12 := by
  decide

end CiSpec.Golden
