-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: function definitions
import Aeneas
import PortcullisCoreAttenuation.Types
import PortcullisCoreAttenuation.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace portcullis_core

/-- [portcullis_core::attenuation::chain_effective_authority::{impl core::ops::function::FnMut<(L, &'_ L), L> for portcullis_core::attenuation::chain_effective_authority::closure<L>}::call_mut]:
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 95:36-95:60 -/
def
  attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnMutPairLSharedLL.call_mut
  {L : Type} (categoryLatticeInst : category.Lattice L)
  (c : attenuation.chain_effective_authority.closure L)
  (tupled_args : (L × L)) :
  Result (L × (attenuation.chain_effective_authority.closure L))
  := do
  let (acc, cap) := tupled_args
  let t ← categoryLatticeInst.meet acc cap
  ok (t, c)

/-- [portcullis_core::attenuation::chain_effective_authority::{impl core::ops::function::FnOnce<(L, &'_ L), L> for portcullis_core::attenuation::chain_effective_authority::closure<L>}::call_once]:
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 95:36-95:60 -/
def
  attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnOncePairLSharedLL.call_once
  {L : Type} (categoryLatticeInst : category.Lattice L)
  (c : attenuation.chain_effective_authority.closure L) (p : (L × L)) :
  Result L
  := do
  let (t, _) ←
    attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnMutPairLSharedLL.call_mut
      categoryLatticeInst c p
  ok t

/-- Trait implementation: [portcullis_core::attenuation::chain_effective_authority::{impl core::ops::function::FnOnce<(L, &'_ L), L> for portcullis_core::attenuation::chain_effective_authority::closure<L>}]
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 95:36-95:60 -/
@[reducible]
def
  attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnOncePairLSharedLL
  {L : Type} (categoryLatticeInst : category.Lattice L) :
  core.ops.function.FnOnce (attenuation.chain_effective_authority.closure L) (L
  × L) L := {
  call_once :=
    attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnOncePairLSharedLL.call_once
    categoryLatticeInst
}

/-- Trait implementation: [portcullis_core::attenuation::chain_effective_authority::{impl core::ops::function::FnMut<(L, &'_ L), L> for portcullis_core::attenuation::chain_effective_authority::closure<L>}]
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 95:36-95:60 -/
@[reducible]
def
  attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnMutPairLSharedLL
  {L : Type} (categoryLatticeInst : category.Lattice L) :
  core.ops.function.FnMut (attenuation.chain_effective_authority.closure L) (L
  × L) L := {
  FnOnceInst :=
    attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnOncePairLSharedLL
    categoryLatticeInst
  call_mut :=
    attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnMutPairLSharedLL.call_mut
    categoryLatticeInst
}

/-- [portcullis_core::attenuation::chain_effective_authority]:
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 94:0-96:1
    Visibility: public -/
def attenuation.chain_effective_authority
  {L : Type} (categoryLatticeInst : category.Lattice L) (start : L)
  (caps : Slice L) :
  Result L
  := do
  let i ← core.slice.Slice.iter caps
  let t ← categoryLatticeInst.corecloneCloneInst.clone start
  core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.fold
    (attenuation.chain_effective_authority.closure.Insts.CoreOpsFunctionFnMutPairLSharedLL
    categoryLatticeInst) i t ()

end portcullis_core
