-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [portcullis_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace portcullis_core

/-- Trait declaration: [portcullis_core::category::Lattice]
    Source: 'crates/portcullis-core/src/category.rs', lines 32:0-41:1
    Visibility: public -/
structure category.Lattice (Self : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  meet : Self → Self → Result Self
  join : Self → Self → Result Self
  leq : Self → Self → Result Bool

/-- [portcullis_core::attenuation::chain_effective_authority::closure]
    Source: 'crates/portcullis-core/src/attenuation.rs', lines 95:36-95:60 -/
@[reducible]
def attenuation.chain_effective_authority.closure (L : Type) := Unit

end portcullis_core
