name: Security Audit

on:
  push:
    branches: [main]
    paths:
      - Cargo.lock
      - Cargo.toml
      - crates/**/Cargo.toml
  pull_request:
  merge_group:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2.9.1
      - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # v1
        with:
          denyWarnings: true
