/-
  GENERATED by scripts/gen-golden-lean.sh from tests/golden/*.json — DO NOT EDIT.
  Decide-checks that the Lean kernels reproduce the golden vectors (gap G3); the
  JSON is the single source shared with the Rust / Solidity / WASM readers.
-/
import Nucleus.Auctions.SettlementDecision
import Nucleus.Commons

namespace Nucleus.Golden
open Nucleus.Auctions.SettlementDecision
open Nucleus.Commons

-- settlement.json (4-language seal: this Lean reader + Rust + Solidity + WASM)
example : classify 0 = Verdict.Reverse := by decide
example : sellerGross 1000000 0 = 0 := by decide
example : refund 1000000 0 = 1000000 := by decide
example : classify 2500 = Verdict.Partial := by decide
example : sellerGross 1000000 2500 = 250000 := by decide
example : refund 1000000 2500 = 750000 := by decide
example : classify 9999 = Verdict.Partial := by decide
example : sellerGross 1000000 9999 = 999900 := by decide
example : refund 1000000 9999 = 100 := by decide
example : classify 10000 = Verdict.Release := by decide
example : sellerGross 1000000 10000 = 1000000 := by decide
example : refund 1000000 10000 = 0 := by decide
example : classify 25000 = Verdict.Release := by decide
example : sellerGross 1000000 25000 = 1000000 := by decide
example : refund 1000000 25000 = 0 := by decide
example : classify 5000 = Verdict.Partial := by decide
example : sellerGross 7654321 5000 = 3827160 := by decide
example : refund 7654321 5000 = 3827161 := by decide

-- commons.json (no-skim routing, dust to first): Lean Commons.routed + Rust + WASM.
-- bps list is shared across vectors (from .shares); routed_conserves PROVES the
-- sum == pool for all inputs — these decide the exact per-share split.
example : routed 1000000 [6000, 2500, 1500] = [600000, 250000, 150000] := by decide
example : routed 7 [6000, 2500, 1500] = [5, 1, 1] := by decide
example : routed 9999999 [6000, 2500, 1500] = [6000001, 2499999, 1499999] := by decide

-- NOTE: vcg's Lean is property-level (truthfulness/IR/budget), not per-vector;
-- VCG vectors are sealed Rust↔WASM (see PROOFS.md + vcg.json _doc).
end Nucleus.Golden
