/-
  GENERATED by scripts/gen-golden-lean.sh from tests/golden/*.json — DO NOT EDIT.
  Decide-checks that the Lean kernels reproduce the golden vectors (gap G3); the
  JSON is the single source shared with the Rust / Solidity / WASM readers.
-/
import Nucleus.Auctions.SettlementDecision

namespace Nucleus.Golden
open Nucleus.Auctions.SettlementDecision

-- settlement.json (4-language seal: this Lean reader + Rust + Solidity + WASM)
example : classify 0 = Verdict.Reverse := by decide
example : sellerGross 1000000 0 = 0 := by decide
example : refund 1000000 0 = 1000000 := by decide
example : classify 2500 = Verdict.Partial := by decide
example : sellerGross 1000000 2500 = 250000 := by decide
example : refund 1000000 2500 = 750000 := by decide
example : classify 9999 = Verdict.Partial := by decide
example : sellerGross 1000000 9999 = 999900 := by decide
example : refund 1000000 9999 = 100 := by decide
example : classify 10000 = Verdict.Release := by decide
example : sellerGross 1000000 10000 = 1000000 := by decide
example : refund 1000000 10000 = 0 := by decide
example : classify 25000 = Verdict.Release := by decide
example : sellerGross 1000000 25000 = 1000000 := by decide
example : refund 1000000 25000 = 0 := by decide
example : classify 5000 = Verdict.Partial := by decide
example : sellerGross 7654321 5000 = 3827160 := by decide
example : refund 7654321 5000 = 3827161 := by decide

-- NOTE: commons/vcg Lean-vector decide-checks land in G3b (Commons.lean is in
-- the queued G2a PR; vcg's Lean is property-level). Both are covered by the Rust
-- golden reader today + (commons) the routed_conserves theorem.
end Nucleus.Golden
